### ISSUE TITLE
Pivotal Content Amplification Submission

### ISSUE THREAD

**Issue by tiffanishaw** [dotnet-foundation/content#1]
**Please describe the content.**
The .NET Foundation should amplify this content because this is content regarding .Net applications and it is a great resource that pertains to this specific audience. 

**URL of the content**
http://msft.it/6000TORy0 

**Copy for the content**
Utilize modern tools and platforms for building #dotNET apps with @Pivotal’s free guide. Download now: http://msft.it/6000TORy0

**Date requested**
9/13, per your EdCal

**Channel requested**
Twitter

**Additional context**
Please email me at v-ticara@microsoft.com if you need anything else. 

![DOTNETFDN PIVOTAL TW](https://user-images.githubusercontent.com/55203685/64716820-f4840400-d477-11e9-8571-a3ba84e1a9d0.png)

**Comment by BethMassi** [comment]
@tiffanishaw is this a Microsoft request or Pivotal? The graphic should be branded Pivotal since it's their content. We have a lot of .NET Cloud Native content from Microsoft product team and this looks confusing. Can you provide a Pivotal branded graphic?

**Comment by BethMassi** [comment]
Thanks! I'll get this scheduled to go out today.

**Comment by tiffanishaw** [comment]
Thank you! I’ll circle back around in one week for the post insights.

Best,
Tiffani Shaw
________________________________

**Comment by tiffanishaw** [comment]
Can I please have the post insights for this content? 

https://twitter.com/dotnetfdn/status/1172584731537526790
--


 Thanks!
