### ISSUE TITLE
[AMPLIFICATION] - Title

### ISSUE THREAD

**Issue by Verdinjoshua26** [dotnet-foundation/content#10]
**Please describe the content.**
A clear and concise description of what the content is and why it's important to the .NET open source community. Ex. The .NET Foundation should amplify this content because it provides news about a .NET Foundation new project release [...]

**URL of the content**
Link to the article, blog, video, social post, presentation, etc. 

**Copy for the content**
Suggested copy you want to use for the social post. Please keep in mind the channel limitations (i.e. Twitter 280 characters)

**Date requested**
The date you are requesting us to amplify. We will try to hit that if approved. 

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please see the [Newsletter repo](https://github.com/dotnet-foundation/newsletter)
To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Are you asking for amplification of something?

**Comment by Verdinjoshua26** [comment]
Everything is up and running

**Comment by BethMassi** [comment]
I don't see anything actionable here so closing. Please submit a new PR with the template filled out if you are requesting content amplification.
