### ISSUE TITLE
[AMPLIFICATION] - Creating extensions methods to improve code readibility

### ISSUE THREAD

**Issue by pierrebelin** [dotnet-foundation/content#100]
**Please describe the content.**
It's a blog post about reminding why creating extensions methods are usefull in .NET development. The article is quick and strait to the point!

**URL of the content**
[Link to the article, blog, video, social post, presentation, etc. ](https://goatreview.com/create-extensions-methods-to-improve-csharp-readability/)

**Copy for the content**
2 minutes read tutorial on methods extensions to improve code readibility🔥(https://goatreview.com/create-extensions-methods-to-improve-csharp-readability/)

**Date requested**
At convenience

Have nice day 😁

**Comment by ddskier** [comment]
This will post on Friday, Oct 14 to Twitter, FB, LinkedIn
