### ISSUE TITLE
[AMPLIFICATION] - Podcast episode on gRPC for dotnet developers

### ISSUE THREAD

**Issue by dracan** [dotnet-foundation/content#102]
**Please describe the content.**
Podcast episode on gRPC for dotnet developers.

**URL of the content**
https://unhandledexceptionpodcast.com/posts/0044-grpc/

**Copy for the content**
The latest #UnhandledException podcast is now out! @PoornimaNayar joins host @dracan to chat all about #gRPC for #dotnet developers! https://unhandledexceptionpodcast.com/posts/0044-grpc/

**Date requested**
When best suits you.

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
This will post on Nov 1 to all .NET Fdn handles. I'll repeat it at some point but not sure the date.

**Comment by dracan** [comment]
Amazing, thank you 🙂
