### ISSUE TITLE
[AMPLIFICATION] - Umbraco Community Day Call for Papers

### ISSUE THREAD

**Issue by poornimanayar** [dotnet-foundation/content#104]
**Please describe the content.**
Call for Papers open for the first edition of Umbraco Community Day

**URL of the content**
https://sessionize.com/Umbraco-Community-Day/

**Copy for the content**
Call For Papers - Call for Papers open for the first edition of Umbraco Community Day. Submit your sessions at https://sessionize.com/Umbraco-Community-Day/ #umbraco #dotnet #opensource

**Date requested**
11th Nov, 18th Nov, 25th Nov, 30th Nov, 1st Dec 

**Channel requested**
Facebook, Twitter, Linkedin

**Additional context**
More information about the event here https://day.umbraco.community/

**Comment by ddskier** [comment]
Scheduled for all the dates you requested on all social handles.
