### ISSUE TITLE
[AMPLIFICATION] - Solution1: A conference by the C# Community Discord Server

### ISSUE THREAD

**Issue by mfriedrich228** [dotnet-foundation/content#105]
**Please describe the content.**  
To celebrate the release of .NET 7 and C# 11, we are hosting for the first time a conference for our C# community Discord server with speakers from our server e.g. Fred Silberberg and Tanner Gooding from MSFT, and Matt Jones from Sumo Digital - also the server owner, and guests from the .NET community like Nick Chapsas and Michael Stonis.

**URL of the content**  
**https://www.youtube.com/@csharpcommunitydiscord**

**Copy for the content**  
Solution1 is the first conference organized by the C# community discord server. From Nov 17th to Nov 24th, our speakers will present the new features of .NET 7 and C# 11 followed by sessions about MAUI, ASP.NET Core, and many more. Join us on Discord: https://discord.com/invite/csharp and YT: https://www.youtube.com/@csharpcommunitydiscord

**Date requested**  
ASAP, Nov 16, Nov 17 and if possible Nov 20

**Channel requested**
Facebook, Twitter, LinkedIn

**Additional context**  
Please post this conference schedule with every post:
![c7a1e583-f3b7-42cc-918d-a01a0c6307fd (23)](https://user-images.githubusercontent.com/61104832/201209873-de48aacd-e3e3-4371-8df8-c22538acdf5e.png)

**Comment by ddskier** [comment]
This is scheduled for Nov 11, 16, 17 and 20th. Will post to FB, Twitter, LinkedIn
