### ISSUE TITLE
Solution1: A conference by the C# Community Discord Server - missing character in YT link on LinkedIn and Facebook

### ISSUE THREAD

**Issue by mfriedrich228** [dotnet-foundation/content#106]
Hello!

first of all thank you for the support and posting so fast about our conference. Unfortunately there seems to be a problem with the links on Facebook (e.g. here: https://www.facebook.com/dotnetfoundation/posts/502094775288912) and LinkedIn. The @ character in the URL of YouTube  is missing there: https://www.youtube.com/**@**csharpcommunitydiscord and so if you click on it, you don't get to our channel. Is it possible to fix this for the existing and future posts? That would be cool! :) On Twitter the link works as expected.

Kind regards

Max

**Comment by ddskier** [comment]
Looks like my social posting app screwed it up by stripping all @ characters from posts. I fixed it on FB & LinkedIn as well as future posts. Let me know if the tool strips out the @ again... But I think I fixed it.
