### ISSUE TITLE
[AMPLIFICATION] - .NET nanoFramework now runs on ESP32-C3 (RISC-V)

### ISSUE THREAD

**Issue by josesimoes** [dotnet-foundation/content#107]
**Please describe the content.**
.NET nanoFramework has released firmware images for Espressif ESP32-C3 series. 
.NET now runs on RISC-V processors too!
This was - maybe - the very 1st time .NET ever runed on a RISC-V processor. This is another contribution to increase the reach of .NET as the framework that runs on more platforms. 

**URL of the content**
Twitter: https://twitter.com/nanoFramework/status/1592849360794312704
LinkedIn: https://www.linkedin.com/posts/dotnet-nanoframework_dotnet-riscv-esp32c3-activity-6998615967446495232-yjyj

**Copy for the content**
Follows the tweet content:

<<<<<
Firmware images of .NET @nanoFramework @EspressifSystem ESP32-C3 series have just been released! 🥳🚀
.NET now runs on @risc_v processors too!
How cool is this?!?! 💜🤩
<<<<<

**Date requested**
Published today, so please amplify at your convenience.

**Channel requested**
Facebook, Twitter, LinkedIn

**Additional context**

**Comment by ddskier** [comment]
Apologies for the delay in responding. I reposted  your links on Twitter and LinkedIn several days ago and then I've got this scheduled again for Nov 23.

**Comment by josesimoes** [comment]
@ddskier no need to apologize! 🙂 Thank YOU for taking care of this.
