### ISSUE TITLE
[AMPLIFICATION] - C# for Babies ebook

### ISSUE THREAD

**Issue by maartenba** [dotnet-foundation/content#108]
**Please describe the content.**
Khalid and Maarten worked on a nice illustrated book, C# for babies. Everyone can learn C# from a young age, and this free illustrated book is a baby-proof introduction to introduce your young ones into .NET.

A retweet would be appreciated 🙏

**URL of the content**
https://twitter.com/resharper/status/1592915333161308160?t=cPeNWToDmmygLmpxOB4qGQ&s=19

**Copy for the content**
A retweet would be enough, but feel free to rework to a format that suits you.

https://twitter.com/resharper/status/1592915333161308160?t=cPeNWToDmmygLmpxOB4qGQ&s=19

**Date requested**
November 2022

**Channel requested**
Twitter

**Comment by ddskier** [comment]
I retweeted this a couple days ago but then got slammed. I will repeat this on Nov 22 on Twitter, FB, LinkedIn
