### ISSUE TITLE
[AMPLIFICATION] - "What's new in .NET7" Article

### ISSUE THREAD

**Issue by bigebesikci** [dotnet-foundation/content#109]
**Please describe the content.**
Hi there,
Our colleague created a thorough information about the highlighted features of .NET 7.

**URL of the content**
[Link to the article](https://community.abp.io/posts/whats-new-with-.net-7-tlq2g43w): https://community.abp.io/posts/whats-new-with-.net-7-tlq2g43w

**Copy for the content**
Here are a few interesting features that are now available with the release of C# 11 and .NET 7. 

**Date requested**
Anytime that suits to your schedule is okay.

**Channel requested**
Facebook, Twitter

Thank you 🙏

**Comment by ddskier** [comment]
This is scheduled for Nov 29 on Twitter, FB, LinkedIn. Will repeat the next week too.
