### ISSUE TITLE
[AMPLIFICATION] - .NET nanoFramework now has a Virtual Device 

### ISSUE THREAD

**Issue by josesimoes** [dotnet-foundation/content#112]
**Please describe the content.**
.NET nanoFramework virtual device now available as a .NET Tool.
Perfect for on-the-go development, running on CI-CD pipelines, automated tests and other usage scenarios that benefit from not requiring a real hardware device.
Seamless integrated with our Visual Studio extension!

**URL of the content**
- Tweet: https://twitter.com/nanoFramework/status/1599846731042402304
- LinkedIn: https://www.linkedin.com/posts/dotnet-nanoframework_visualstudio-dotnet-embeddedsystems-activity-7005613824099663872

**Copy for the content**
.NET nanoFramework virtual device now available as a .NET Tool.
Perfect for on-the-go development, running on CI-CD pipelines, automated tests and other usage scenarios that benefit from not requiring a real hardware device.
Seamless integrated with our Visual Studio extension!

**Date requested**
- Tweet and LInledin post out today. Please amplify at your convinience.

**Channel requested**
Facebook, Twitter, LinkedInd

**Comment by ddskier** [comment]
Re-shared your posts on Twitter and LinkedIn and then posting this again on Dec 13
