### ISSUE TITLE
[AMPLIFICATION] - Offline library to get information about countries

### ISSUE THREAD

**Issue by egbakou** [dotnet-foundation/content#113]
**Please describe the content.**

[RESTCountries.NET](https://github.com/egbakou/RESTCountries.NET) is a .NET standard library to get information about countries. Version 3.0.0 was recently released, providing:
- Offline support
- Translation of country names in multiple languages
- Country postal code with the associated regex for validation
- Google Maps and OpenStreetMap location
- Country flag in Unicode, PNG and SVG format
- Time zones information
- Car information
- Start of the week
- Mobile phone prefix information.

This library can be helpful for applications that are intended to be used in several countries, thus solving the problems of internationalization and inclusion.

**URL of the content**
- [Repository](https://github.com/egbakou/RESTCountries.NET)
- [Documentation](https://github.com/egbakou/RESTCountries.NET#readme)
- [Nuget](https://www.nuget.org/packages/RESTCountries.NET)

Thanks in advance !

**Comment by ddskier** [comment]
Scheduled for Dec 26. Will repeat the following week.

**Comment by egbakou** [comment]
Thank you @ddskier !
