### ISSUE TITLE
[AMPLIFICATION] - Dotenv library to read and parsing .env files

### ISSUE THREAD

**Issue by MrDave1999** [dotnet-foundation/content#114]
**Please describe the content.**
[dotenv.core](https://github.com/MrDave1999/dotenv.core) is a open source library to read and parsing .env files in .NET Core and  .NET Framework (4.6+).

**Main features:**
- It has a fluent interface, which makes it simple and easy to use.
- Support for load multiple .env files.
- Support to load the .env file depending on the environment (development, test, staging, or production).
- Searches in parent directories when it does not find the .env file in the current directory.
- Allows to set the base path for a set of .env files.
- Allows to define which keys should be required by the application.
- Support for the variables interpolation.
- Support for mapping keys to a strongly typed object.

**The use of .env files provides two main advantages:**
- Its syntax is easier than an json, so there is less chance of making a mistake.
- It facilitates deployment with Docker Compose, because this application parses and reads .env files.

This library helps developers who are not comfortable using appsettings.json to represent their application settings, so using .env files is an alternative.

**URL of the content**
- [Repository](https://github.com/MrDave1999/dotenv.core)
- [Website](https://mrdave1999.github.io/dotenv.core/)
- [Overview](https://github.com/MrDave1999/dotenv.core#overview)
- [API Documentation](https://mrdave1999.github.io/dotenv.core/api/DotEnv.Core.html)
- [Conceptual Documentation](https://mrdave1999.github.io/dotenv.core/articles/getting_started.html)
- [Nuget](https://www.nuget.org/packages/dotenv.core/)

Thanks in advance!

**Comment by ddskier** [comment]
This will post tomorrow (Dec 27) and repeat next week.

**Comment by MrDave1999** [comment]
@ddskier Thanks! :)
