### ISSUE TITLE
[AMPLIFICATION] - Full-stack .NET web apps in F# (and C#) with charting + reactive forms

### ISSUE THREAD

**Issue by granicz** [dotnet-foundation/content#115]
**Please describe the content.**
I would like to amplify this content because it tells the story of immense productivity with developing full-stack .NET web applications in F# (and C#), and can inspire more developers to use ASP.NET Core.

**URL of the content**
https://intellifactory.com/user/granicz/20221229-full-stack-fsharp-with-charting-reactive-forms-and-more-under-300-loc-with-websharper

**Copy for the content**
It would be great to simply RT my original tweet - https://twitter.com/granicz/status/1609060870289489920 with a message to #csharp #fsharp #aspnetcore developers.

**Date requested**
As soon as you can - the article+my tweet is out now

**Channel requested**
Facebook, Twitter

**Additional context**
Feel free to use this image with the amplification: https://i.imgur.com/ozgeWTWh.png

Thank you!

**Comment by ddskier** [comment]
This will post tomorrow, Jan 3 and repost sometime next week.
