### ISSUE TITLE
[AMPLIFICATION] - Jeff Fritz compares PDF tools

### ISSUE THREAD

**Issue by AnneLazar** [dotnet-foundation/content#116]
**Please describe the content.**
This is content with Jeff Fritz comparing tools IronPDF, Aspose, iText and SyncFusion.

**URL of the content**
https://www.youtube.com/watch?v=Tv3VHsr7pog

**Copy for the content**

What's the best PDF tool out there? Watch Jeff Fritz have a "shoot out" between Aspose, IronPDF, SyncFusion and iText

**Date requested**
Friday 6 January 

**Channel requested**
Facebook, Twitter

**Additional context**

**Comment by ddskier** [comment]
This is scheduled for Jan 10 and will repeat the following week.
