### ISSUE TITLE
[AMPLIFICATION] - Reed-Solomon Erasure coding project

### ISSUE THREAD

**Issue by egbakou** [dotnet-foundation/content#117]
**Please describe the content.**
Erasure coding is a data protection method in which data is broken into fragments and stored across multiple storage devices or locations. The advantages of erasure coding include using less storage in contrast to data replication and the ability to reconstruct the original data even if some fragments are missing. Reed-Solomon is one of the methods of erasure coding. The project, [reedsolomon](https://github.com/egbakou/reedsolomon), is an implementation of it in C#/.NET.

Note: I am looking for contributors to improve the project.

**URL of the content**
Repo: https://github.com/egbakou/reedsolomon
Doc: https://github.com/egbakou/reedsolomon#readme

**Additional context**
![image](https://user-images.githubusercontent.com/26142591/213575150-9b797e9c-6150-4df2-931c-a6649742615c.png)
![image](https://user-images.githubusercontent.com/26142591/213575190-3e980f62-1552-48b5-8199-ee7f61739871.png)

Hoping that my request will be accepted :)
Thank you !

**Comment by ddskier** [comment]
This will be posted to FB, Twitter, LinkedIn on Jan 23. I will repeat it next week.

**Comment by egbakou** [comment]
Thank you @ddskier

**Comment by egbakou** [comment]
Hi @ddskier,
For the upcoming amplification, can you please only share the link to the repo without including the images ?
 I've already added a social card to the repo, as you can see below:
![image](https://user-images.githubusercontent.com/26142591/214942225-a3161146-6be0-4807-af44-1dc763397d56.png)

I believe this will result in more engagement. 
Thank you.

**Comment by ddskier** [comment]
Done
