### ISSUE TITLE
[AMPLIFICATION] - Commemorating Charlie Poole's Contributions to the NUnit Project

### ISSUE THREAD

**Issue by SeanKilleen** [dotnet-foundation/content#118]
**Please describe the content.**

Charlie Poole, the steward of NUnit (now a .NET Foundation project) for **20 years**, is stepping back.

We remaining members of the NUnit Core team wanted to commemorate his incredible tenure and the work he put in that has enabled so many developers to succeed.

**URL of the content**
Announcement: https://nunit.org/news/update/nunit/2023/01/29/celebrating-charlie-poole.html

**Copy for the content**

However best in your own voice but suggestions include something like:

* The #NUnit Project Commemorates @CharliePoole's 20+ years of contributions & leadership -- add your thanks via the link in the announcement! #dotnet #oss
* Few #oss projects have been around in #dotnet as long as #nunit, let alone with one key steward. @CharliePoole is stepping back after *over 20 years* -- read the team's thanks, and send your own!

**Date requested**

Your earliest convenience.

**Channel requested**

Facebook, Twitter

**Comment by CharliePoole** [comment]
@SeanKilleen I'm very touched by this. Thank you. 

One comment... can you make it a little clearer that other people actually created NUnit? I was a guy who came to contribute back in 2002 and outlasted everyone else.

**Comment by SeanKilleen** [comment]
@CharliePoole I'll add phrasing to the announcement specifically clarifying that you didn't create it 👍 though we reviewed it amongst the core team and we all felt saying you led the project for 20+ years was an accurate statement.

> I was a guy who came to contribute back in 2002 and outlasted everyone else.

Nice try, humble guy.

**Comment by ddskier** [comment]
This will post tomorrow 1/30 to .NET Foundation social handles on Twitter, FB, LinkedIn. Will repeat next week

**Comment by SeanKilleen** [comment]
@ddskier thanks so much! ♥️
