### ISSUE TITLE
[AMPLIFICATION] - AOP with Interceptors and IL/Code Weaving in .NET Applications

### ISSUE THREAD

**Issue by EngincanV** [dotnet-foundation/content#119]
**Please describe the content.**
Hi, I created a post, that describes what Aspect Oriented Programming is and how it can help developers to improve their applications' modularity. I aimed to create a practical guide by showing some common approaches (**Interceptors** and **IL/Code Weaving**) to achieve this programming paradigm.

**URL of the content**
[AOP with Interceptors and IL/Code Weaving in .NET Applications](https://engincanv.github.io/aop/aspect-oriented-programming/interceptors/code-weaving/il-weaving/.net/2023/01/29/aop-with-interceptors-and-il-code-weaving.html)

**Copy for the content**
Aspect-oriented programming is a paradigm that aims to increase applications' modularity by allowing the separation of cross-cutting concerns. In this article, you can find a practical guide by showing Interceptors and IL/Code Weaving to achieve this programming paradigm.

**Date requested**
Anytime that suits your schedule is okay for me.

**Channel requested**
LinkedIn, Twitter

**Comment by ddskier** [comment]
This will post to Twitter, FB, LinkedIn on Feb 1 and repeat next week
