### ISSUE TITLE
[AMPLIFICATION] - Hello World FIlm

### ISSUE THREAD

**Issue by shawnwildermuth** [dotnet-foundation/content#12]
I've created a feature-length documentary film about inclusion and diversity in software development. Here's a short description:

This documentary film will talk about software developers in their own voices. These workers are unlike most others in today’s economy. Software developers come from a wide range of backgrounds and educations. They have a passion for work that most people do not understand. In addition, the film will dive into the lack of diversity and inclusion inside the industry. It will attempt to explain why women and people of color don’t pursue software careers or why retaining them is the next big challenge. This is especially relevant when you look back and see how important women were to the pioneering early days of the software industry. Our audiences include software developers, women’s and racial injustice activists, and those newly interested in feature-length documentaries.

**URL of the content**
https://helloworldfilm.com

**Copy for the content**
Shawn Wildermuth's first film is coming this fall. Sign up at helloworldfilm.com to be notified of how to watch it when it releases! 

**Date requested**
Any dates before September 2020

**Channel requested**
Facebook, Twitter

**Additional context**
![title-only](https://user-images.githubusercontent.com/568272/86567887-0cae9d80-bf3a-11ea-97b8-5db5031a7436.jpg)

**Comment by ddskier** [comment]
I've scheduled for July 8 on FB and Twitter and will repeat periodically
