### ISSUE TITLE
[AMPLIFICATION] - .NET nanoFramework can now run on Silicon Labs Giant Gecko

### ISSUE THREAD

**Issue by josesimoes** [dotnet-foundation/content#120]
**Please describe the content.**
Silicon Labs Giant Gecko S1 MCUs can now run .NET nanoFramework! 
We've just added support for it, running on top of Azure RTOS. All this was kindly sponsored by Skyworks Inc. who's using .NET all the way from desktop to the hardware.

**URL of the content**
Tweet: https://twitter.com/nanoFramework/status/1622906665895972865
LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:7028674781591789569
Blog with full story: https://www.nanoframework.net/welcome-silabs-giant-gecko/ 

**Copy for the content**
Silicon Labs Giant Gecko S1 MCUs can now run .NET nanoFramework! 
We've just added support for it, running on top of Azure RTOS. All this was kindly sponsored by Skyworks Inc. who's using .NET all the way from desktop to the hardware.

**Date requested**
Any schedule will be just fine.

**Channel requested**
Facebook, Twitter, LinkedIn

**Additional context**
This is a great example of responsible use of Open Source by a large corporation. Skyworks has sponsored a significant development effort for .NET nanoFramework project. With this we are now running on a new platform from a new vendor and using an RTOS (Azure RTOS) that wasn't supported before.

**Comment by ddskier** [comment]
This will post to all handles tomorrow 2/24/2023 and repeat next week
