### ISSUE TITLE
[AMPLIFICATION] - 50th episode of the Unhandled Exception podcast - Hot Reload with David Wengier

### ISSUE THREAD

**Issue by dracan** [dotnet-foundation/content#121]
**Please describe the content.**
The .NET community would find this interesting as it's about dotnet hot-reload, which is now quite a big thing in dotnet.

**URL of the content**
https://unhandledexceptionpodcast.com/posts/0050-hotreload/

**Copy for the content**
The #UnhandledException podcast has now reached its 50th episode!!! 🎉 In it, @dracan was joined by @davidwengier from the Rosyln IDE team, to chat about #dotnet hot-reload, and how it works 🔥 https://unhandledexceptionpodcast.com/posts/0050-hotreload/

**Date requested**
Whenever suits you best

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
This will post tomorrow 3/3 and repeat next week.

**Comment by dracan** [comment]
Amazing - thank you 🙂🙏
