### ISSUE TITLE
[AMPLIFICATION] - TechBash 2023 call for speakers

### ISSUE THREAD

**Issue by alvinashcraft** [dotnet-foundation/content#122]
**Please describe the content.**
The TechBash 2023 CFP is now open (thru April 11th). Much of our sessions tend to be geared toward developers in the .NET space. We would love to have speakers from the community submit sessions, workshops, and keynotes for our event this fall.

**URL of the content**
[TechBash 2023 on Sessionize](https://sessionize.com/techbash-2023/)
[CFP info on our website](https://techbash.com/#CallForSpeakers)

**Copy for the content**
The TechBash 2023 developer conference CFP is open now thru Apr 11. Submit your sessions, workshops, and keynotes today, and join us in the Poconos this fall.

**Date requested**
Any weekday in March 2023 would be awesome.

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
N/A

**Comment by nicoleabuhakmeh** [comment]
I'll be advertising the event closer to the date - I've put it on my calendar. I'm closing this CFP.

**Comment by alvinashcraft** [comment]
Thanks so much, Nicole!
