### ISSUE TITLE
[AMPLIFICATION] - How to use xUnit attributes theory and facts

### ISSUE THREAD

**Issue by pierrebelin** [dotnet-foundation/content#123]
Please describe the content.
It's a blog post to discover how to use xUnit attributes theory and facts, usefull in .NET tests. The article is quick and strait to the point!

URL of the content
[Link to the article, blog, video, social post, presentation, etc.](https://goatreview.com/create-efficent-csharp-tests-with-xunit/)

Copy for the content
Do you know the difference between the attribute Theory and Fact on xUnit test library ? 😎

xUnit contains multiple attributes to improve the readability of your tests, mainly by facilitating the arguments inside your function.

Read more here : https://goatreview.com/create-efficent-csharp-tests-with-xunit/

Date requested
At convenience

Have nice day 😁

**Comment by ddskier** [comment]
I posted today and will post again next week
