### ISSUE TITLE
[AMPLIFICATION] - Mastering complex objects comparison using SequenceEqual on C#

### ISSUE THREAD

**Issue by pierrebelin** [dotnet-foundation/content#124]
**Please describe the content.**
It's a blog post to discover how to master complex objects comparison using SequenceEqual on C#. The article is quick and strait to the point!

**URL of the content**
https://goatreview.com/mastering-sequenceequal-csharp/ (will be published the 20th march)

**Copy for the content**
🎓Learn how to compare enumerable with complex types in 2 minutes

- Works directly with types without references
- Requires implementation of IEqualityComparer for complex types

Subscribe at the newsletter at the bottom of the article to get more articles like this 😎
By Pierre Belin @pierrebelin

**Date requested**
After the 21th march

**Channel requested**
Newsletter and LinkedIn

**Additional context**

**Comment by ddskier** [comment]
This is set up for Mar 22 and will repeat the following week.
