### ISSUE TITLE
[AMPLIFICATION] - Why Use ABP Framework Event

### ISSUE THREAD

**Issue by bigebesikci** [dotnet-foundation/content#125]
Hi there, it's me again! :)

We are organizing a new episode of our regular meetings for [Open Source ABP Framework](https://github.com/abpframework/abp) community. I am sending the details below:

Title: Why should I use the ABP Framework as a .NET developer?
Event date: March 30, 2023
Event time: 18:00 UTC
Speakers: @hikalkan(https://twitter.com/hibrahimkalkan), @ebicoglu(https://twitter.com/alperebicoglu), @berkansasmaz (https://twitter.com/berkansasmazz)
Sponsors: JetBrains(3 free annual personal subscription to [dotUltimate](https://www.jetbrains.com/dotnet/) giveaway)

**URL of the content**
YouTube link: https://www.youtube.com/watch?v=TS8_iHkuCjw
Kommunity event link: https://kty.li/64PV8

**Copy for the content**
📆 Did you register to the new episode of #ABPCommunityTalks?
It will be about "Why You Should Use the #ABPFramework as a #dotNET Developer"
🎁 Don't forget about the 3 @JetBrains dotUltimate & 2 ABP Commercial Personal License giveaway!
Register from 👉 https://kty.li/64PV8

**Date requested**
23rd of March and the 29th or 30th of March would be perfect!

**Channel requested**
Facebook, Twitter, Newsletter

**Additional context**
LinkedIn/Twitter Size Image:
![abp-community-talk](https://user-images.githubusercontent.com/78538870/225620241-e9f7f19a-949c-4fe9-b682-cd8369469355.png)
Instagram Story Size Image:
![abp-community-talk-5](https://user-images.githubusercontent.com/78538870/225620204-36c62d69-529c-4d99-a572-57538887e205.png)
Instagram Post Size Image:
![abp-community-talk-2](https://user-images.githubusercontent.com/78538870/225620169-60dbba98-9afc-4872-ac6f-69a53ab9f8ec.png)

Thank you in advance 🙏

**Comment by ddskier** [comment]
Scheduled for Mar 23 and Mar 29.
