### ISSUE TITLE
[AMPLIFICATION] - Global Azure UK Community Event Call For Proposal Announcement

### ISSUE THREAD

**Issue by poornimanayar** [dotnet-foundation/content#126]
**Please describe the content.**
Global Azure UK Community Event Call For Proposal Announcement

**URL of the content**
https://sessionize.com/global-azure-london-2023/

**Copy for the content**
#CFP is now open for Global Azure London 2023. As part of the Global Azure series, we're excited to be hosting an event at the Microsoft Reactor in London on 12th May 2023. Apply now to be a speaker 

**Date requested**
24th March, 6th April

**Channel requested**
Facebook, Twitter, LinkedIn

**Comment by ddskier** [comment]
This is scheduled for Mar 24 and Apr 6 on all .NET Foundation social handles
