### ISSUE TITLE
[AMPLIFICATION] - Global Azure UK Community Event Announcement

### ISSUE THREAD

**Issue by poornimanayar** [dotnet-foundation/content#127]
**Please describe the content.**
Newsletter content for Global Azure UK Community Event

**URL of the content**
https://sessionize.com/global-azure-london-2023/

**Copy for the content**
As part of the [[Global Azure](https://globalazure.net/)](https://globalazure.net/) series, we're excited to be hosting an event at the **[[Microsoft Reactor](https://developer.microsoft.com/en-us/reactor/)](https://developer.microsoft.com/en-us/reactor/)** in London on **May 12th**!

Expect a day packed full of awesome Azure talks, covering everything from PaaS, DevOps, IoT, AI / ML, security, tooling, and beyond.

This is also a great chance to network with MVPs and experts in the Azure world.

Talks will be delivered to our live audience and streamed on the Microsoft Developers YouTube channel.

**Date requested**
March Newsletter

**Channel requested**
Newsletter

**Comment by nicoleabuhakmeh** [comment]
Adding to the March Newsletter! Thank you for submitting!

**Comment by nicoleabuhakmeh** [comment]
I added the CFP and the Event. I'll run the event again in the April newsletter too.

**Comment by nicoleabuhakmeh** [comment]
I've added this to the April Newsletter for next month's event. Closing this issue
