### ISSUE TITLE
[CREATION] - AI is on the rise 

### ISSUE THREAD

**Issue by AnneLazar** [dotnet-foundation/content#128]
**Please describe the content you want to create.**

A software developers view on AI and how it can be used by engineers.

**Target date**
3 April

**Channel requested**
Blog, Website

**Additional context**
(https://docs.google.com/document/d/16QO-7j4g0lTHhbdmC4Fs6T3Flxn2tDpdJf0jq7HnrNs/edit?usp=sharing)

**Comment by nicoleabuhakmeh** [comment]
Hi @AnneLazar - I'm unable to open that link, can you turn sharing on

**Comment by AnneLazar** [comment]
Hi Nicole Apologies please try this link instead https://docs.google.com/document/d/1X_Tt8A8KaxzkqQOGoFtBZ1T8sMEBPRgVbZqhqki7He0/edit?usp=sharing
