### ISSUE TITLE
[AMPLIFICATION] - ABP .NET Conf'23 with .NET Foundation sponsorship!

### ISSUE THREAD

**Issue by bigebesikci** [dotnet-foundation/content#130]
**Please describe the content.**
Hi there, we are doing regular talks as you are aware. This time, we took it to the next level with an actual day-long conference.
We are proud to say that .NET Foundation is one of the sponsors of this event. So it would be great to annonce it on your socials for a couple of times, as well.

I am attaching the social media visuals for the event and the one we created specially for .NET Foundation in the below of this issue.

We appreciate all your help, sponsorship and effort!! Thank you so much 🙏

**URL of the content**
https://kommunity.com/volosoft/events/1st-abp-conference-96db1a54

**Copy for the content**

### **BEFORE EARLY-BIRD:**
> ⏰ Time is running out to get early-bird tickets to ABP .NET Conf'23! ⏰
> Don't miss out on hearing from an incredible lineup of speakers, including .NET experts and Microsoft MVPs.
> LAST DAY to catch early-bird: APRIL 21, 2023
> Register now and join the excitement 👉 https://kty.li/6GxGK
> #ABPConf23

----------

### **ANYTIME:**
> 🚨 Attention all .NET developers!
> The ABP Conference'23 is the event you've been waiting for.
> Join us for expert-led sessions, networking opportunities, and inspiration.
> Register today 👉 https://kty.li/6GxGK
> #ABPConf23
----------
> 🌎 Join the global .NET community at the ABP Conference'23! This virtual event is the perfect opportunity to connect with peers, learn about the latest trends, and advance your career.
> Register today 👉 https://kty.li/6GxGK
> #ABPConf23
----------
> .NET Foundation proud to present!
> 💪 ABP .NET Conf'23 offers a chance to connect with the .NET community!
> This virtual event is the perfect opportunity to network with peers, learn from experts, and advance your career. 
> Register today 👉 https://kty.li/6GxGK
> #ABPConf23

**Date requested**

- BEFORE EARLY BIRD: 2 times before 21st of April, 2023
- ANYTIME: 3-4 times before the event date which is May 10th, 2023

**Channel requested**
Facebook, Twitter, Newsletter

**Additional context**
![abpconf-banner-komm-w-sponsors](https://user-images.githubusercontent.com/78538870/232067515-fb000f22-86eb-4692-9155-61eecaaa266e.png)
![abpconf-banner-w-sponsors](https://user-images.githubusercontent.com/78538870/232067530-117fa940-eeaf-4394-a4d5-d2dc3dc97e54.png)
![dotnet-foundation-1_1](https://user-images.githubusercontent.com/78538870/232068357-f1855fcc-ac64-4143-8010-9aa1067b7d0d.png)
![dotnet-foundation-16_9](https://user-images.githubusercontent.com/78538870/232068365-57f65262-fb23-4383-8408-6e050ff84c48.png)

**Comment by ddskier** [comment]
I've scheduled early bird on social for Tues and Friday this week. I haven't had a chance to do the other posts yet.

**Comment by bigebesikci** [comment]
thank you so much 🙏

**Comment by nicoleabuhakmeh** [comment]
Added to the April Newsletter.
