### ISSUE TITLE
[AMPLIFICATION] - Unhandled Exception Podcast episode about Elastic Search with Steve Gordon

### ISSUE THREAD

**Issue by dracan** [dotnet-foundation/content#131]
**Please describe the content.**
This is for the next Unhandled Exception podcast episode, which is a podcast mostly about .NET and .NET projects/technologies.

**URL of the content**
https://unhandledexceptionpodcast.com/posts/0052-elasticsearch/

**Copy for the content**
The next #UnhandledException podcast episode has now dropped! In it, @dracan joined by @stevejgordon to chat about @elastic, its use cases, and the #dotnet client libraries Steve has been working on. https://unhandledexceptionpodcast.com/posts/0052-elasticsearch/ #elastic #elasticsearch

**Date requested**
Whenever suits you best :)

**Channel requested**
Facebook, Twitter, Newsletter

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Scheduled for Wed Apr 19 and will repeat sometime next week or the following

**Comment by nicoleabuhakmeh** [comment]
Added to the April Newsletter

**Comment by dracan** [comment]
> Added to the April Newsletter

Amazing! Thank you 😊🙏
