### ISSUE TITLE
[AMPLIFICATION] - "C# - Expression Trees"

### ISSUE THREAD

**Issue by EngincanV** [dotnet-foundation/content#132]
**Please describe the content.**

Hi, I created a post, that describes Expression Trees. It's an interesting feature of the C# language. Nevertheless, it's overlooked by most developers. So, I wanted to create a post that fills this gap.

**URL of the content**
https://engincanv.github.io/c%23/expression-trees/2023/04/16/csharp-expression-trees.html

**Copy for the content**

Expression Trees is one of the most important and interesting feature of the C# language. Nevertheless, it’s overlooked by most developers. In this article, I wanted to fill this gap and describe Expression Trees with examples.

**Date requested**
Anytime on weekdays is okay for me.

**Channel requested**
Twitter, LinkedIn

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Scheduled for Thurs Apr 20th and will repeat sometime the next week.
