### ISSUE TITLE
[AMPLIFICATION] - Speeding Up ASP.NET Application Tips & Tricks

### ISSUE THREAD

**Issue by bigebesikci** [dotnet-foundation/content#133]
**Please describe the content.**
Hi there,
One of our team mates created a blog post in which there are beneficial tips and tricks for speeding up an ASP.NET Core web application. It'd be great to share with .NET Foundation community to benefit from it.

Thank you!

**URL of the content**
https://blog.abp.io/abp/Speed-Up-Your-ASP.NET-Application

**Copy for the content**

"Speed Up Your ASP.NET Application" provides tips and tricks to optimize the performance of your ASP.NET application for better speed, responsiveness, and user experience... Read from 👉 https://blog.abp.io/abp/Speed-Up-Your-ASP.NET-Application

**Date requested**
Any time that suits to your agenda is fine. :)

**Channel requested**
Facebook, Twitter, Newsletter

**Comment by ddskier** [comment]
This will post today and repeat next week on social. Not closing this because of newsletter ask.

**Comment by nicoleabuhakmeh** [comment]
Added to the Newsletter for April
