### ISSUE TITLE
[AMPLIFICATION] - The thing to understand about how Visual Studio integrates debugging in Docker Compose

### ISSUE THREAD

**Issue by pierrebelin** [dotnet-foundation/content#134]
**Please describe the content.**
It's a blog post to discover how Visual Studio integrates debugging in Docker Compose. The article is quick and strait to the point!

**URL of the content**
[Link ](https://goatreview.com/understand-how-visual-studio-integrates-debugging-in-docker-compose/)

**Copy for the content**
Visual Studio has a perfect integration of Docker Compose to debug inside containers
🎓Learn the thing to understand about how Visual Studio do it.

➡️ Article => https://goatreview.com/understand-how-visual-studio-integrates-debugging-in-docker-compose/
Subscribe at the newsletter at the bottom of the article to get more articles like this 😎
By @pierrebelin

**Date requested**
No date requested

**Channel requested**
LinkedIn, Twitter, Newsletter

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
This will post Tues, May 2 and repeat another time. Not closing because of newsletter request.

**Comment by pierrebelin** [comment]
This one can be closed
