### ISSUE TITLE
[AMPLIFICATION] - Unhandled Exception podcast episode 53: We Are .NET

### ISSUE THREAD

**Issue by dracan** [dotnet-foundation/content#135]
**Please describe the content.**
This is for the next Unhandled Exception podcast episode, which is a podcast mostly about .NET and .NET projects/technologies.

**URL of the content**
https://unhandledexceptionpodcast.com/posts/0053-wearedotnet/

**Copy for the content**
The next #UnhandledException podcast is now out! In it, host @dracan was joined by @TimCadenbach and @jost0101 to chat all about the rapidly growing @wearedotnet community they've built! 🔥 https://unhandledexceptionpodcast.com/posts/0053-wearedotnet/ #dotnet #wearedotnet

**Date requested**
Any date

**Channel requested**
Facebook, Twitter, Newsletter

**Additional context**
Add any other context or screenshots about the request here.

**Comment by dracan** [comment]
Amazing - thank you so much for this 😊🙏
Just noticed that I hadn't set a title for this issue 🤦‍♂️ So I've just renamed it now.

**Comment by nicoleabuhakmeh** [comment]
Added to May Newsletter
