### ISSUE TITLE
[AMPLIFICATION] - The nopCommerce article about moving to .NET 7

### ISSUE THREAD

**Issue by alexsolntsev** [dotnet-foundation/content#137]
**Please describe the content.**
We would like to share margin performance improvements after moving from .NET 6 to .NET 7 to the community. Also, we share some thoughts on .NET 7 of professional developers and .NET bloggers.

**URL of the content**
https://www.nopcommerce.com/en/blog/dotnet-7-updates-and-nopcommerce-performance

**Copy for the content**
Social media text:

```
Improving performance by 14% was one of the main outcomes of the .NET 7 update for nopCommerce 📈

Read their article and find out about:

✔️ performance-related updates; 
✔️ experts’ thoughts about the .NET 7; 
✔️ a performance evaluation of nopCommerce after a .NET 7 upgrade.

https://www.nopcommerce.com/en/blog/dotnet-7-updates-and-nopcommerce-performance
```

**Date requested**
Since the .NET 7 release date was quite a while and .NET 8 is upcoming, it will be great to publish social media posts within a week.

**Channel requested**
Facebook, Twitter, LinkedIn, Newsletter (if possible)

**Additional context**
nopCommerce logo: https://res.cloudinary.com/ecommerceberlin/image/upload/v1574940914/Awards_vote/logo_nopCommerce.png

Thank you for your help 🖖

**Comment by ddskier** [comment]
This is scheduled on .NET Foundation social handles for 5/18 and will repeat again the following week. Not closing because of newsletter request.
