### ISSUE TITLE
[AMPLIFICATION] - Rx.NET v6.0 with support for .NET 6.0 and .NET 7.0 is available.

### ISSUE THREAD

**Issue by HowardvanRooijen** [dotnet-foundation/content#138]
**Please describe the content.**
v6.0 of the Reactive Extensions for .NET (a DNF project) with support for .NET 6.0 & .NET 7.0 is available. This is the first release in 2.5 years and marks a transition of project maintainer. It's also a good news story about a less obvious, but incredibly valuable role that the .NET Foundation plays - enabling projects to be moved from one maintainer to another to enable continuity.

**URL of the content**
https://endjin.com/blog/2023/05/rx-dotnet-v6-released

**Copy for the content**
Rx .NET v6.0 with support for .NET 6.0 & .NET 7.0 https://endjin.com/blog/2023/05/rx-dotnet-v6-released

**Date requested**
ASAP

**Channel requested**
All please: Facebook, Twitter, Newsletter

**Additional context**
We've also published a high level roadmap for v7 here: https://github.com/dotnet/reactive/discussions/1868

**Comment by ddskier** [comment]
Scheduled for Mon, 5/22. Will repeat at least once. I scheduled the blog post first and the repo for 1 min after. Not closing because of newsletter request.

**Comment by nicoleabuhakmeh** [comment]
Added to the Newsletter!
