### ISSUE TITLE
[AMPLIFICATION] - Entity Framework Power Tools cross platform CLI now available

### ISSUE THREAD

**Issue by ErikEJ** [dotnet-foundation/content#139]
**Please describe the content.**
The popular and highly rated Visual Studio extension EF Core Power Tools for reverse engineering and more is now available a a cross platform .NET global tool for Windows, macOS and Linux. Take advantage of the many features and options directly from the command line, like mapping of Azure SQL/SQL Server stored procedures & functions and much more.

**URL of the content**
https://github.com/ErikEJ/EFCorePowerTools/tree/master/src/GUI/efcpt

**Copy for the content**
Now available: Entity Framework Power Tools cross platform CLI - map stored procedures & functions (and much more) directly from the command line.

**Date requested**
May 30

**Channel requested**
Facebook, Twitter

**Comment by ddskier** [comment]
Scheduled for May 30 on FB, Twitter, LinkedIn
