### ISSUE TITLE
[AMPLIFICATION] - .NET Summit Belarus

### ISSUE THREAD

**Issue by meilalina** [dotnet-foundation/content#14]
**Please describe the content.**
1. Online conference .NET Summit Belarus, August 7-8, 2020.
2. Organizers: .NET User Group Minsk (https://www.facebook.com/groups/dotnet.minsk/, https://www.meetup.com/NET-User-Group-Minsk/) and SPACE_ community hub.
3. The conference program contains of presentations of technical .NET use cases and related technologies. 

**URL of the content**
https://dotnetsummit.by/

**Copy for the content**
4th @DotNetBy is coming soon! Join us and enjoy 2 days online event, 3 tracks of talks, communication in speaker’s rooms, and fantastic .NET-speakers team! Let’s meet together on August 7-8. Grab your ticket at dotnetsummit.by. Use promocode DF10 and get 10% discount! ;)

**Date requested**
July 30, 2020

**Channel requested**
Twitter

**Additional context**
Thanks a lot for your support!

**Comment by ddskier** [comment]
July 30th is the same day as .NET Conf. I will schedule this for July 31 and repeat it on Aug 4. I will also push on the FB channel too.

**Comment by meilalina** [comment]
Awesome! Thank you very much.

**Comment by ddskier** [comment]
These have been scheduled for July 31 and Aug 4.
