### ISSUE TITLE
[AMPLIFICATION] - Visualize API response directly in Visual Studio with .http file

### ISSUE THREAD

**Issue by pierrebelin** [dotnet-foundation/content#140]
Please describe the content.
It's a blog post to discover how to use the new integration of http file inside Visual Studio.. The article is quick and strait to the point!

URL of the content
https://goatreview.com/visualize-api-responses-in-visual-studio-http-file/ 

Copy for the content
🎓 Are you still using Postman/Insomnia as backend developer to validate your API while Visual Studio also does it?
VS has a perfect integration of .http file to check your API directly inside the IDE

➡️ Article => https://goatreview.com/visualize-api-responses-in-visual-studio-http-file/
Subscribe at the newsletter at the bottom of the article to get more articles like this 😎
Written by Pierre Belin : https://www.linkedin.com/in/pierre-belin/

Date requested
Start from today !

Channel requested
Newsletter and LinkedIn

Additional context

**Comment by ddskier** [comment]
This will run on LinkedIn on May 31

**Comment by pierrebelin** [comment]
Can be closed :)
