### ISSUE TITLE
[AMPLIFICATION] - DotBond: tool for dynamic API development

### ISSUE THREAD

**Issue by xseine** [dotnet-foundation/content#142]
**Please describe the content.**
I believe this is an extremely interesting project and by promoting, hopefully, people would get involved in development and/or discussion. The tool is very .NET oriented and inspired, and aims to build a really powerful protocol between .NET and TypeScript frontend that provides complete translation of models from C# to TS, client feature to make custom LINQ-like queries on Web API, etc.

**URL of the content**
https://github.com/xseine/dotbond-prototype

**Copy for the content**
GraphQL alternative with LINQ-like syntax in TypeScript (beta version)

**Date requested**
6/6/2023

**Channel requested**
Twitter, Newsletter (Members/Sponsors/Projects)

**Additional context**

**Comment by ddskier** [comment]
This is scheduled on social for 6/7/23 and will repeat at least once. Not closing because of newsletter request.
