### ISSUE TITLE
[AMPLIFICATION] - Avalonia UI on Inside .NET 

### ISSUE THREAD

**Issue by MikeCodesDotNET** [dotnet-foundation/content#148]
**Please describe the content.**
The .NET Foundation should amplify this content because Avalonia UI is the most popular community project within the foundation. This session covers an introduction to the technology and shows how it can help developers build .NET applications for every platform. 

**URL of the content**
https://www.youtube.com/watch?v=FWaHZYzpM5E&ab_channel=InsidedotNET

**Copy for the content**
Discover why Avalonia UI is fast becoming the most popular UI technology for .NET developers. 

**Date requested**
Anytime (ASAP).

**Channel requested**
All?

**Additional context**
Add any other context or screenshots about the request here.

**Comment by MikeCodesDotNET** [comment]
Any idea when we'll get confirmation of the amplification? Other requests from 2 days ago have already had responses.

**Comment by ddskier** [comment]
Apologies, I thought I'd responded. I'm a volunteer so sometimes I screw up. :) This is scheduled for June 14 on all social channels.  I'm leaving this issue open so that it can be included in next newsletter

**Comment by MikeCodesDotNET** [comment]
Thanks for the update. Looking forward to seeing the amplification.

**Comment by nicoleabuhakmeh** [comment]
Keeping this open for possible blog post on DNF website.

**Comment by khalidabuhakmeh** [comment]
While the content is good, the time to promote it may have passed (from a blog post perspective). Unassigning myself.
