### ISSUE TITLE
[AMPLIFICATION] - Composite Design Pattern: An agile story

### ISSUE THREAD

**Issue by praveenraghuvanshi** [dotnet-foundation/content#15]
**Please describe the content.**
Software design patterns are important for developing software as it helps simplify recurring problems in a strategic way. The article is about Composite design pattern with a new example from Agile domain giving a fresh perspective to the readers on the pattern. The .Net Foundation should amplify this content as it's about improving the quality of software and the examples used is in .Net(C#) language.

**URL of the content**
https://dev.to/praveenraghuvanshi/composite-design-pattern-an-agile-story-g6j

**Copy for the content**
"A fresh perspective on one of the Gang of Four design pattern, the Composite Pattern with an example from Agile domain and C# language"

**Date requested**
Anytime

**Channel requested**
Facebook, Twitter

Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Hi Praveen, I will promote this on Wed, Aug 5 on Facebook and Twitter. Do you have a Twitter handle that you want me to include?

**Comment by praveenraghuvanshi** [comment]
Yes, Its @praveenraghuvan. Thank you

**Comment by ddskier** [comment]
This is scheduled for Aug on FB and Twitter
