### ISSUE TITLE
[AMPLIFICATION] - Boost .NET Performance with Lazy Initialization

### ISSUE THREAD

**Issue by pierrebelin** [dotnet-foundation/content#150]
Please describe the content.
It's a blog post to discover how to use boost .NET Performance with Lazy Initialization. The article is quick and strait to the point!

URL of the content
https://goatreview.com/boost-dotnet-performance-lazy-initialization/

Copy for the content
🎓 Do you always fully load your class at initialization, when you could lazily load it as needed?
Microsoft lets you become as Lazy<T> as you should!

Article => https://goatreview.com/boost-dotnet-performance-lazy-initialization/
➡️ Subscribe at the newsletter at the bottom of the article to get more articles like this 😎
Written by @pierrebelin_ : https://www.linkedin.com/in/pierre-belin/

Date requested
Tomorrow after 5pm or later 

Channel requested
Newsletter and LinkedIn

Additional context

**Comment by ddskier** [comment]
Scheduled on social for 6/19. Not closing for newsletter inclusion

**Comment by pierrebelin** [comment]
Perfect, thanks you

**Comment by nicoleabuhakmeh** [comment]
Keeping this open for possible blog post on DNF website.

**Comment by nicoleabuhakmeh** [comment]
Added to July Newsletter
