### ISSUE TITLE
[AMPLIFICATION] - Dart Sass Host: .NET wrapper around the Dart Sass

### ISSUE THREAD

**Issue by Taritsyn** [dotnet-foundation/content#152]
Hello!

**Please describe the content.**
Dart Sass Host is an .NET wrapper around the Dart Sass with the ability to support a virtual file system. Unlike other .NET wrappers around the Dart Sass, this library is not based on the Dart runtime, but on the version for JavaScript.

**URL of the content**
https://github.com/Taritsyn/DartSassHost

**Copy for the content**
Dart Sass Host is an .NET wrapper around the Dart Sass with the ability to support a virtual file system.

**Date requested**
No fixed date

**Channel requested**
Twitter, Facebook

**Additional context**
Social media preview:
![Dart Sass Host Social media preview](https://repository-images.githubusercontent.com/309700656/ec080258-c175-4dce-bdd4-61d17dd06f9a)

**Comment by ddskier** [comment]
Scheduled for June 21 on FB, Twitter, LinkedIn

**Comment by Taritsyn** [comment]
Thanks!
