### ISSUE TITLE
[AMPLIFICATION] - Episode 54: Cleaning your Big Ball of Mud using CQS - with Matt Hunt

### ISSUE THREAD

**Issue by dracan** [dotnet-foundation/content#153]
**Please describe the content.**
This is for the next Unhandled Exception podcast episode, which is a podcast mostly about .NET and .NET projects/technologies.

**URL of the content**
https://unhandledexceptionpodcast.com/posts/0054-ballofmudcqrs/

**Copy for the content**
The next #UnhandledException podcast episode is now live!!! In it, host @dracan chatted with @doesdotnet about "big ball of mud" codebases, and how the CQS pattern can help! 🔥🎙 https://unhandledexceptionpodcast.com/posts/0054-ballofmudcqrs/ #dotnet #cqs

**Date requested**
When best suits you.

**Channel requested**
Facebook, Twitter, Newsletter (Members/Sponsors/Projects)

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
This is scheduled for June 25 and will post FB, Twitter, LinkedIn

**Comment by nicoleabuhakmeh** [comment]
Added to Newsletter.

**Comment by dracan** [comment]
> Added to Newsletter. 

Thank you! 😊🙏
