### ISSUE TITLE
[AMPLIFICATION] - Avalonia v11 Release

### ISSUE THREAD

**Issue by MikeCodesDotNET** [dotnet-foundation/content#156]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
Yes

**Please describe the content.**
A blog post outlining the new features of Avalonia v11.0

**URL of the content**
[Link to the article, blog, video, social post, presentation, etc. ](https://dev.to/avalonia/welcome-to-the-new-era-of-app-development-introducing-avalonia-v11-4na7)

**Copy for the content**
Learn about whats new in Avalonia 11.0. Build apps for Windows, macOS, Linux, iOS, Android and WebAssembly from a single project. 

@AvaloniaUI is one of the .NET Foundations most popular community projects, for good reason!

[Link to the article, blog, video, social post, presentation, etc. ](https://dev.to/avalonia/welcome-to-the-new-era-of-app-development-introducing-avalonia-v11-4na7)

**Date requested**
ASAP

**Channel requested**
All

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Scheduled for 7/6 on FB, LinkedIn, Twitter

**Comment by nicoleabuhakmeh** [comment]
Added to the July Newsletter.
