### ISSUE TITLE
[AMPLIFICATION] - ResX Resource Manager is now supporting Azure Open AI

### ISSUE THREAD

**Issue by tom-englert** [dotnet-foundation/content#158]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
Yes

**Please describe the content.**
ResX Resource Manager is now supporting Azure Open AI for translations. Check out version 1.76 to get high quality, context aware automated translations using Azure Open AI: https://bit.ly/44i2ZZu.
Special thanks to Joakim Riedel for the contribution of this feature.

**URL of the content**
https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Automatic-Translations.md#azure-open-ai

**Copy for the content**
ResX Resource Manager is now supporting Azure Open AI for translations. Check out version 1.76 to get high quality, context aware automated translations using Azure Open AI: https://bit.ly/44i2ZZu.
Special thanks to Joakim Riedel for the contribution of this feature.

**Date requested**
ASAP

**Channel requested**
All available

**Additional context**

**Comment by ddskier** [comment]
Scheduled for July 11 on FB, Twitter, LinkedIn
