### ISSUE TITLE
[CREATION] - ReSharper & Rider 2020.2 Release Party

### ISSUE THREAD

**Issue by matkoch** [dotnet-foundation/content#16]
Our team at JetBrains just released ReSharper and Rider 2020.2 and we would love to make a release party hosted by the .NET Foundation channel on YouTube.

**Target date**
It would be great if it was within the next two weeks at least.

**Channel requested**
It should be streamed via YouTube and hosted via StreamYard as we have a group of people covering different things. Assistance to switch between different views would be much appreciated, but generally, we already have experience with StreamYard.

**Additional context**
https://www.jetbrains.com/resharper/whatsnew/
https://www.jetbrains.com/rider/whatsnew/

Thanks in advance!

**Comment by BethMassi** [comment]
@clairernovotny can you direct this to the appropriate person on the Outreach committee that can help with the streaming?

**Comment by clairernovotny** [comment]
I don't think we know who that is yet, we'll discuss on Thursday's meeting.

**Comment by ddskier** [comment]
Keep us posted on this event so that we can share on social media.

**Comment by matkoch** [comment]
We're ready as soon as you are :)

**Comment by matkoch** [comment]
@clairernovotny any update on this?

**Comment by clairernovotny** [comment]
Tagging @jstrauss

**Comment by matkoch** [comment]
Any updates here? @jstrauss

**Comment by ddskier** [comment]
Do we only need to find a host on the .NET Foundation side? If so can @jamesmontemagno or Jeff Fritz do it? Would be good to get on the schedule.

**Comment by matkoch** [comment]
We need someone that invites everyone and either manages the screensharing or allows us to do that ourselves. “Hosting” in terms of moderation is not needed.

**Comment by matkoch** [comment]
Thanks once more!
