### ISSUE TITLE
[AMPLIFICATION] - Developer Ecosystem Survey 2023 by JetBrains

### ISSUE THREAD

**Issue by feberfantasere** [dotnet-foundation/content#162]
**Please describe the content.**
Promotion of the annual Developer Ecosystem Survey 2023 led by JetBrains. Every year we run this survey with the aim to explore the current state of the software development industry, and we want to reach a broader .NET community to get more reliable data. 

**URL of the content**
https://surveys.jetbrains.com/s3/ti-developer-ecosystem-survey-2023

**Copy for the content**
Take part in the Developer Ecosystem Survey by JetBrains! Share your programming experience and get a chance to win one of the amazing prizes. #DevEcosystem23

**Date requested**
The survey is currently open, so it would be great to amplify it as soon as you have the capacity.

**Channel requested**
Facebook, Twitter, Newsletter

**Comment by nicoleabuhakmeh** [comment]
Hi Alexandra - We can schedule a tweet for this, but we reserve survey promotion to the Newsletter for our Corporate Sponsors.

**Comment by ddskier** [comment]
This will post to all social accounts on 7/21
