### ISSUE TITLE
[AMPLIFICATION] - VMware Newsletter

### ISSUE THREAD

**Issue by nicoleabuhakmeh** [dotnet-foundation/content#163]
**Are you a .NET Foundation Member**
Yes - Sponsor (VMware)

**Please describe the content.**
Promotion of the first newsletter- Hooked on .NET 

**URL of the content**
[Newsletter ](https://tanzu.vmware.com/developer/languages/dotnet/newsletter/first/)

**Copy for the content**
Hooked on .NET - The inaugural edition
The inaugural edition includes suggestions for the latest blogs to read, podcasts to listen to and videos to watch.

**Date requested**
This week, month for Newsletter

**Channel requested**
Facebook, Twitter, LinkedIn, Newsletter

**Additional context**
Submitted via email by Layla Porter

**Comment by ddskier** [comment]
Scheduled for July 24 on all social

**Comment by nicoleabuhakmeh** [comment]
Loaded into the July Newsletter
