### ISSUE TITLE
[AMPLIFICATION] - Elevate Your .NET Testing Strategy #2: InMemoryDatabase

### ISSUE THREAD

**Issue by pierrebelin** [dotnet-foundation/content#164]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
Yes

**Please describe the content.**
It's a blog post to discover how use InMemoryDatabase for testing endpoints. The article is quick and strait to the point!

**URL of the content**
https://goatreview.com/dotnet-testing-inmemorydatabase-for-component-tests/

**Copy for the content**
🎓You want to test quickly your API endpoints with a real database ? Use InMemoryDatabase !
The InMemoryDatabase allows to real repository and unit of work without mocks for component tests. It perfectly combine with WebApplicationFactory. Check this out!

Article => https://goatreview.com/dotnet-testing-inmemorydatabase-for-component-tests/
➡️ Subscribe at the newsletter at the bottom of the article to get more articles like this 😎
Written by @pierrebelin_ : https://www.linkedin.com/in/pierre-belin/

**Date requested**
It will be published today at 5pm (UTC+2), so whenever you like

**Channel requested**
Newsletter, LinkedIn and Twitter

**Comment by ddskier** [comment]
Scheduled for Aug 1 on all social media

**Comment by nicoleabuhakmeh** [comment]
Added to the July Newsletter
