### ISSUE TITLE
[AMPLIFICATION] - Taking Entity Framework Core data seeding to the next level with Bogus

### ISSUE THREAD

**Issue by sander1095** [dotnet-foundation/content#165]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
This blog post describes how to use the awesome community project [Bogus](https://github.com/bchavez/bogus) to generate realistic fake data together with [Entity Framework Core](https://github.com/dotnet/efcore) to set up your testing data in seconds! This content is valuable to the .NET open-source community for efficient testing and database setup.

**URL of the content**
https://stenbrinke.nl/blog/taking-ef-core-data-seeding-to-the-next-level-with-bogus/

**Copy for the content**
Using Bogus to generate realistic fake data together with Entity Framework Core to set up your testing data in seconds!

**Date requested**
 No specific date.

**Channel requested**
 Any possible channel.

**Additional context**
None.

**Comment by ddskier** [comment]
Scheduled for 8/2 on all .NET Foundation social channels
