### ISSUE TITLE
[AMPLIFICATION] - Altairis Sqlite Backup

### ISSUE THREAD

**Issue by ridercz** [dotnet-foundation/content#166]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
Altairis Sqlite Backup helps to automate backup of Sqlite databases in ASP.NET Core Web applications. Sqlite is good database for many web scenarios, but lacks the maintenance options of big DBs like SQL Server. This library can do automated backups, local, remote or into Azure Storage Account.

**URL of the content**
https://github.com/ridercz/Altairis.SqliteBackup

**Copy for the content**
Altairis Sqlite Backup helps to automate backup of Sqlite databases in ASP.NET Core Web applications. Sqlite is good database for many web scenarios, but lacks the maintenance options of big DBs like SQL Server. This library can do automated backups, local, remote or into Azure Storage Account.

**Date requested**
Any.

**Channel requested**
Any.

**Comment by ddskier** [comment]
Scheduled for 8/3 on all .NET Foundation social handles
