### ISSUE TITLE
[AMPLIFICATION] - Rosy Crow

### ISSUE THREAD

**Issue by aschuhardt** [dotnet-foundation/content#168]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
Rosy Crow is an Android browser for the plaintext, privacy-first Gemini protocol. The .NET Foundation should amplify Rosy Crow because the app demonstrates MAUI's potential for building highly-customized, feature-rich apps that target niche audiences. The app is totally free and open-sourced.

**URL of the content**
https://rosy-crow.app
https://github.com/aschuhardt/rosy-crow

**Copy for the content**
Rosy Crow is an Android browser for the plaintext, privacy-first Gemini protocol made with .NET 7 and MAUI.

**Date requested**
08/15/2023

**Channel requested**
Twitter, Facebook, LinkedIn, Newsletter

**Additional context**
Background on the Gemini protocol project: https://gemini.circumlunar.space/

![253795465-c42774e3-6b12-4b7b-9fb5-33132e37007d](https://github.com/dotnet-foundation/content/assets/13511943/89c0a3b1-1e68-4e2e-beb3-cdb74605eb1d)

**Comment by ddskier** [comment]
Scheduled to post on all social channels on Aug 8
