### ISSUE TITLE
[AMPLIFICATION] - Online course: Fundamentals of Building .NET Applications on AWS

### ISSUE THREAD

**Issue by julielerman** [dotnet-foundation/content#17]
This is a 2.5 hour course on Pluralsight that introduces .NET developers to AWS and to building an ASP.NET API  in Visual Studio using the AWS Toolkit for Visual Studio, an extension that helps you tap into a slew of services on AWS. Throughout the course, I demonstrate connecting the application to a SQL Server database (hosted on AWS Relational Database Service aka RDS), publishing the app into a virtual machine (EC2 instance), publishing the app as auto-managed Docker containers and then publishing the app behind a Lambda function. It's a great intro for .NET devs who are either just curious about AWS or who have been tasked to learn about it.

Pluralsight does require a paid subscription to view courses, however there is a free 10-day trial always available and authors have access to (a limited number of) 30-day trial passes they can distribute as needed.

**URL of the content**
Shortened: https://bit.ly/PS_dotnetaws
Full: https://app.pluralsight.com/library/courses/fundamentals-building-dot-net-applications-aws/table-of-contents 

**Copy for the content**
You can take the easy way and RT this tweet: https://twitter.com/julielerman/status/1292478319867367424
it's text says:
Yo, @dotnet devs! Curious about @awscloud, like I was? Or need to learn it for work? My newest @pluralsight
 course is out! Fundamentals of Building .NET Applications on AWS http://bit.ly/PS_dotnetaws Learn about creating/deploying #sqlserver, #aspnetcore, #docker, #serverless on AWS

**Date requested**
As soon as you can/want :)

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
There are also two articles in Code magazine related to this if you are interested. Let me know.

**Comment by ddskier** [comment]
Looks like this already got retweeted on Twitter and I posted to FB. I'll repost on both channels next week. And I'll checkout the two Code magazine articles and post them as well.

**Comment by ddskier** [comment]
Btw, here is URL to FB post: https://www.facebook.com/dotnetfoundation/posts/628655101122907

**Comment by julielerman** [comment]
Thanks!! Now if only we could get the @dotnet alias to RT haha. But that's really Microsoft dotnet not just dotnet. :)

**Comment by julielerman** [comment]
code mags is here:
https://www.codemag.com/Article/2008041/Transform-Your-ASP.NET-Core-API-into-AWS-Lambda-Functions
and
https://www.codemag.com/Article/2005041/Discovering-AWS-for-.NET-Developers
Thanks DeeDee :)
