### ISSUE TITLE
[AMPLIFICATION] - Space Apps Manchester Hackathon (Part of NASA Space Apps Challenge)

### ISSUE THREAD

**Issue by leeenglestone** [dotnet-foundation/content#170]
**Are you a .NET Foundation Member**
Yes (And corporate member - Avanade)

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
Space Apps Manchester is a global, virtual hackathon that encourages the tech community to tackle earth and space related challenges as part of the NASA Space Apps Challenge in October. This years theme is Open Science.

**URL of the content**
https://www.SpaceAppsManchester.com

**Copy for the content**
Participate in a global virtual hackathon that is out of this world!
Registration is now open for the Space Apps Manchester global virtual hackathon (part of the NASA Space Apps Challenge) on 7th & 8th October 2023. If you are interested in coding or space, check it out! See SpaceAppsManchester.com for more details.

**Date requested**
No particular date. But posts in August and September would be appreciated

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - for Members/Sponsors/Projects only

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Scheduled for FB, Twitter, LinkedIn on Aug 10. Will repeat Aug 21, Sept 13, Sept 27

**Comment by nicoleabuhakmeh** [comment]
Added to August Newsletter

**Comment by leeenglestone** [comment]
Hi - Can I provide an updated image please? The previous one is missing 3 sponsors. Thanks

**Comment by ddskier** [comment]
yes I can update social

**Comment by leeenglestone** [comment]
Can you use the image in this tweet please? Thanks

https://x.com/LeeEnglestone/status/1705290160886153236?s=20

**Comment by ddskier** [comment]
Sept 27 social post has been updated with new image
