### ISSUE TITLE
[AMPLIFICATION] - Domain Events vs Integration Events

### ISSUE THREAD

**Issue by EngincanV** [dotnet-foundation/content#171]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**

I have created a new article that explains what domain events and integration events are, how they differ, and how to decide when to use each one.

**URL of the content**
https://engincanv.github.io/ddd/domain-events/integration-events/event-driven-architecture/2023/08/05/domain-events-vs-integration-events.html

**Copy for the content**

Do you know what domain events and integration events are, how they differ, or how they can help you to build a loosely coupled application? Read the article below to find out 👇

https://engincanv.github.io/ddd/domain-events/integration-events/event-driven-architecture/2023/08/05/domain-events-vs-integration-events.html

**Date requested**

Anytime on weekdays is okay for me.

**Channel requested**

Twitter/X, LinkedIn

**Additional context**

None.

**Comment by ddskier** [comment]
This is scheduled for Aug 14 on social channels
