### ISSUE TITLE
[AMPLIFICATION] - Elevate Your .NET Testing Strategy #3: Fixtures separation

### ISSUE THREAD

**Issue by pierrebelin** [dotnet-foundation/content#172]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
It's a blog post to discover how separate fixtures from tests to improve readability. The article is quick and strait to the point!

**URL of the content**
https://goatreview.com/dotnet-testing-fixtures-separation/

**Copy for the content**
🐐 🐐 Want to improve the readability of your tests? Separate your fixtures!
Instead of having everything in your test content, separate the data from the behavior to simplify it. Check it out!

Article => https://goatreview.com/dotnet-testing-fixtures-separation/
➡️ Subscribe at the newsletter at the bottom of the article to get more articles like this 😎
Written by @pierrebelin_ : https://www.linkedin.com/in/pierre-belin/

**Date requested**
As you prefer

**Channel requested**
X/Twitter
LinkedIn
Newsletter - for Members/Sponsors/Projects only

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
This is scheduled for Aug 15 on all social channels
