### ISSUE TITLE
[AMPLIFICATION] - Announcing GitHub sponsorship matching For Uno Platform contributors and employees  

### ISSUE THREAD

**Issue by mtmattei** [dotnet-foundation/content#173]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
Uno Platform announces an initiative in support of open-source contributors and employees. Recognizing the challenges faced by maintainers within the .NET ecosystem, the program offers sponsorship matching to Uno Platform's GitHub contributors and staff. This effort aims to address the underfunding of open-source work. The program encourages individual developers and employees to contribute, fostering financial sustainability. The initiative reflects Uno Platform's commitment to fostering long-term sustainability in the open-source community.

**URL of the content**
https://platform.uno/blog/github-sponsorship-matching-for-uno-platform-contributors-and-employees/

**Copy for the content**
Exciting News from Uno Platform! Introducing a new initiative to support open-source contributors & employees. Our sponsorship matching program empowers the #opensource community, fostering sustainability one contribution at a time. Learn more: 

**Date requested**
08/21/23

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - for Members/Sponsors/Projects only

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Scheduled for 8/21 on twitter, linkedin, fb
