### ISSUE TITLE
[AMPLIFICATION] - MassTransit #2: In-memory Mediator pattern basics

### ISSUE THREAD

**Issue by pierrebelin** [dotnet-foundation/content#177]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
It's a blog post to discover how to use the in memory mediator pattern with the library MassTransit. The article is quick and strait to the point!

**URL of the content**
https://goatreview.com/masstransit-inmemory-mediator-basics/

**Copy for the content**
🐐 🚀 If you're diving into the world of messaging in your .NET projects, you won't want to miss this deep dive into the in-memory pattern using MassTransit. 📨💬

🔗 Article: https://goatreview.com/masstransit-inmemory-mediator-basics/
Don't miss out on the chance to level up your messaging game. Subscribe to our newsletter at the end of the article for more insightful content. 😎

Connect with Pierre 👉 https://www.linkedin.com/in/pierre-belin/

**Date requested**
As you prefer, article already online

**Channel requested**
LinkedIn
Newsletter - for Members/Sponsors/Projects only

**Additional context**

**Comment by ddskier** [comment]
Did I miss this? Apologies.

**Comment by pierrebelin** [comment]
No worries at all, since MassTransit is not part of the .NETFoundation projects, I thought you didn't want to put it forward!
