### ISSUE TITLE
[AMPLIFICATION] - JetBrains .NET Day Online 2023

### ISSUE THREAD

**Issue by maartenba** [dotnet-foundation/content#179]
**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
Promotion of the JetBrains .NET Day Online event we are hosting for the .NET community.

**URL of the content**
https://jb.gg/6owrsf

**Copy for the content**

Attached is an image if you wish to include one - ![Twitter.png](https://github.com/dotnet-foundation/content/assets/485230/8abe2978-a669-4221-8a99-a8d83fc554f6).

Tweet text:

```
Join our free virtual event, JetBrains .NET Day Online '23!

📅 September 26
🎙️ Topics: #csharp, #fsharp, #Blazor, Avalonia, EF Core, xUnit, and more!

Register: https://jb.gg/6owrsf

Supported by @dotnetfdn #dotnet #JBDotNetDays
```

**Date requested**
September 5, 2023, and ideally another one around September 14th.

**Channel requested**
Facebook, Twitter, LinkedIn, and if possible - newsletter

Thank you folks! 🙏

**Comment by ddskier** [comment]
This is scheduled for Sept 5 and Sept 14

**Comment by nicoleabuhakmeh** [comment]
Hi Maarten!

Added to the August Newsletter.
