### ISSUE TITLE
[AMPLIFICATION] - Steeltoe 3.0

### ISSUE THREAD

**Issue by jkonicki** [dotnet-foundation/content#18]
**Please describe the content.**
The .NET Foundation should amplify this content because it provides news about a .NET Foundation project's major release: *Steeltoe 3.0*

**URL of the content**
Blog link https://steeltoe.io/blog/steeltoe-3-0-packs-a-mighty-punch-with-many-new-features

Tweet for retweeting: https://twitter.com/SteeltoeOSS/status/1298007491616350213

**Copy for the content**
Twitter:
Can you retweet this with a comment `Are you building cloud-native \#dotnet applications? You should check out all the new features in the latest release of Steeltoe 3.0! ` 

Original tweet: https://twitter.com/SteeltoeOSS/status/1298007491616350213

Facebook: 
`Are you building cloud-native \#dotnet applications? You should check out all the new features in the latest release of Steeltoe 3.0! `

Use the link to blog: https://steeltoe.io/blog/steeltoe-3-0-packs-a-mighty-punch-with-many-new-features

**Date requested**
It was released on 8/24, so anytime this week would be great.

**Channel requested**
Twitter, Facebook

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Scheduled for Aug 26 on Twitter and FB. Also retweeted your tweet.
