### ISSUE TITLE
[AMPLIFICATION] - Everything you need to know about configuration and secret management in .NET

### ISSUE THREAD

**Issue by sander1095** [dotnet-foundation/content#180]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
This blog post describes everything a .NET developer needs to know about configuration and secret management, like `IConfiguration`, the Options Pattern, User secrets and several Azure Services. It's quite a long blog post; I see it as a handy pocketguide that a developer can always fall back on (or send to others) when they want to learn more the aforementioned topics.

**URL of the content**
https://stenbrinke.nl/blog/configuration-and-secret-management-in-dotnet/

**Copy for the content**
A handy pocketguide that covers everything a .NET developers needs to know about configuration and secret management, both locally and in the cloud!

**Date requested**
 No specific date.

**Channel requested**
 Any possible channel.

**Additional context**
None.

**Comment by ddskier** [comment]
This will post to LinkedIn, FB, Twitter on Sept 12
