### ISSUE TITLE
[AMPLIFICATION] - .NET Conf promotion

### ISSUE THREAD

**Issue by ddskier** [dotnet-foundation/content#182]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
Promote .NET Conf 2023 which is the largest virtual .NET conference and provides tons of high quality technical .NET content

**URL of the content**
https://www.dotnetconf.net/ 

**Copy for the content**
#dotnetconf is back for 2023!

3 days of free .NET #developer content streaming live around the globe. Save the date! 
https://www.dotnetconf.net/ #dotnet 

**Date requested**
Any dates that are open on social. Repeat until Nov 14 periodically
For newsletter, can we get mentions in Oct and Nov?

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter

**Additional context**
Add any other context or screenshots about the request here.
![dotnetconf visual](https://github.com/dotnet-foundation/content/assets/13860779/de1091e2-a456-4866-b4d5-6dd43d1a94f9)

**Comment by nicoleabuhakmeh** [comment]
Added to September and will keep open for October inclusion.
