### ISSUE TITLE
[AMPLIFICATION] - CMS for .NET Talk

### ISSUE THREAD

**Issue by bigebesikci** [dotnet-foundation/content#183]
**Are you a .NET Foundation Member**
Yes

**Please describe the content.**
Hi there, we are organizing a new episode of ABP Community Talks, which you might be familiar with from before. In this episode, we will talk about how to create a content management system with .NET using ABP Framework's CMS Kit.

It will take place on Thursday the 28th of September, 2023 at 17:00 UTC.

It would be great to include it in your newsletter as well, if you have a newsletter on the way before September 28, 2023.

Thank you in advance 🙏

**URL of the content**
Registration URL: https://kommunity.com/volosoft/events/abp-community-talks-20237-build-your-content-management-system-with-net-8a44b48a

**Copy for the content**

1 week before (September 21, 2023)
` 📣 Get ready! In just 1 week, join for a special #ABPCommunityTalks on Sep 28 at 17:00 UTC: "Build Your Own CMS with .NET". Plus, awesome giveaways await: JetBrains dotUltimate & ABP licenses! 🎁
Register now: https://kommunity.com/volosoft/events/abp-community-talks-20237-build-your-content-management-system-with-net-8a44b48a`

3 days before (September 25, 2023)
`⏳ 3 days left to the .NET CMS Kit Community Talk! Not only will you gain insights into the @ABPFramework, but you might also grab a JetBrains or ABP license! 🔗 https://kommunity.com/volosoft/events/abp-community-talks-20237-build-your-content-management-system-with-net-8a44b48a `

The day before (September 27, 2023)
` 🚀  Tomorrow at 17:00 UTC! "Build Your Own CMS with .NET" is your chance to learn from the experts at @ABPFramework is almost here. Insights, demos, and giveaways awaiting! 🔗 https://kommunity.com/volosoft/events/abp-community-talks-20237-build-your-content-management-system-with-net-8a44b48a `

**Date requested**
September 21, September 25, and September 27

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - for Members/Sponsors/Projects only

**Additional context**
* Horizontal - YouTube, Newsletter, etc. (1920x1080):

![abp-community-talk-1](https://github.com/dotnet-foundation/content/assets/78538870/619fcd1c-68a7-4139-b4c2-44acd8b6bf3d)

* Vertical - Instagram Story size (1080x1920):

![abp-community-talk-2](https://github.com/dotnet-foundation/content/assets/78538870/5f5638bd-2ddf-4ee6-a711-5e42a6fa3118)

* Instagram, Facebook (1080x1080):

![abp-community-talk-3](https://github.com/dotnet-foundation/content/assets/78538870/411ac238-5b66-4301-94c7-95e3e767fef2)

* Twitter, LinkedIn post size (1200x628):

![abp-community-talk-4](https://github.com/dotnet-foundation/content/assets/78538870/39ca3908-e1bb-41e7-9a97-4a30311885e6)

**Comment by ddskier** [comment]
This is scheduled for all social channels on the 3 dates requested
