### ISSUE TITLE
[AMPLIFICATION] - Avalonia Visual Studio Code Release

### ISSUE THREAD

**Issue by MikeCodesDotNET** [dotnet-foundation/content#185]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
Yes

**Please describe the content.**
We recently released an extension for [Visual Studio Code](https://github.com/AvaloniaUI/AvaloniaVSCode) and would love to promote this to the broader .NET community via social media. The extension is OSS (MIT Licensed) and already on the Visual Studio marketplace..  

**URL of the content**
https://github.com/AvaloniaUI/AvaloniaVSCode

**Copy for the content**
Exciting news for all .NET Developers! 

@AvaloniaUI now offers extensions for all your favourite IDEs, including VSCode, complete with XAML IntelliSense and a live XAML previewer. 

Try the extension today: https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.vscode-avalonia

**Date requested**
25th or 27th of Sept. 

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - for Members/Sponsors/Projects only

**Additional context**
![VSCode Screenshot](https://github.com/dotnet-foundation/content/assets/552074/7a948287-2262-4e4c-a49b-69eb11cc721f)

**Comment by ddskier** [comment]
Scheduled for all social channels on Sept 25 and repeating on Oct 3

**Comment by nicoleabuhakmeh** [comment]
Added to September Newsletter

**Comment by MikeCodesDotNET** [comment]
Thanks! 🙏
