### ISSUE TITLE
[AMPLIFICATION] - Roslyn Source Code Generators

### ISSUE THREAD

**Issue by ignatandrei** [dotnet-foundation/content#186]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
This is a comprehensive and opinionated list of Roslyn Source Code Generators that can help you with any CSharp project.

**URL of the content**
[List of Roslyn Code Generators](https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG)

**Copy for the content**
With Roslyn Code Generators you write code that write code. Read and after that use the RSCG for fun and easy of programming.
Also, if you have one, please submit an issue at https://github.com/ignatandrei/RSCG_Examples/issues

**Date requested**
Any date

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - for Members/Sponsors/Projects only

**Comment by ddskier** [comment]
This is scheduled on all social platforms for Oct 4
