### ISSUE TITLE
[AMPLIFICATION] - Migration from .NET Core 2.2 to .NET Core 3.1: nopCommerce experience

### ISSUE THREAD

**Issue by ivkadp** [dotnet-foundation/content#19]
**Content description**
This article, written by the nopCommerce team, describes the process of migrating free and open-source ASP.NET eCommerce platform nopCommerce from ASP.NET Core 2.2 to ASP.NET Core 3.1. The article will be useful for everyone who wants to understand the advantages and specificities of migration.

**URL of the content**
https://www.nopcommerce.com/migration-from-net-core-22-to-net-core-31-nopcommerce-experience

**Copy for the content**
This article describes the process of migration from .NET Core 2.2 to .NET Core 3.1 on the example of open-source and free eCommerce platform nopCommerce. Learn the advantages and specificities of migration: https://www.nopcommerce.com/migration-from-net-core-22-to-net-core-31-nopcommerce-experience

**Date requested**
27.08.2020

**Channel requested**
Facebook, Twitter

**Additional context**
![Migration from  NET Core 2 2 to  NET Core 3 1_ nopCommerce experience (1)](https://user-images.githubusercontent.com/50017147/91434931-33b88a00-e86e-11ea-8d20-b3a28a9feb12.png)

**Comment by ddskier** [comment]
Published on FB & Twitter. 

https://twitter.com/dotnetfdn/status/1299027850851430402
https://www.facebook.com/dotnetfoundation/photos/a.294760944512326/633564787298605/
