### ISSUE TITLE
[AMPLIFICATION] - Stride game engine

### ISSUE THREAD

**Issue by tebjan** [dotnet-foundation/content#190]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
Yes

**Please describe the content.**
I would like to submit an amplification request for the Stride C# game engine. I am a contributor to the project and involved in the community since the beginning. Currently, I am trying to help Stride to gain more exposure.

Stride, an open-source C# game engine (written in C#!), has gained increased significance in the wake of recent events in the world of game development, notably with Unity. I propose amplifying Stride's content through the .NET Foundation's social channels to raise awareness and promote the engine's capabilities.

https://www.stride3d.net
https://github.com/stride3d/stride

**URL of the content**
Many things from our Twitter account and blog could be relevant.

**Notable blog posts:**
https://www.stride3d.net/blog/embracing-open-source-stride-as-an-alternative-to-unity/
https://www.stride3d.net/blog/game-development-in-stride/

**Technical Blog posts:**
https://www.stride3d.net/blog/closer-look-private-members/

**Tutorials:**
https://doc.stride3d.net/latest/en/tutorials/

**Notable tweets:**

Types of scripts and using async/await in Stride:
https://twitter.com/stridedotnet/status/1715142284281323581

No. 3 spot in FOSS game dev popularity:
https://twitter.com/stridedotnet/status/1713912406806598115

Stride uses 'real' C# compared to other game engines:
https://twitter.com/stridedotnet/status/1712151882553041332

Stride can be used with F# and VisualBasic:
https://twitter.com/stridedotnet/status/1710364455282872718

Stride can be integrated in other .NET projects, such as vvvv:
https://twitter.com/stridedotnet/status/1709708841863008746

"Awesome Stride", a huge link resource for Stride:
https://twitter.com/stridedotnet/status/1708525831864139906

Video about switching from Unity to Stride:
https://twitter.com/stridedotnet/status/1707072675783246167

Stride tech demo published:
https://twitter.com/stridedotnet/status/1706751298224165310

Using C# hot-reload with Stride:
https://twitter.com/Loprez8/status/1703940985942884689

**Copy for the content**
Our Twitter entries can be used.

https://twitter.com/stridedotnet

**Date requested**
Earliest convenience.

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter

**Additional context**
I personally think Stride is a powerful tool that deserves to be showcased more. While recent industry developments have highlighted its relevance, it remains surprisingly overlooked within the C# and .NET community.

**Comment by ddskier** [comment]
Thanks for the info on Stride. I'm promoting a post on Oct 26. I will also promote when I have gaps in the schedule. Thank you!

**Comment by nicoleabuhakmeh** [comment]
Added as the Project Spotlight for the October Newsletter.

**Comment by tebjan** [comment]
Thanks a lot for the tweet yesterday!

We just published a new blog post, it is quite technical. Does the .NET foundation twitter account also repost tweets?
https://twitter.com/stridedotnet/status/1717876803602145769

**Comment by ddskier** [comment]
I reposted your tweet

**Comment by tebjan** [comment]
Thanks a lot for the Spotlight in the newsletter! 
We'll probably open a new amplification request when our 4.2 release with .NET 8 is out.

Regards from the Stride community!
