### ISSUE TITLE
GitHub Copilot Access Request

### ISSUE THREAD

**Issue by saitorhan** [dotnet-foundation/content#191]
Hello.
First of all, I am extremely pleased to be a member of this valuable community.
I have been developing software with .Net and providing local training since 2009. I made a request for the use of Copilot. I wonder if this valuable community of .Net has access to GitHub Copilot?
Thank you for everything.

@BethMassi @jglozano @rprouse @devlead

**Comment by nicoleabuhakmeh** [comment]
Removed the tag of individuals no longer on the board. Added Board Members to discuss.

**Comment by saitorhan** [comment]
Hello dear admin friends,
As a member of this valuable community, I am waiting for your response regarding my request about using Copilot. If we do not have the right to use it for free, I will make the purchase. I am looking forward to your valuable feedback on this matter.
@richlander

**Comment by SeanKilleen** [comment]
@saitorhan I am not a leader of the .NET Foundation but to my knowledge there are no complimentary subscriptions offered as part of membership and your best route is going to be to purchase a product like normal.

**Comment by saitorhan** [comment]
Thanks so much.
