### ISSUE TITLE
[AMPLIFICATION] - Integration tests with Docker.DotNet

### ISSUE THREAD

**Issue by pierrebelin** [dotnet-foundation/content#195]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
It's a blog post to discover how to create integration tests using Docker.DotNet library. The article is quick and strait to the point!

**URL of the content**
https://goatreview.com/dotnet-testing-integration-tests-docker-dotnet/

**Copy for the content**
🐐 Ready to master the intricacies of DockerDotNet? Dive deep into the world of integration tests with this remarkable library! 🐋🚀

If you're a developer exploring the potential of DockerDotNet for your .NET projects, you won't want to miss this insightful guide. 📦💻 Learn how to harness the power of containerization and streamline your integration testing process effortlessly.

🔗 Article: https://goatreview.com/bi-directional-grpc-stream-cache-server-csharp/

Subscribe to our newsletter for more insightful content 👉 https://goatreview.com/subscription
Connect with Pierre Belin 👉 https://www.linkedin.com/in/pierre-belin/

**Date requested**
As you prefer, article already online

**Channel requested**
LinkedIn

**Comment by ddskier** [comment]
Scheduled for Nov 9 on LinkedIn
