### ISSUE TITLE
[AMPLIFICATION] - Future-proof Your .NET Apps With Foundation Model Choice and Amazon Bedrock

### ISSUE THREAD

**Issue by fbouteruche** [dotnet-foundation/content#197]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
Amazon Bedrock enables .NET developers to easily access leading foundation models like Claude, Jurassic, Stable Diffusion and others through a single API using the [AWSSDK.BedrockRuntime Nuget package](https://www.nuget.org/packages/AWSSDK.BedrockRuntime). It brings the choice of foundation models to the .NET community.

The post introduces Amazon Bedrock, walks through setting up the .NET SDK, and introduces a sample app to showcase using Amazon Bedrock in a .NET app.

**URL of the content**
https://community.aws/posts/future-proof-dotnet-app-with-amazon-bedrock

**Copy for the content**

Looking for adding generative AI capabilities to your .NET app? Get easy access to leading foundation models like Claude, Jurassic or Stable Diffusion with Amazon Bedrock! Read this post to learn how to get started.

**Date requested**
When possible

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - for Members/Sponsors/Projects only

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
This is scheduled for Tues, Nov 14 on all social channels

**Comment by fbouteruche** [comment]
Thank you.
