### ISSUE TITLE
[AMPLIFICATION] - .NET 8.0 & ABP 8.0 Event

### ISSUE THREAD

**Issue by bigebesikci** [dotnet-foundation/content#199]
**Are you a .NET Foundation Member**
Yes

**Please describe the content.**
We have a new episode of ABP Community Talks in which we will cover What is coming with .NET 8.0 and ABP 8.0 versions with open source ABP Framework core development team. We think it would be very beneficial to us and to your audience if they would like to register and attend. I'd like to ask you for 2 times announcement with both content and dates below. Thank you in advance!

**URL of the content**
https://kommunity.com/volosoft/events/abp-community-talks-20238-whats-coming-with-net-80-abp-v80-a196d644

**Copy for the content**
Event alert📢
In this episode, open source ABP Framework's core development team will talk about what is coming with the .NET 8.0 and ABP 8.0.
ABP Community Talks 2023.8 will take place on November 23, 2023 at 17:00 UTC.
Register NOW 👉 https://kommunity.com/volosoft/events/abp-community-talks-20238-whats-coming-with-net-80-abp-v80-a196d644

**Date requested**
- on November 16, 2023

**Copy for the content**
ABP Community Talks 2023.8: What's coming with .NET 8.0 and ABP 8.0 is TOMORROW at 17:00 UTC!
Be sure to catch the live event to watch and have a chance to join their raffles.
Register here 👉 https://kommunity.com/volosoft/events/abp-community-talks-20238-whats-coming-with-net-80-abp-v80-a196d644

**Date requested**
- on November 22, 2023

Here are the visuals in different sizes:

Instagram / Facebook Post(1080x1080)
![intagram-post](https://github.com/dotnet-foundation/content/assets/78538870/ab93ed16-fc34-4ee9-9cf7-b50bf9a3567e)

Instagram / Facebook Story (1080x1920)
![instagram-story](https://github.com/dotnet-foundation/content/assets/78538870/23882e42-dbd1-4350-95b2-f76f61a930ed)

X/Twitter 
![twitter-linkedin](https://github.com/dotnet-foundation/content/assets/78538870/5bb89c0d-d0a0-4edb-9744-b319376cc118)
/ LinkedIn (1200x628)

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - for Members/Sponsors/Projects only

**Comment by ddskier** [comment]
Scheduled for Nov 16 and 22 on all social channels

**Comment by bigebesikci** [comment]
Hi there,

We have a change in the speakers and in the designs, can you please update the scheduled post accordingly?
I apologize for the last minute change but it's cruicial for us.

Thank you! 🙏


Here is the updated version:

**URL of the content**
https://kommunity.com/volosoft/events/abp-community-talks-20238-whats-coming-with-net-80-abp-v80-a196d644

**Copy for the content**
Event alert📢
In this episode, open source ABP Framework's core team and @stevensanderson will talk about what is coming with the .NET 8.0 and ABP 8.0.
ABP Community Talks 2023.8 will take place on November 23, 2023 at 17:00 UTC.
Register NOW 👉 https://kommunity.com/volosoft/events/abp-community-talks-20238-whats-coming-with-net-80-abp-v80-a196d644

**Date requested**
on November 16, 2023


**Copy for the content**
ABP Community Talks 2023.8: What's coming with .NET 8.0 and ABP 8.0 is TOMORROW at 17:00 UTC!
And @stevensanderson is their guest speaker in this episode! Be sure to catch the live event to watch and have a chance to join their raffles.
Register here 👉 https://kommunity.com/volosoft/events/abp-community-talks-20238-whats-coming-with-net-80-abp-v80-a196d644

**Date requested**
on November 22, 2023


Here are the visuals in different sizes:

Instagram / Facebook Post(1080x1080)
![intagram-post](https://github.com/dotnet-foundation/content/assets/78538870/752d9a0a-d3ce-4794-bad6-4081c785313e)


Instagram / Facebook Story (1080x1920)
![instagram-story](https://github.com/dotnet-foundation/content/assets/78538870/c00f0fad-8efc-4b9a-a6ea-c19102501536)


X/Twitter/ LinkedIn (1200x628)
![twitter-linkedin](https://github.com/dotnet-foundation/content/assets/78538870/0b894ae6-439c-4dc0-b3ea-d19bd4de8f6c)



Channel requested
X/Twitter
LinkedIn
Facebook
Newsletter - for Members/Sponsors/Projects only

**Comment by ddskier** [comment]
I updated the posts.

**Comment by bigebesikci** [comment]
Thank you so much! I appreciate it 🙏
