### ISSUE TITLE
MLOps.NET

### ISSUE THREAD

**Issue by aslotte** [dotnet-foundation/content#20]
**Please describe the content.**
MLOps.NET is an open-source data science tool aimed to make the process of managing, monitoring and deploying your ML.NET machine learning model to production easier.  

**URL of the content**
https://github.com/aslotte/MLOps.NET

**Copy for the content**
Are you building machine learning models with @MLdotnet? Then you should absolutely take a moment to check-out #MLOpsNET that can help you manage, automate and track the model's path from training to deployment in production https://github.com/aslotte/MLOps.NET

**Date requested**
As soon as feasible

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Posted to Twitter and FB
https://twitter.com/dotnetfdn/status/1300811628640907268
https://www.facebook.com/dotnetfoundation/posts/637042660284151
