### ISSUE TITLE
[AMPLIFICATION] - Cake 3.20 released

### ISSUE THREAD

**Issue by devlead** [dotnet-foundation/content#200]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
Yes

**Please describe the content.**
The .NET Foundation member project released a new version.

**URL of the content**
https://cakebuild.net/blog/2023/11/cake-v3.2.0-released

**Copy for the content**

> Cake v3.2.0 released 🚀 🍰
>
> Highlights of this release
> 🔸DotNetRemovePackage alias
> 🔸DotNetAddPackage alias
> 🔸MacOS native dependency fixes
> 🔸Dependency and SDK updates
> https://cakebuild.net/blog/2023/11/cake-v3.2.0-released
> #dotnet #devops

**Date requested**
As soon as convenient.

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - for Members/Sponsors/Projects only

**Comment by ddskier** [comment]
Scheduled for Nov 21 on all social channels
