### ISSUE TITLE
[AMPLIFICATION] - The world of Delegates

### ISSUE THREAD

**Issue by Djoufson** [dotnet-foundation/content#201]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**

This content is a Medium blog post, about delegates and how to use them properly in C#. Delegates are a key feature in .NET modern applications, making them robust and more reliable. In this article we will dive deep into this concept, how it started? Where it is now and how to properly use delegates.

**URL of the content**

https://medium.com/@djouflegran/the-world-of-delegates-in-c-f44be8b2365f

**Copy for the content**

If you are not aware of delegates, I bet you use them without even knowing. Delegates are a must-know topic in our industry, and play a critical role in our everyday .NET applications. In this article, we will dive really deep into this topic, from the very basics to an acceptable level.
[Github](https://github.com/Djoufson)
[LinkedIn](https://linkedin.com/in/djoufson)
[Twitter/X](https://twitter.com/djouf_legran)

**Date requested**
November the 17th 2023

**Channel requested**
X/Twitter
LinkedIn
Newsletter

**Additional context**
I recently joined the .NET Foundation community, and recently started my blog writer journey. This is actually my 2nd post and I would like to make more content like this. I am pretty sure this could help more than one person who is new to the C# world, and hope that by amplifying my audience we will target this goal ✅

**Comment by ddskier** [comment]
Scheduled for Nov 17 on all social channels
