### ISSUE TITLE
[AMPLIFICATION] - Silk.NET 3.0 API Review

### ISSUE THREAD

**Issue by Perksey** [dotnet-foundation/content#202]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
Yes

**Please describe the content.**
Similar to #58, promoting another critical 3.0 design meeting where we discuss our progress on our prototypes for the next evolution of the Silk.NET library, and our proposals arising as a result of this.

**URL of the content**
https://youtu.be/yXNDZDE3AHE

**Copy for the content**
After months of prototyping, we're finally ready to share our designs for Silk.NET 3.0! Join us on 19th Nov 19:00 UTC where we discuss our proposals for 3.0, .NET's next evolution in native interoperability. Can't make it? Stream the VoD immediately! https://youtu.be/yXNDZDE3AHE

**Date requested**
ASAP

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
See #58 and https://github.com/dotnet-foundation/wg-marketing/issues/8, I remember writing some good words last time around.

**Comment by ddskier** [comment]
Scheduled for all social on Nov 18
