### ISSUE TITLE
[AMPLIFICATION] - Social Media Posts - Avanade's CTO's Review of Technology from MS Ignite

### ISSUE THREAD

**Issue by leeenglestone** [dotnet-foundation/content#205]
**Are you a .NET Foundation Member**
Yes, and corporate sponsor (Avanade)

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
As corporate sponsors we would love the .NET Foundation to help share our CTO's thoughts on technology from the latest MS Ignite.
MS Ignite is a developer conference so DNF followers and members may find the technologies mentioned interesting.

**URL of the content**
https://www.avanade.com/en/blogs/avanade-insights/artificial-intelligence/top-takeaways-microsoft-ignite-2023 

**Copy for the content**
Founded by Accenture and Microsoft, our corporate partner @Avanade knows a lot about the Microsoft stack. Hear from their CTO @AaronReich about his top technology takeaways from Microsoft Ignite and their impact – from data platform to Azure and Microsoft Copilot. Check out the writeup and videos:
 https://www.avanade.com/en/blogs/avanade-insights/artificial-intelligence/top-takeaways-microsoft-ignite-2023 ​

#AvanadeDoWhatMatters #PassionForTech #MSIgnite

![Slide1](https://github.com/dotnet-foundation/content/assets/2360725/ed6885d0-80d8-40f0-8699-c20b097c769f)

**Date requested**
As soon as is appropriate for DNF.

**Channel requested**
LinkedIn
Facebook
Newsletter - Published last day of the month for Members/Sponsors/Projects

**Additional context**
Add any other context or screenshots about the request here.
![Slide1](https://github.com/dotnet-foundation/content/assets/2360725/ed6885d0-80d8-40f0-8699-c20b097c769f)

Aarons LinkedIn profile (to help with tagging him in)
https://www.linkedin.com/in/aaron-reich/

**Comment by ddskier** [comment]
This is scheduled for 12/5 on all social channels. The social scheduling tool I use doesn't enable tagging on LinkedIn.

**Comment by nicoleabuhakmeh** [comment]
Actions Complete.
