### ISSUE TITLE
[AMPLIFICATION] - Infinite Days in Cameroon

### ISSUE THREAD

**Issue by Djoufson** [dotnet-foundation/content#206]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
I am a Microsoft Learn Student Ambassador and founder of The [.NET Cameroon](https://discord.gg/T8qp9bzA) community, that promotes the usage of .NET and Microsoft Technologies in Cameroon.
The Infinite Days is the first in-person event that we host, and will consist of two conferences and a hackathon. The .NET Foundation should amplify this event, in order to get more and more people interested with .NET in Cameroon, in Africa and later in the world.

**URLs of the content**
- [Registration for the in-person event](https://forms.office.com/r/bUs9MVqqkR)
- [Registration for the online live conference](https://www.linkedin.com/feed/update/urn:li:activity:7137734694598561794)

**Copy for the content**
🚀 Exciting News for Tech Enthusiasts in Cameroon! 🌍 Join our #dotnetevent to dive into the incredible world of .NET! 🎉 Whether you're a pro or a newbie, discover the power of .NET in our daily tasks. 🖥️✨

🔗 Register Now: https://forms.office.com/r/bUs9MVqqkR
🎙️ Don't miss out on the action! Tune in LIVE on LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:7137734694598561794

Let's embrace innovation together! 🚀 #dotnet #techconference #innovationintech

**Date requested**
- 07th of December 2023
- 10th of December 2023
- 13th of December 2023

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**

![Infinite Days](https://github.com/dotnet-foundation/content/assets/101910784/78e18833-b9f5-4934-ad5f-befa3e3fd51a)

**Comment by ddskier** [comment]
Scheduled on all social channels for 07th of December 2023 10th of December 2023 13th of December 2023
