### ISSUE TITLE
[AMPLIFICATION] - Improve your security by hiding your Application Insights instrumentation key from the browser

### ISSUE THREAD

**Issue by sander1095** [dotnet-foundation/content#208]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No (But an official .NET project)

**Please describe the content.**
This blog post teaches the reader how to improve the security of their front-end monitoring tools, like Azure Application Insights. By default, you need to expose an instrumentation key to use Application Insights, which is insecure when this is done in the browser becaues the user has access to it and could abuse it by spamming it with fake data.

By using a reverse-proxy to forward traffic to App Insights, you can hide this instrumentation key and keep your applications safe. The blog post does this using YARP, a reverse proxy made and used by Microsoft!

**URL of the content**
https://stenbrinke.nl/blog/hide-app-insights-key-from-the-browser/

**Copy for the content**
In this blog post you'll learn how to improve the security of your website and Azure Application Insights by hiding the Instrumentation Key from the browser. This prevents a malicious user from abusing your key it by sending fake traffic, increasing cloud costs!

**Date requested**
Before christmas/new years would be great!

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - Published last day of the month for Members/Sponsors/Projects

**Additional context**
The post is part of the .NET advent calendar and C# advent, so it has a festive theme. Anything you can do to make the post a bit festive would fit the theme ;)

**Comment by ddskier** [comment]
Scheduled on all social channels for Dec 11.
