### ISSUE TITLE
[AMPLIFICATION] - End-to-End Serverless Deep Neural Network with Azure Functions and ML.Net

### ISSUE THREAD

**Issue by praveenraghuvanshi** [dotnet-foundation/content#21]
**Please describe the content.**
An article about creating a end-to-end deep neural network for image classification leveraging transfer learning using ML.Net and deploying to Serverless Azure Functions. The .Net Foundation should amplify this content as it covers various concepts such as deep learning, transfer learning, microsoft azure and the code is in .Net(C#) language.

**URL of the content**
Article : Dev.To - https://dev.to/praveenraghuvanshi/end-to-end-serverless-deep-neural-network-with-azure-functions-and-ml-net-505a
Video: Serverless ANZ 2020 - https://www.youtube.com/watch?v=K2RPNaglHHc

**Copy for the content**
An End-to-End Serverless Deep Neural Network with Azure Functions and ML.Net

**Date requested**
At the earliest

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
This is scheduled for tomorrow, 9/16 at 6:45AM Pacific on FB & Twitter.

**Comment by praveenraghuvanshi** [comment]
Thanks for posting it, however it seems first link (hubs.ly/H0whdKn0) is broken... You can remove it.
