### ISSUE TITLE
[AMPLIFICATION] - Captcha component for Blazor

### ISSUE THREAD

**Issue by VahidFarahmandian** [dotnet-foundation/content#210]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
Today, there are many projects being developed that use right-to-left languages.  Aligning the components has always been one of the main challenges in these projects.  At `Jinget.Blazor` we try to solve this challenge.  The following article introduces the captcha component for Blazor projects, which supports RTL languages ​​such as Arabic, Farsi, Hebrew, etc.  We think that supporting the entire community can be interesting for the .NET Foundation and exciting for the audience. 

**URL of the content**
https://jinget.medium.com/captcha-component-for-blazor-41d86e239476

**Copy for the content**
Captcha component for Blazor, with RTL and LTR languages support, and also with plenty of interesting features published

Download NuGet: 
https://www.nuget.org/packages/Jinget.Blazor
View Source: https://github.com/VahidFarahmandian/Jinget

**Date requested**
Dec 13th 2023

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - Published last day of the month for Members/Sponsors/Projects

**Additional context**
---

**Comment by ddskier** [comment]
Scheduled for 8AM PST on Dec 13

**Comment by nicoleabuhakmeh** [comment]
Actions Complete.
