### ISSUE TITLE
[AMPLIFICATION] - Uno Platform 5.0 Live Webinar

### ISSUE THREAD

**Issue by mtmattei** [dotnet-foundation/content#211]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
Uno Platform Live webinar about 5.0 release. =In this webinar, we will show the new features delivered in 5.0, platform benefits, tools, and techniques to make you as productive as you can be in developing cross-platform .NET applications.

**URL of the content**
[Link to the article, blog, video, social post, presentation, etc. ](https://youtube.com/live/TeA6zEq5MGk)

**Copy for the content**
📢Hey .NET Devs! Join Uno Platform's free 5.0 webinar today at 12 PM EST. They'll be talking all about their new C# markup, Hot Reload, Figma to C# magic, and .NET MAUI embedding. Plenty of demos and awesome giveaways you won't want to miss! 🎁
Tune in here: https://youtube.com/live/TeA6zEq5MGk
![5 0webinar](https://github.com/dotnet-foundation/content/assets/90909523/6e28755d-1e88-4e62-b32b-3eb3db3bcecb)

**Date requested**
12/12/23 - Only amplify if approved for the day asked. Thank you 

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Scheduled for Dec 12 at 8AM PST on all social handles
