### ISSUE TITLE
[AMPLIFICATION] - Fullstack .NET web apps in F#/C# with charting + reactive forms

### ISSUE THREAD

**Issue by granicz** [dotnet-foundation/content#217]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
I would like to amplify this content because it's relevant to all F#/C# fullstack web developers: it describes an ASP.NET project template that boosts productivity, talks about power features that make .NET web programming fun(ctional) and type safe, and can inspire more developers to use ASP.NET Core.

**URL of the content**
https://intellifactory.com/user/granicz/20240102-A-new-fullstack-SPA-template-for-WebSharper-and-whats-next

**Copy for the content**
It would be great to RT my original tweet - https://twitter.com/granicz/status/1742351337516679605 with a message to #csharp #fsharp #aspnetcore developers. The headline could be "Fullstack .NET web apps in F# with charting + reactive forms - reloaded"

**Date requested**
As soon as you can

**Channel requested**
X/Twitter, LinkedIn, Facebook, Newsletter

**Additional context**
https://intellifactory.com/assets/fullstack-spa-Tables.png
https://intellifactory.com/assets/fullstack-spa-Charting.png
https://intellifactory.com/assets/fullstack-spa-Forms.png

**Comment by ddskier** [comment]
I retweeted this on .NET Foundation handle. I'll also share the blog post next week and probably in the future on all social handles

**Comment by granicz** [comment]
Thanks @ddskier !

**Comment by nicoleabuhakmeh** [comment]
Actions Complete.
