### ISSUE TITLE
[AMPLIFICATION] - Avalonia - Sustainable OSS

### ISSUE THREAD

**Issue by MikeCodesDotNET** [dotnet-foundation/content#218]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
Yes

**Please describe the content.**
A blog post describing the challenges of scaling a popular OSS project and how we're generating revenue that funds a team of full-time developers to work on improving Avalonia. 

**URL of the content**
[Link to the article, blog, video, social post, presentation, etc. 
](https://avaloniaui.net/Blog/balancing-growth-and-sustainability-avalonia-s-financial-evolution)

**Copy for the content**
Creating sustainable OSS is a huge challenge! 

Discover @AvaloniaUI's approach to funding a growing team that works on improving the .NET Foundation's most popular community project. 

https://avaloniaui.net/Blog/balancing-growth-and-sustainability-avalonia-s-financial-evolution
**Date requested**
ASAP

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - Published last day of the month for Members/Sponsors/Projects

**Additional context**
We updated the post today (5th) to include our EOY revenue numbers.

**Comment by ddskier** [comment]
Scheduled on all social channels for Jan 9

**Comment by nicoleabuhakmeh** [comment]
Added to Newsletter
