### ISSUE TITLE
[AMPLIFICATION] - PostgreSQL range types and Entity Framework Core

### ISSUE THREAD

**Issue by Giorgi** [dotnet-foundation/content#219]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
The .NET Foundation should amplify this content because it describes how to use PostgreSQL range types with Entity Framework Core.

**URL of the content**
https://www.giorgi.dev/database/postgresql-range-types-entity-framework/

**Copy for the content**
Learn about the power of PostgreSQL range types and how to use it with Entity Framework Core.

**Date requested**
11.01

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - Published last day of the month for Members/Sponsors/Projects

**Comment by ddskier** [comment]
The URL for this content didn't come through in your request.

**Comment by Giorgi** [comment]
Oops, fixed it.

**Comment by ddskier** [comment]
Will post to all social channels on Jan 11

**Comment by nicoleabuhakmeh** [comment]
Actions Complete
