### ISSUE TITLE
[AMPLIFICATION] - Use Kubernetes for Modern .NET Apps? Steeltoe and Project Tye are Your Path to Productivity

### ISSUE THREAD

**Issue by ddieruf** [dotnet-foundation/content#22]
**Please describe the content.**
This is a blog post about new K8s features in Steeltoe 3.0 and how a developer can pair their .NET microservices using Steeltoe with Tye to create a good developer experience.

**URL of the content**
https://steeltoe.io/blog/tech-tutorial-use-kubernetes-for-modern-net-apps-steeltoe-and-project-tye-are-your-path-to-productivity

**Copy for the content**
[Longer]
Learn how the combination of Steeltoe and Tye can make your .NET on Kubernetes cloud-native in a snap! Develop locally in the same environment that your apps use for production. See how Steeltoe can wipe out all that boilerplate code in just a few simple lines.

[Abbreviated]
Got .NET Kubernetes? Then you need Steeltoe and Tye. Learn about them now.

[Twitter]
Got @dotnet @kubernetesio? Then you need @steeltoeoss and #Tye. Learn about them now.

**Date requested**
10/2/2020 (or the next available slot)

**Channel requested**
Facebook, Twitter - yes please

**Additional context**
Nope

cc: @jkonicki

**Comment by ddskier** [comment]
This is scheduled on Facebook and Twitter on Monday, Oct 5 at 6:45AM PDT.
