### ISSUE TITLE
[AMPLIFICATION] - Introduction to Rx.NET 2nd Edition (2024) book is available for FREE

### ISSUE THREAD

**Issue by HowardvanRooijen** [dotnet-foundation/content#221]
**Are you a .NET Foundation Member**
Yes (Corporate Sponsor)

**Is this for promoting a .NET Foundation Project**
Yes

**Please describe the content.**

Lee Campbell donated the contents of his 2010 book "Introduction to Rx.NET" to the Rx.NET Project (and the .NET Foundation), we spent 2023H2 rewriting the book, bringing it up to date with Rx.NET v6.0 & .NET 8.0, and have made it available for FREE to the .NET Community.

**URL of the content**
https://endjin.com/blog/2024/01/introduction-to-rx-dotnet-2nd-edition-book-available-for-free
or
https://introtorx.com/

**Copy for the content**

The Reactive Extensions for .NET were designed for a Cloud Native future, which has now arrived. Rx.NET is one of .NET's superpowers. Introduction to Rx.NET 2nd Edition (2024) is available for FREE as PDF, EPUB, Online, and on GitHub. See https://introtorx.com for more details.

**Date requested**
The date you are requesting us to amplify. We will try to hit that if approved. 

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - Published last day of the month for Members/Sponsors/Projects

**Additional context**
We have some design assets:

https://res.cloudinary.com/endjin/image/upload/f_auto/q_80/c_scale/w_1024/assets/images/blog/2024/01/introduction-to-rx-dotnet-2nd-edition-book-available-for-free.jpg

https://res.cloudinary.com/endjin/image/upload/v1705050242/assets/images/blog-graphics/free-introduction-to-rx-dotnet-2nd-edition-book-2023-now-available.png

**Comment by ddskier** [comment]
This is scheduled for Jan 17 on all social channels

**Comment by HowardvanRooijen** [comment]
Thank you!

**Comment by nicoleabuhakmeh** [comment]
Added to January Newsletter.
