### ISSUE TITLE
[AMPLIFICATION] - YeSQL.Net 1.0.0 released

### ISSUE THREAD

**Issue by MrDave1999** [dotnet-foundation/content#223]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
YeSQL.NET is a class library for loading SQL statements from .sql files instead of writing SQL code in your C# source files.

**URL of the content**
[Repository](https://github.com/ose-net/yesql.net)

**Copy for the content**
> YeSQL.NET v1.0.0 released 🚀 🍰
>
> YeSQL.NET is a class library for loading SQL statements from SQL files.
>
> It is no longer necessary to hardcode the SQL code in the application source code. Create a file with .sql extension and use YeSQL.NET to load the sql file.
> https://github.com/ose-net/yesql.net #dotnet #csharp #oss #sql #yesql

**Date requested**
As soon as convenient.

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - Published last day of the month for Members/Sponsors/Projects

**Additional context**
Thanks 👍

**Comment by ddskier** [comment]
Scheduled for Jan 25 and repeating on Jan 29 on all social handles
