### ISSUE TITLE
[AMPLIFICATION] - Released DotVVM 4.2

### ISSUE THREAD

**Issue by tomasherceg** [dotnet-foundation/content#224]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
Yes

**Please describe the content.**
Information about the recent release of DotVVM 4.2 and a link to the blog post with the announcement.

**URL of the content**
https://www.dotvvm.com/blog/111/Released-DotVVM-4-2

**Copy for the content**
**DotVVM 4.2** brings several new features and many improvements. The **migration of Web Forms applications to .NET 8** is easier thanks to the new Web Forms Adapters package. You can use **strongly typed identifiers in the UI layer**, enjoy **validation attributes in static commands**, and much more.

![Released DotVVM 4.2](https://pbs.twimg.com/media/F-4FGVea0AAXIxQ?format=png&name=medium)

**Date requested**
Any time.

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - Published last day of the month for Members/Sponsors/Projects

**Additional context**
N/A

**Comment by ddskier** [comment]
Scheduled for Jan 26 and repeating Jan 31 on all social channels

**Comment by nicoleabuhakmeh** [comment]
Added to the Newsletter for January.
