### ISSUE TITLE
[AMPLIFICATION] - SimpleAuthentication

### ISSUE THREAD

**Issue by marcominerva** [dotnet-foundation/content#225]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
A library to easily integrate Authentication in ASP.NET Core projects. It supports JWT Bearer, API Key and Basic Authentication in both Controller-based and Minimal API projects and requires only one line of code. All the configuration can be done in the appsettings.json file. It also automatically integrates with Swagger.

**URL of the content**
https://github.com/marcominerva/SimpleAuthentication

**Copy for the content**
With SimpleAuthentication, you can easily integrate Authentication in ASP.NET Core projects with just one line of code. It supports JWT Bearer, API Key and Basic Authentication. Check it out at https://github.com/marcominerva/SimpleAuthentication.

**Date requested**
05 february 2024

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - Published last day of the month for Members/Sponsors/Projects

**Additional context**
https://www.youtube.com/watch?v=SVZuaPE2yNc

**Comment by ddskier** [comment]
Scheduled for Feb 5 on all social channels

**Comment by nicoleabuhakmeh** [comment]
Actions Complete.
