### ISSUE TITLE
[AMPLIFICATION] - Sisk Framework

### ISSUE THREAD

**Issue by CypherPotato** [dotnet-foundation/content#226]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No, but already [submitted to board](https://github.com/orgs/dotnet-foundation/projects/8?pane=issue&itemId=41588468)

**Please describe the content.**
This project is an experiment to create a lightweight HTTP framework for .NET, an alternative to ASP.NET, with a philosophy of being agnostic of architectures and standards and enabling cloud-native development in a fast and modular way. It is important because it gives the .NET developer an alternative, open-source HTTP technology for cloud and web development.

**URL of the content**
[Link to the article, blog, video, social post, presentation, etc. ](https://sisk.project-principium.dev/)

**Copy for the content**

```
Meet the Sisk Framework 🚀, a lighter alternative for you to build your
next cloud app the way you want.

With Sisk, you can code the way you want. Create MVC, MVVC, SOLID
applications, or any other design pattern you're interested in. You have full control here!

Build your first Sisk app today: https://sisk.proj.pw #dotnet #web #http
```

**Date requested**
The best date that the .NET Foundation finds.

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter

**Additional context**
It would be really cool and I would be happy if the .NET Foundation could create an article or content about Sisk. He has been alive for a year, and already has an [article published](https://khalidabuhakmeh.com/sisk-an-alternative-dotnet-http-server) independently by a volunteer.

Publicizing it would attract more .NET developers to test, give their opinions and improve the project.

Thank you.

**Comment by ddskier** [comment]
Scheduled for Feb 1 and repeating on Feb 6 on all social channels
