### ISSUE TITLE
[AMPLIFICATION] - Bulk on EFCore with ExecuteUpdate and ExecuteDelete

### ISSUE THREAD

**Issue by pierrebelin** [dotnet-foundation/content#227]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
It's a blog post to present how to bulk on EFCore with ExecuteUpdate and ExecuteDelete in .NET8. The article is quick and strait to the point!

**URL of the content**
https://goatreview.com/bulk-efcore-executeupdate-executedelete/

**Copy for the content**
Eager to optimize your database operations in Entity Framework Core? Unleash the power of ExecuteUpdate and ExecuteDelete, the 🐐 methods for batch updates and deletes! 🚀

Delve into this article to learn how these latest enhancements in EF Core revolutionize the way developers handle data, prioritizing performance and simplicity.

🔗 Article: https://goatreview.com/bulk-efcore-executeupdate-executedelete/

Upgrade your EF Core skills and let these methods do the heavy lifting! Subscribe to our newsletter at the end of the article for more expert insights. 😎

Connect with Pierre Belin 👉 https://www.linkedin.com/in/pierre-belin/

**Date requested**
As you prefer

**Channel requested**
LinkedIn
Newsletter - Published last day of the month for Members/Sponsors/Projects

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Scheduled for Feb 2 and repeating Feb 12 on LinkedIn

**Comment by nicoleabuhakmeh** [comment]
Actions Complete.
