### ISSUE TITLE
[AMPLIFICATION] - SimpleResults Library

### ISSUE THREAD

**Issue by MrDave1999** [dotnet-foundation/content#229]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
A simple library to implement the Result pattern for returning from services.

**URL of the content**
https://github.com/MrDave1999/SimpleResults

**Copy for the content**
> SimpleResults released 🚀 🍰
> 
> SimpleResults is a simple library that serves as a sample on how to implement the Result pattern in NET.
> It also has support for translating the result object to HTTP status code for both MVC controllers and Minimal APIs.
> https://github.com/MrDave1999/SimpleResults #dotnet #csharp #oss #result-pattern

**Date requested**
As soon as convenient.

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - Published last day of the month for Members/Sponsors/Projects

**Additional context**
Thanks. 👍

**Comment by ddskier** [comment]
Scheduled for Feb 14 on all social channels
