### ISSUE TITLE
[AMPLIFICATION] - Stride game engine Release 4.2

### ISSUE THREAD

**Issue by tebjan** [dotnet-foundation/content#230]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
Yes

**Please describe the content.**
New 4.2 Release with .NET 8 and C#12 support.

**URL of the content**
https://twitter.com/stridedotnet/status/1755009850969411698
https://www.stride3d.net/blog/announcing-stride-4-2-in-dotnet-8

**Copy for the content**
The free and open-source .NET game engine Stride just released version 4.2 with support for .NET8 and C#12.

**Date requested**
asap

**Channel requested**
X/Twitter (retweet our tweet)
LinkedIn (Link to blog post)
Facebook (Link to blog post)
Newsletter - Published last day of the month for Members/Sponsors/Projects (Link to blog post)

But you can also choose what fits best.

**Comment by ddskier** [comment]
Retweeted on Twitter account and will run again on all accounts on Feb 15

**Comment by nicoleabuhakmeh** [comment]
Actions Complete.
