### ISSUE TITLE
[AMPLIFICATION] - Unhandled Exception Podcast episode 65 - Mads Torgersen, Dan Roth, and Scott Hunter (C# and Blazor)

### ISSUE THREAD

**Issue by dracan** [dotnet-foundation/content#231]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
This is for the next Unhandled Exception podcast episode, which is a podcast mostly about .NET and .NET projects/technologies.

**URL of the content**
https://unhandledexceptionpodcast.com/posts/0065-madst-danr-scotth/

**Copy for the content**

Twitter:
In the latest #UnhandledException podcast, @dracan was joined by @MadsTorgersen, @danroth27, and
@coolcsh to chat about #Blazor, C#12 interceptors, C#13, source generators, discriminated unions, AOT, and more!
https://unhandledexceptionpodcast.com/posts/0065-madst-danr-scotth/
#dotnet

Others:
In the latest #UnhandledException podcast, Dan was joined by Mads Torgersen, Dan Roth, and
Scott Hunter to chat about #Blazor, C#12 interceptors, C#13, source generators, discriminated unions, AOT, and more!
https://unhandledexceptionpodcast.com/posts/0065-madst-danr-scotth/
#dotnet

**Date requested**
Up to you :)

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - Published last day of the month for Members/Sponsors/Projects

**Additional context**

For the LinkedIn post, could you add a link at the bottom to my LinkedIn profile? (https://www.linkedin.com/in/danclarkeuk)

Thank you 🙂🙏
Dan

Also, here's a graphic for social media posts...

![SocialMediaPostImage](https://github.com/dotnet-foundation/content/assets/567988/9f5c2acf-819b-4854-940a-616684e5bcff)

**Comment by ddskier** [comment]
Scheduled Feb 19 on all social channels. Also included link to LinkedIn profile for LI post.

**Comment by dracan** [comment]
Amazing! Thank you @ddskier! 😊🙏

**Comment by nicoleabuhakmeh** [comment]
Actions Complete.
