### ISSUE TITLE
[AMPLIFICATION] - EFCore.Visualizer

### ISSUE THREAD

**Issue by Giorgi** [dotnet-foundation/content#233]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
With Entity Framework Core query plan debugger visualizer, you can view the query plan of your queries directly inside Visual Studio. Currently, the visualizer supports SQL Server and PostgreSQL.

This is a [free extension for Visual Studio 2022](https://marketplace.visualstudio.com/items?itemName=GiorgiDalakishvili.EFCoreVisualizer) that is also open sourced: https://github.com/Giorgi/EFCore.Visualizer

**URL of the content**
https://marketplace.visualstudio.com/items?itemName=GiorgiDalakishvili.EFCoreVisualizer
https://github.com/Giorgi/EFCore.Visualizer

**Copy for the content**
View Entity Framework Core query plan directly inside Visual Studio. Supports SQL Server and PostgreSQL. Requires VS 17.9 or newer

**Date requested**
Feb 16 or later

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter

**Additional context**

If possible make **Requires VS 17.9 or newer** bold.

![SqlPlan2](https://github.com/dotnet-foundation/content/assets/580749/5901ccea-3b0b-4829-b58a-2d707df1d9ab)
![PostgreSQLPlan2](https://github.com/dotnet-foundation/content/assets/580749/7cd801f8-d76d-4d87-9140-91d8126ec76e)

**Comment by ddskier** [comment]
Scheduled for Feb 20 on all social channels

**Comment by nicoleabuhakmeh** [comment]
Actions Complete.
