### ISSUE TITLE
[AMPLIFICATION] - Takeaways from pioneers in Microsoft Copilot adoption

### ISSUE THREAD

**Issue by leeenglestone** [dotnet-foundation/content#235]
**Are you a .NET Foundation Member**
Yes, and corporate sponsor (Avanade)

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
A forbes article featuring Avanade AI experts talking about the value of a people-first approach with AI.

**URL of the content**
(https://www.linkedin.com/posts/avanade_generativeai-copilot-ai-activity-7161457899460915200-zKhn?utm_source=share&utm_medium=member_desktop)

**Copy for the content**
🔎 Click to reveal the secrets of #GenerativeAI in the workplace straight from the pioneers leading the charge in Microsoft #Copilot adoption. 

The latest Forbes article features our Chief AI Officer Florin Rotar and Zoe Wilson who spotlight the value of a people-first approach, avoiding unintended #AI divides and much more: https://www.forbes.com/sites/avanade/2024/02/06/generative-ai-in-the-workplace-5-takeaways-from-pioneers-in-microsoft-copilot-adoption/?sh=f6147a668f8b&utm_campaign=aicopilot-ao&utm_source=linkedin&utm_medium=soc-or&utm_content=&_bl=%7BcreativeId%7D

![1707424613016](https://github.com/dotnet-foundation/content/assets/2360725/a43f4ad8-1ef2-40b1-a1f3-804aed0ca363)

![1707424614001](https://github.com/dotnet-foundation/content/assets/2360725/6b4fd9ca-e044-4dac-866e-4cd61d8203df)

![1707424614871](https://github.com/dotnet-foundation/content/assets/2360725/f4a30db5-6cdc-4fd2-bef2-b1af6cdc0da7)

![1707424615413](https://github.com/dotnet-foundation/content/assets/2360725/a7a0580b-1c3d-40c1-9f7a-72239eb37426)

**Date requested**
Ideally sometime w/ 19th February or the next week

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Scheduled for Feb 28 on all social channels
