### ISSUE TITLE
[AMPLIFICATION] - MinimaHelpers

### ISSUE THREAD

**Issue by marcominerva** [dotnet-foundation/content#245]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
A collection of helpers libraries for Minimal API projects. Among the others, there is a Source Generator for automatic endpoints registration.

**URL of the content**
https://github.com/marcominerva/minimalhelpers

**Copy for the content**
A collection of helpers libraries for Minimal API projects. Among the others, there is a Source Generator for automatic endpoints registration:
1) Implement the auto-generated IEndpointRouteHandlerBuilder interface
2) Call the MapEndpoints() method in the Program.cs

**Date requested**
03-apr-2024

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter

**Additional context**
![image](https://github.com/dotnet-foundation/content/assets/3522534/3cd67787-7622-4845-bc3c-719fd8ef0647)

**Comment by ddskier** [comment]
Set for Apr 3 on all social channels
