### ISSUE TITLE
[AMPLIFICATION] - Beautiful .NET Test Reports Using GitHub Actions

### ISSUE THREAD

**Issue by SeanKilleen** [dotnet-foundation/content#246]
**Are you a .NET Foundation Member**
Yes (at least I think? I paid annual dues but then I think there were some changes. If not, I'll rectify it!) I'm also an MS MVP in developer tools.

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**

I've heard from several in the .NET community that they wish they had better insight into their tests in GitHub Actions. I wrote a post to showcase how I've used actions created by others in the GitHub community to achieve this. It's one of those things that folks don't necessarily think to look for until they've seen it in action, and so I want to amplify here in the hopes of making the lives of .NET OSS devs a bit easier.

**URL of the content**

https://seankilleen.com/2024/03/beautiful-net-test-reports-using-github-actions/

**Copy for the content**

Using GitHub Actions to build & test your .NET projects? Sean Killeen shows you a way to improve test reports and outputs within your PRs: [link]

(Not sure if you use `@GitHub`, `#dotnet`, etc -- but it's fine with me if you convert those)

**Date requested**

Your earliest convenience. No rush; I just see it as an article I wish I'd existed when I was building my CI/CD pipeline.

**Channel requested**

✅ X/Twitter
✅ LinkedIn
Facebook
✅ Newsletter - Published last day of the month for Members/Sponsors/Projects

**Additional context**

I'm unsure whether this rises to a level of helpfulness that warrants inclusion in the newsletter; I'll leave that for you to decide.

Thank you!

**Comment by ddskier** [comment]
Scheduled for Apr 2 on all social channels
