### ISSUE TITLE
.NET 5 and .NET 6 with Scott Hunter

### ISSUE THREAD

**Issue by IrinaLeonteva** [dotnet-foundation/content#25]
**Please describe the content.**
Join the online meetup with Scott Hunter, Director of Program Management for the .NET at Microsoft!

The meetup is on February 16.

The main talk will cover the state of .NET and give an overview of all the new capabilities in .NET 5. This includes new features for building smaller, faster Web API's and gRPC for Microservices, Windows desktop enhancements including ClickOnce, and the new features in Blazor for SPA's. Scott will also talk about the journey to One .NET and show a preview of Project Tye to build and publish Microservices. The meeting ends with a glance into the future in .NET 6.

**URL of the content**
https://www.meetup.com/nopCommerce-Global-Meetup/events/275569812/
**Copy for the content** (Copy for Twitter)
Join the online meetup with Scott Hunter, Director of Program Management for the .NET at Microsoft!

The meetup is on February 16.

The main talk will cover the state of .NET and give an overview of all the new capabilities in .NET 5. 

**Date requested**
4 February 2021

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). 

**Additional context**
![89](https://user-images.githubusercontent.com/78420362/106600061-fb2e8200-656a-11eb-974d-b340deffacac.png)

**Comment by ddskier** [comment]
This has been scheduled for Feb 4 on Twitter and Facebook
