### ISSUE TITLE
[AMPLIFICATION] - DentallApp Release

### ISSUE THREAD

**Issue by MrDave1999** [dotnet-foundation/content#250]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
A web application that manages appointment scheduling, reminders and cancellation of appointments

**URL of the content**
https://github.com/DentallApp/back-end

**Copy for the content**
> DentallApp is a software with chatbot for appointment management, reminders and sending appointment cancellation messages.
> The goal of this project is to provide an example of how to use a Plug-in Architecture to decouple third-party technologies from your host application.
> https://github.com/DentallApp/back-end #csharp #oss #webapi #plugins

**Date requested**
Tomorrow if it is possible

**Channel requested**
X/Twitter
LinkedIn
Facebook
Newsletter - Published last day of the month for Members/Sponsors/Projects

**Additional context**
Thanks. 👍

**Comment by ddskier** [comment]
Scheduled for tomorrow Apr 12 on all social channels
