### ISSUE TITLE
[AMPLIFICATION] - Azure Developers - .NET Day 2024

### ISSUE THREAD

**Issue by v-LukeReardon** [dotnet-foundation/content#251]
**Are you a .NET Foundation Member**
No - I am a vendor supporting the .NET Marketing team's efforts at Microsoft.

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
The .NET Foundation should amplify this content because it provides news about an upcoming event - Azure Developers - .NET Day 2024, which members of the foundation would be interested in attending. For more information on the event, you can check out our blog or webpage listed below.

**URL of the content**
- Event webpage: https://aka.ms/azuredevelopers/dotnetday 
- Blog post: https://devblogs.microsoft.com/dotnet/announcing-azure-developers-dotnet-day-2024/

**Copy for the content**
Azure Developers .NET Day is back! Join the .NET community on April 30th to learn cutting-edge cloud development techniques from experts on cloud services for AI, data, cloud-native, and developer productivity. Elevate your cloud development skills today:
https://aka.ms/azuredevelopers/dotnetday

**Date requested**
This event is on the 30th so any and all social promotion would be appreciated.

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
Not sure if possible to also be included in the newsletter? If not, no problem. Please let me know if there are any questions.

**Comment by ddskier** [comment]
Scheduled for Apr 23 on all social channels. I'll repeat it at least once prior to the event

**Comment by v-LukeReardon** [comment]
Amazing, thank you!

Thanks,
Luke Reardon

**Comment by ddskier** [comment]
Update - this post will repeat on social channels on Apr 29

**Comment by v-LukeReardon** [comment]
[like]  Luke Reardon (Spur Reply LLC) reacted to your message:
________________________________
