### ISSUE TITLE
[AMPLIFICATION] - JetBrains Tooling Survey

### ISSUE THREAD

**Issue by khalidabuhakmeh** [dotnet-foundation/content#252]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**

A survey link request and amplification to help better understand .NET developer tooling.

**URL of the content**

https://surveys.jetbrains.com/s3/v11-net-development-survey

**Copy for the content**

JetBrains wants to better understand how developers work with #dotnet and which tooling they prefer to be more productive. Please help us by filling out this short survey, which will take around 10 minutes.

**Date requested**
The date you are requesting us to amplify. We will try to hit that if approved. 

**Channel requested**

- [x] X/Twitter 
- [x] LinkedIn
- [x] Facebook
- [ ] Newsletter

**Additional context**

At JetBrains, we are trying to better understand how developers work in .NET development and which tooling they prefer to be more productive. Please help us by filling out this short survey, which should take around 10 minutes.

By participating in our survey, not only will you help us with our research, but you’ll also get the chance to win one of five $50 Amazon Gift Cards or a one-year All Products Pack subscription. The winners will be picked randomly from among the responses that have completed the survey with meaningful answers.

Any information you provide will be kept strictly confidential.

**Comment by ddskier** [comment]
This will post to all social channels on May 2 and repeat on May 7. Let me know if you want me to repeat it more.

**Comment by khalidabuhakmeh** [comment]
Thanks @ddskier. I appreciate what you do. 🙏

**Comment by khalidabuhakmeh** [comment]
Thanks everyone. Cheers.
