### ISSUE TITLE
[AMPLIFICATION] - JetBrains .NET Days Online 2024 Call for Speakers

### ISSUE THREAD

**Issue by maartenba** [dotnet-foundation/content#253]
**Please describe the content.**
Promotion of the JetBrains .NET Days Online call for speakers. We're hosting an event for the wider .NET community, and would like to attract some speakers.

**URL of the content**
https://jb.gg/38cyrc

**Copy for the content**
Tweet text:

```
JetBrains have opened the Call for Speakers for the 2024 JetBrains .NET Days Online 🎉

✔️ Have a great session to share with fellow #dotnet folks?
✔️ Available to present on September 25 or 26?
👉 Submit your talk! https://jb.gg/38cyrc
```

**Date requested**
Before June 1, 2024. Ideally two tweets along the way.

**Channel requested**
Facebook, Twitter, and if possible - newsletter

Thank you folks! 🙏

**Comment by ddskier** [comment]
I have it posting to all social channels on May 6, 15, and 27

**Comment by maartenba** [comment]
Thank you!
