### ISSUE TITLE
Open Source Project: ASP.NET Core Inventory Management System

### ISSUE THREAD

**Issue by go2ismail** [dotnet-foundation/content#254]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
ASP.NET Core Razor Pages implementation of inventory order management. Warehouse, product, vendor, customer, purchase order, sales order, shipment, goods receive and more

**URL of the content**
[https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System)

**Copy for the content**
Welcome to our Warehouse Inventory Management System (WHMS), a cutting-edge solution meticulously designed to revolutionize your inventory operations. Powered by ASP.NET Core 8.0 Razor Pages (C#), WHMS offers a comprehensive suite of features including Sales, Purchase, Delivery, Goods Receive, Transfer, Adjustment, Return, Scrapping, Stock Count, Transaction Report, Movement Report, and Stock Report. Seamlessly manage your warehouse inventory with ease and precision, ensuring optimal stock levels, streamlined workflows, and enhanced productivity. Experience the future of inventory management with WHMS – your ultimate tool for operational excellence.

**Date requested**
The date you are requesting us to amplify. We will try to hit that if approved. 

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
![image](https://github.com/dotnet-foundation/content/assets/2275051/5657cd80-b488-4141-9c3a-ef9cb8e22d61)

**Comment by ddskier** [comment]
Scheduled for May 8 on all social channels
