### ISSUE TITLE
[AMPLIFICATION] - Oqtane 5.1 With Static Server Rendering

### ISSUE THREAD

**Issue by sbwalker** [dotnet-foundation/content#256]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
Yes

**Please describe the content.**
Release announcement for the Oqtane Framework open source project

**URL of the content**
https://www.oqtane.org/blog/!/84/announcing-oqtane-5-1-with-static-server-rendering

**Copy for the content**
With the release of 5.1, Oqtane now utilizes Microsoft's latest recommended patterns for developing full-stack Blazor applications, supporting both Static Server Rendering (SSR) and Interactive render modes within the same application. This new capability has been integrated into Oqtane's existing architecture to provide multi-tenancy, modularity, and a robust security model which allows developers to focus on building applications rather than infrastructure.

**Date requested**
Week of May 6

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Scheduled for Thurs, May 9, Repeating on May 20th
