### ISSUE TITLE
[AMPLIFICATION] - Uno Platform 5.2

### ISSUE THREAD

**Issue by mtmattei** [dotnet-foundation/content#257]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
Amplifying Uno Platform 5.2 release. We' just released a new version of Uno Platform, and would like to attract new users and feedback.

**URL of the content**
Article: https://platform.uno/blog/the-first-and-only-true-single-project-for-mobile-web-desktop-and-embedded-in-net/

video: https://youtube.com/live/Hm8OAIIfZ0g?feature=share

**Copy for the content**
Uno Platform 5.2 - Simplifying development and accelerating build times. 

📂 New Single Project structure
⚡ Enhanced Skia capabilities
🪟 Multi-Window support
🪄 Updated Wizard
9️⃣ .NET 9 preview support

🔗Read the full release: https://platform.uno/blog/the-first-and-only-true-single-project-for-mobile-web-desktop-and-embedded-in-net/

👉Watch 5.2 in action! https://youtube.com/live/Hm8OAIIfZ0g?feature=share

**Date requested**
May 8th, 2024 and/or May 15th 2024

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Scheduled for May 15 and repeating May 21. Will post to all social channels
