### ISSUE TITLE
[AMPLIFICATION] - The Breakpoint Show - Boring Tech Episode 

### ISSUE THREAD

**Issue by khalidabuhakmeh** [dotnet-foundation/content#260]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
The Breakpoint Show is a podcast-style show with community members Chris Woodruff, Maarten Balliauw, and Khalid Abuhakmeh and the occasional guest.

**URL of the content**
Link to the article, blog, video, social post, presentation, etc. 

**Copy for the content**

“The Breakpoint Show" dives into a seemingly paradoxical topic: boring technology. Join the guys as they explore why embracing boring technology can be a game-changer for software developers.

https://www.youtube.com/watch?v=CFb2p4ymQPQ

**Date requested**

Whenever it is available.

**Channel requested**
- [x] X/Twitter 
- [x] LinkedIn
- [x] Facebook

**Additional context**

website: https://www.breakpoint.show/

**Comment by ddskier** [comment]
Set for May 29 on all social channels and repeating on Jun 4.
