### ISSUE TITLE
[AMPLIFICATION] - Tackling Primitive Obsession in .NET

### ISSUE THREAD

**Issue by SteveDunn** [dotnet-foundation/content#261]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
The content I would like to amplify is my open source project, Vogen, which tackles a code-smell/anti-pattern called Primitive Obsession.
The content is an open source repo in GitHub and a NuGet package (with over 600,00 downloads).

I feel it is important to the .NET open source community as it promotes cleaner and more readable code.

**URL of the content**
A wrote a blog post on Primitive Obsession here: https://dunnhq.com/posts/2021/primitive-obsession/
The rep is here:  https://github.com/SteveDunn/Vogen

**Copy for the content**
I'm open to how you'd like to interpret the content, but the message I'd like to convey is about the Primitive Obsession smell, and how Vogen helps.

**Date requested**
Any date will do. I've been working on this for a few years now, so there's no particular rush.

**Channel requested**
X/Twitter
LinkedIn
Facebook

As many as possible! Whatever you can manage would be greatly appreciated!

**Additional context**
No additional context springs to mind.

**Comment by ddskier** [comment]
Scheduled for May 30 and repeating on June 10 on all social channels

**Comment by SteveDunn** [comment]
> Scheduled for May 30 and repeating on June 10 on all social channels

Thank you! 👍

**Comment by SteveDunn** [comment]
Hi @ddskier , I didn't see it in the last newsletter...

**Comment by ddskier** [comment]
@SteveDunn, it doesn't look like you requested newsletter in your original request.
Also, I only handle social media. @nicoleabuhakmeh manages the newsletter

**Comment by SteveDunn** [comment]
Thank you. @nicoleabuhakmeh , any chance I could be in the next newsletter? Thanks in advance!
