### ISSUE TITLE
[AMPLIFICATION] - Everything you need to know about OpenAPI and API client generation

### ISSUE THREAD

**Issue by sander1095** [dotnet-foundation/content#263]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
This posts teaches the user about problems you usually encounter whilst building API's. Next, it teaches about OpenAPI and related tooling, including API Client generation which can solve the problems mentioned earlier.  Knowing how to use OpenAPI and API client generation saves time and prevents lots of duplicate code. It's also very fun!

**URL of the content**
https://stenbrinke.nl/blog/openapi-api-client-generation/

**Copy for the content**
Building API's is fun but API discoverability is tough and writing API clients is time consuming and boring. This extensive posts teaches you how OpenAPI can fix this with API Client generation, other tooling, and more!
 
**Date requested**
As early as possible, whatever works for the .NET foundation team! :)

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Scheduled for June 11 on all social channels

**Comment by ddskier** [comment]
Also repeating on all social on June 19

**Comment by sander1095** [comment]
Thanks @ddskier ! I _really_ appreciate it <3
