### ISSUE TITLE
[AMPLIFICATION] - ASP.NET Core Online Dashboard Designer

### ISSUE THREAD

**Issue by go2ismail** [dotnet-foundation/content#264]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
Welcome to Visual BI, an innovative Online Dashboard Designer meticulously crafted to transform your data analysis experience. Powered by cutting-edge technology and built on ASP.NET, Visual BI leverages the open-source Serenity web framework based on ASP.NET Core 8.0. It offers a comprehensive suite of features, including data analysis components that display interconnected data in various formats such as grids, charts, maps, gauges, and more. Enjoy the convenience of automatic layout adjustments, allowing you to visualize complex data effortlessly. Seamlessly manage and analyze your data with precision, ensuring insightful and actionable intelligence. Experience the future of data visualization with Visual BI – your ultimate tool for analytical excellence.

**URL of the content**
[ASP.NET Core Online Dashboard Designer](https://www.youtube.com/watch?v=1sZoJ53Qocw) 

**Copy for the content**
Welcome to Visual BI, an ASP.NET-based Online Dashboard Designer using the open-source Serenity framework (ASP.NET Core 8.0). It offers advanced features to display data in grids, charts, maps, and more, with automatic layout adjustments for effortless visualization. Your ultimate tool for analytical excellence

**Date requested**
Friday 14, June 2024. 

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
![image](https://github.com/dotnet-foundation/content/assets/2275051/0102b960-6605-4e1c-bd47-11b20152fc3c)

**Comment by ddskier** [comment]
This is scheduled for Friday, June 14 on all social channels
