### ISSUE TITLE
[AMPLIFICATION] - Orchard Harvest 2024

### ISSUE THREAD

**Issue by viktoriamagyar** [dotnet-foundation/content#265]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
Yes

**Please describe the content.**
My college Zoltán Lehóczky is one of the maintainers of the .NET Foundation project Orchard Core. In September, we'll have our next community conference, Orchard Harvest, in Las Vegas: https://orchardcore.net/harvest. For this, we'd appreciate support from you to get the word out there.
The Orchard Harvest conference will be in Las Vegas, on September 12th and 13th 2024.
Just like [the last Harvest](https://orchardcore.net/harvest-2023), it’s going to be a great opportunity to share knowledge, talk about development plans and ideas, and foremost, meet the rest of the worldwide community. During these two days, participants will have the chance to dive deep into Orchard Core development, learn best practices, and engage with other experts. Furthermore, there are hands-on coding sessions in the pipeline to elevate their skill set!

**Copy for the content**
Suggested copy you want to use for the social post. Please keep in mind the channel limitations (i.e. x/Twitter 280 characters)

Join us for Orchard Harvest Conference 2024 in vibrant Las Vegas on September 12th and 13th at the Orleans Hotel and Casino!
Get ready for two days filled with learning, coding, and connecting with the worldwide Orchard community.

During these two days, you'll have the chance to dive deep into Orchard Core development, learn best practices, and engage with other experts.
Can't wait until September? Check out recordings from last year's special online Orchard Harvest on our YouTube channel [here](https://www.youtube.com/playlist?list=PLpCsCyd254Fr-2gbJEOLAJaoU_4EqHKaI).

But that's not all! As a participant, you'll enjoy exclusive access to discounted accommodations at the Orleans Hotel and Casino.

Harvest 2024 still has a few places for dynamic speakers as well to share their expertise with our community. Apply until the 29th of June to be a part of this transformative event!
Register Here: [https://forms.office.com/pages/responsepage.aspx...](https://forms.office.com/pages/responsepage.aspx?id=Wt6elek45kStyIVVO-uCICDdeeZFbXdAlSWTkdgpZAtUQTJHWEQzSkg4WjRVOEFGUkpBWFlFMTM4QS4u)

This Year's Leading Themes:

1. Leading Up to a v3.0: The Future of OC
- How will the future OC look like?
2. The Role of a CMS nowadays
- Decoupled/headless operating models
- AI development tools
3. Explore some advanced Topics
- Shapes
- Placements
- Cloud Integrations
- Performance
- Module Extensibility
4. Showcases
- Real-world implementations of OC in action.

Ready to be a part of something extraordinary? Reserve your spot today and take advantage of early bird pricing.

Don't miss this opportunity to connect with like-minded professionals. 
You can find all the important details at [https://orchardcore.net/harvest](https://orchardcore.net/harvest)

**Twitter:**Registration for the Orchard Harvest 2024 conference is open. This will be held in Las Vegas NV, on Sept. 12 & 13 2024. Find more about tickets, speaker opportunities, and programs at https://orchardcore.net/harvest
#OrchardHarvest2024

**Date requested**
17th of June or as soon as possible

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
-

**Comment by ddskier** [comment]
This is scheduled for June 18 and will repeat June 26

**Comment by viktoriamagyar** [comment]
Thank you!

Viktória Magyar
Business developer
Lombiq Technologies Ltd.
https://lombiq.com
[https://lombiqstatic.com/Themes/Lombiq.Theme/Images/lombiq-email-signature-logo.png?2020]<https://lombiq.com>
Please note that we store your personal data in accordance with our privacy policy<https://lombiq.com/privacy-policy>, but you can anytime choose to withdraw your previous consent by writing to ***@***.***


________________________________

**Comment by viktoriamagyar** [comment]
@ddskier Hi! Sorry, I had to modify the links in the post. Cloud you, please reshare it with the right links? Thank you ver much!

**Comment by ddskier** [comment]
Hi, no problem. Which links changed?

**Comment by viktoriamagyar** [comment]
Hi! 
These are the links. I copied them from the wrong place. Is it clear in this way?

"our YouTube channel [here](https://www.youtube.com/playlist?list=PLpCsCyd254Fr-2gbJEOLAJaoU_4EqHKaI)."
"Register Here: [https://forms.office.com/pages/responsepage.aspx...](https://forms.office.com/pages/responsepage.aspx?id=Wt6elek45kStyIVVO-uCICDdeeZFbXdAlSWTkdgpZAtUQTJHWEQzSkg4WjRVOEFGUkpBWFlFMTM4QS4u)"
"important details at https://orchardcore.net/harvest"

**Comment by ddskier** [comment]
I made the changes

**Comment by viktoriamagyar** [comment]
Thank you!
