### ISSUE TITLE
[AMPLIFICATION] - .NET & AI Community Talks

### ISSUE THREAD

**Issue by bigebesikci** [dotnet-foundation/content#267]
**Are you a .NET Foundation Member**
Yes

**Please describe the content.**
Hey there,
We are organizing a new episode of ABP Community Talks in which Luis Quintanilla will be with us to talk about .NET & AI.
This could be an interesting and a trending topic for the .NET Community, so I think sharing with .NET Foundation community would be very beneficial for the audience.

Thank you so much!

**URL of the content**
https://kommunity.com/volosoft/events/abp-community-talks-20242-net-ai-c6530dfc

**Copy for the content**
"📢 Last 3 Days to ABP Community Talks 2024.2!
Join us to learn about .NET and AI with @ljquintanilla and @engincanveske
🗓️ on June 27th, 2024 at 17:00 UTC.

Register from 👉 https://kommunity.com/volosoft/events/abp-community-talks-20242-net-ai-c6530dfc
#dotnet #abpframework #ai #ABPCommunityTalks"
_--- To be posted on Twittter/X: on June 24th, 2024_

"📢 Last 3 Days to ABP Community Talks 2024.2!
Join us to learn about .NET and AI with Luis Quintanilla and Engincan Veske
🗓️ on June 27th, 2024 at 17:00 UTC.

Register from 👉 https://kommunity.com/volosoft/events/abp-community-talks-20242-net-ai-c6530dfc
#dotnet #abpframework #ai #ABPCommunityTalks"
_--- To be posted on LinkedIn & Facebook: on June 24th, 2024_

"🎉 Today is the day!
ABP Community Talks 2024.2 is TODAY at 17:00 UTC!
To learn about the .NET & AI with @ljquintanilla and @engincanveske:
Register from 👉 https://kommunity.com/volosoft/events/abp-community-talks-20242-net-ai-c6530dfc
Watch from 👉  https://www.youtube.com/watch?v=JiykJsLd12E
#dotnet #abpframework #ai #ABPCommunityTalks"
_--- To be posted on June 27th (before 5 PM UTC): on Twitter/X_

"🎉 Today is the day!
ABP Community Talks 2024.2 is TODAY at 17:00 UTC!
To learn about the .NET & AI with Luis Quintanilla and Engincan Veske:
Register from 👉 https://kommunity.com/volosoft/events/abp-community-talks-20242-net-ai-c6530dfc
Watch from 👉  https://www.youtube.com/watch?v=JiykJsLd12E
#dotnet #abpframework #ai #ABPCommunityTalks"
_--- To be posted on June 27th (before 5 PM UTC): on LinkedIn & Facebook_ 

**Date requested**
The one with "Last 3 Days": on June 24th, 2024
The one with "Today": on June 27th, 2024 (before 5 PM UTC)

**Channel requested**
X/Twitter
LinkedIn 
Facebook

**Additional context**
![1200_628](https://github.com/dotnet-foundation/content/assets/78538870/fdd2c86c-943b-41b5-8073-446347312a6f)

**Comment by ddskier** [comment]
This is scheduled for requested days on all social channels
