### ISSUE TITLE
[AMPLIFICATION] - JetBrains State of Developer Ecosystem Survey 2024

### ISSUE THREAD

**Issue by maartenba** [dotnet-foundation/content#269]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
JetBrains is starting its 8th annual State of Developer Ecosystem survey, which polls for developers insights. Results are shared typically around October/November, followed by raw data for others to analyze as well.

**URL of the content**
https://surveys.jetbrains.com/s3/nf-developer-ecosystem-survey-2024

**Copy for the content**
What’s shaping the future of code development? @JetBrains has opened its State of Developer Ecosystem survey, and you can win fabulous prizes for taking part. Follow the link to share your insights: https://surveys.jetbrains.com/s3/nf-developer-ecosystem-survey-2024

**Date requested**
Once or twice in June/July timeframe.

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Comment by ddskier** [comment]
Posted it today and repeating twice more in July. Posting to all social channels
