### ISSUE TITLE
[AMPLIFICATION] - JetBrains .NET Day Online 2021 Call for Speakers

### ISSUE THREAD

**Issue by maartenba** [dotnet-foundation/content#27]
**Please describe the content.**
JetBrains is organizing their third .NET Day Online on May 12, 2021. It is a free virtual event where community speakers cover topics they are passionate about, ranging from deep technical .NET content and speakers’ experiences with specific tools and technologies, to personal development.

They are looking for speakers interested in presenting, and welcome all topics that would be relevant to the wider .NET community, a great opportunity for .NET Foundation members who aspire to deliver a session.

**URL of the content**
https://blog.jetbrains.com/dotnet/2021/02/15/jetbrains-net-day-online-2021-call-for-speakers/?utm_source=newsletter&utm_medium=referral&utm_campaign=resharper&utm_content=dnf2021-02

**Copy for the content**
Totally happy with a retweet (or copy/paste) of: https://twitter.com/resharper/status/1361329006172397575

**Date requested**
Week of Feb 22 or week of March 1, 2021, what best fits your content schedule.

**Channel requested**
Twitter

**Comment by BethMassi** [comment]
@ddskier can you schedule this for next week?

**Comment by ddskier** [comment]
Will do!

**Comment by ddskier** [comment]
I retweeted the current tweet and will repeat on Mar 1

**Comment by ddskier** [comment]
Meant to close this - retweeted this and repeating on Monday, Mar 1.

**Comment by maartenba** [comment]
Thanks folks! 🥇
