### ISSUE TITLE
[AMPLIFICATION] - DotEnv.Core 3.1.0 released

### ISSUE THREAD

**Issue by DevD4v3** [dotnet-foundation/content#271]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
**DotEnv.Core** is a .NET library for reading and parsing .env files. It also provides a mechanism to retrieve the value of an environment variable in a simple and easy way.

**URL of the content**
https://github.com/MrDave1999/dotenv.core

**Copy for the content**
> DotEnv.Core 3.1.0 released 🚀 🍰
>
> A library .NET for reading and parsing .env files.
> https://github.com/MrDave1999/dotenv.core #dotnet #csharp #oss #env #dotenv

**Date requested**
As soon as convenient.

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Comment by DevD4v3** [comment]
@ddskier

**Comment by ddskier** [comment]
oh dang, sorry. Been on the road a lot so missed this. This will post on July 15 and repeat July 24. Will post to all social channels
