### ISSUE TITLE
[AMPLIFICATION] - Unhandled Exception Podcast episode 68 - Modular Monoliths - with Steve "ardalis" Smith

### ISSUE THREAD

**Issue by dracan** [dotnet-foundation/content#273]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
This is for the next Unhandled Exception podcast episode, which is a podcast mostly about .NET and .NET projects/technologies.

**URL of the content**
https://unhandledexceptionpodcast.com/posts/0068-modularmonolithswithardalis/

**Copy for the content**

Twitter:
The next #UnhandledException podcast episode has now dropped! @dracan was joined by Steve Smith (@ardalis) to chat about Modular Monolith architectures in #dotnet! 🔥🎙️
https://unhandledexceptionpodcast.com/posts/0068-modularmonolithswithardalis/

Others:
The next #UnhandledException podcast episode has now dropped! Dan was joined by Steve "ardalias" Smith to chat about Modular Monolith architectures in #dotnet! 🔥🎙️
https://unhandledexceptionpodcast.com/posts/0068-modularmonolithswithardalis/

**Date requested**
Whenever works best for you :)

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
Add any other context or screenshots about the request here.

For the LinkedIn post, could you add a link at the bottom to my LinkedIn profile? (https://www.linkedin.com/in/danclarkeuk)

Also, here's a graphic for social media posts...

![0068-ModularMonolithsWithArdalis](https://github.com/dotnet-foundation/content/assets/567988/b3e96877-ab15-4521-8c2f-0210fcf0f72e)

**Comment by ddskier** [comment]
This is scheduled for July 10 and repeats on July 22 on all social channels
