### ISSUE TITLE
[AMPLIFICATION] - Summer Of Craft Book "Growing together"

### ISSUE THREAD

**Issue by ythirion** [dotnet-foundation/content#274]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
We are launching a summer holiday workbook around Software Craftsmanship called the Summer Craft Book.
Each week, a specific theme is going to be examined like **Object Calisthenics**, **Command Query Separation**, **Test-Driven Development**, **Legacy Code Refactoring**, **Property-Based Testing**. 

You will have information, theory, exercises, games and resources to go further.
Set aside a couple of hours a week to work on the subject.
If you happen to have more time, a coding version will be available so you can dig into each exercise a bit longer.
We wouldn't want your craft skills to go to waste !

**URL of the content**
https://github.com/advent-of-craft/2024-summer-craft-book

**Copy for the content**
🌞 Your vacations are about to take a new turn!
🌴🏖️ Chilling on the beach and sipping cocktails is great, but imagine the thrill of coding while enjoying the sun!
🎉 Get ready for this year's edition of the Summer Craft Book! 

Dive into a unique workbook designed to blend relaxation and learning, tailored for software enthusiasts.
Our Book offers engaging coding challenges in C#, insightful articles, and practical exercises to sharpen your skills while you unwind.

**Date requested**
07/12

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
It is totally free and Open Source 👍 
![summer-craft-book](https://github.com/dotnet-foundation/content/assets/20967693/1f48dbe1-aabe-4af1-a65a-2e5a03f0eed6)

**Comment by ddskier** [comment]
Scheduled for July 12 on all social channels
