### ISSUE TITLE
[AMPLIFICATION] - Multithreading in Blazor WASM using Web Workers

### ISSUE THREAD

**Issue by KristofferStrube** [dotnet-foundation/content#276]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
The .NET Foundation should amplify this content because it gives insight into what options Blazor developers have for multithreaded work in Blazor WASM which is not possible out of the box.

**URL of the content**
https://kristoffer-strube.dk/post/multithreading-in-blazor-wasm-using-web-workers/

**Copy for the content**
Are you doing CPU heavy work in your Blazor WASM applications? Then, you might want to read this article, which gives an overview of some of the options you have for writing multithreaded code in Blazor WASM using Web Workers.
#dotnet #blazor

**Date requested**
Not important.

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
-

**Comment by ddskier** [comment]
Scheduled for July 29 on all social channels
