### ISSUE TITLE
[AMPLIFICATION] -  SemanticKernel.Connectors.Oracle

### ISSUE THREAD

**Issue by Giorgi** [dotnet-foundation/content#278]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
The .NET Foundation should amplify this content because it is a new connector for Semantic Kernel.

**URL of the content**
https://github.com/Giorgi/SemanticKernel.Connectors.Oracle

**Copy for the content**
Introducing Semantic Kernel memory for Oracle. Oracle 23ai added a new vector type and vector search capabilities to the database engine, and this connector for Semantic Kernel builds on top of it. You can now store and filter vector embeddings in the Oracle database when using Semantic Kernel.

**Date requested**
As soon as possible

**Channel requested**
All

**Comment by ddskier** [comment]
Scheduled for July 31 on all social media channels
