### ISSUE TITLE
[AMPLIFICATION] - OSS Power-Ups on .NET Foundation YouTube Channel

### ISSUE THREAD

**Issue by matkoch** [dotnet-foundation/content#28]
**Please describe the content.**
We're hosting a series called "OSS Power-Ups", where we draw some light on various great .NET OSS projects. So far we had FluentValidation and FluentAssertions on the show. With the next episode, we'd like to start streaming to the DNF channel as well, to extend our reach. The next episode will be about [Snoop](https://github.com/snoopwpf/snoopwpf), but actually we'd like to make this a regular procedure, and I'm basically asking here for how that should work.

**URL of the content**
The upcoming episode is announced here: https://info.jetbrains.com/resharper-webinar-april-2021.html

**Date requested**
27 April 16:00 CEST

**Channel requested**
.NET Foundation YouTube Channel

**Additional context**
I gave a proper introduction to the format in the episode with FluentValidation: https://www.youtube.com/watch?v=ePrWPblO-H4

**Comment by DaveNoderer59** [comment]
The Virtual User Group can stream your event through Streamyard onto the dnf youtube. If you submit  your request to : https://forms.microsoft.com/Pages/ResponsePage.aspx?id=3G8HFsH8FUqxyjLJolWQDu3r3uMrwH1HjiQupxbALB5UODc4UllaTjQ2MzkzMjlRR1RYMjBMMTJHNy4u 
it will get to the right group. Your content looks useful. Are you running a community group / meetup as well?

**Comment by matkoch** [comment]
@DaveNoderer59 we already have access to the DNF channel account. As noted, this question is more about the general procedure. We have a webinar once a month, and creating an issue each time doesn't sound very efficient. I guess it's foremost up to @clairernovotny or @ddskier to clarify.

**Comment by matkoch** [comment]
Followed up with #30
