### ISSUE TITLE
[AMPLIFICATION] - ReSharper 20th Birthday

### ISSUE THREAD

**Issue by matkoch** [dotnet-foundation/content#281]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
Hi! Just asking if you could do a retweet on the following tweet.

Much appreciated! :)

**URL of the content**
https://x.com/resharper/status/1815764643761053797

**Copy for the content**
```
ReSharper turns 20! Can you imagine that? 🥳

Join us in reflecting on how 
[@ReSharper](https://x.com/resharper)
 has transformed the [#dotnet](https://x.com/hashtag/dotnet?src=hashtag_click) community over the years, and revisit some good old memes and stories about ReSharper IDE: [https://jb.gg/resharper-20](https://t.co/zQn18GGZDT)

What’s your ReSharper story? [#20YearsOfReSharper](https://x.com/hashtag/20YearsOfReSharper?src=hashtag_click)
```

**Date requested**
At your convenience.

**Channel requested**
X/Twitter

**Comment by ddskier** [comment]
Done
