### ISSUE TITLE
[AMPLIFICATION] - Unhandled Exception Podcast episode 69 - The Umbraco CMS and Community

### ISSUE THREAD

**Issue by dracan** [dotnet-foundation/content#282]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
This is for the next Unhandled Exception podcast episode, which is a podcast mostly about .NET and .NET projects/technologies. This one is about the Umbraco CMS and its Community.

**URL of the content**
https://unhandledexceptionpodcast.com/posts/0069-umbraco/

**Copy for the content**

Twitter: In the latest #UnhandledException podcast episode, @dracan was joined by @carlcod_es, @lottepitcher, @crgrieve, and @callumbwhyte to chat about the #Umbraco CMS, and its amazing community!
https://unhandledexceptionpodcast.com/posts/0069-umbraco/ #dotnet

Others: In the latest #UnhandledException podcast episode, Dan was joined by Carl Sargunar, Lotte Pitcher, Carole Rennie Logan, and Callum Whyte to chat about the #Umbraco CMS, and its amazing community!
https://unhandledexceptionpodcast.com/posts/0069-umbraco/ #dotnet

Carl Sargunar, Lotte Pitcher, Carole Rennie Logan, and Callum Whyte, to discuss the Umbraco community and CMS!

**Date requested**
When suits you best :)

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**

For the LinkedIn post, could you add a link at the bottom to my LinkedIn profile? (https://www.linkedin.com/in/danclarkeuk)

![0069-Umbraco](https://github.com/user-attachments/assets/d9ffbd69-f767-485f-875a-812f22b7d264)

Thank you 🙂🙏
Dan

**Comment by ddskier** [comment]
Set for Monday, Aug 12 on all social channels

**Comment by dracan** [comment]
Amazing - thank you @ddskier 🙂🙏
