### ISSUE TITLE
[CREATION] - Orchard Harvest Conference

### ISSUE THREAD

**Issue by viktoriamagyar** [dotnet-foundation/content#285]
**Please describe the content you want to create.**
We would like to ask you to promote our event, which will be the biggest Orchard Core event of the year. We would like to reach as many developers as possible.

**About Orchard Core and Orchard Harvest**
Orchard Core is an open-source, modular, and multi-tenant application framework and CMS built on ASP.NET Core. We like it as developers because it's a feature-rich foundation to build modern .NET web apps on.
Orchard Harvest is the annual gathering of the Orchard Core community, with entry-level and hardcore technical talks, a review of where we are, a panel, and a hackathon.

**Why should you participate?**
You can attend exciting presentations by experienced Orchard Core users and ask your questions live, as we have organized Q&A sessions within the program.
You'll also have plenty of opportunities to meet and network with technology experts and frequent users, including a panel discussion on today's most trending topics.
Make your .NET web developer team more productive with a standardized framework and CMS, and stop reinventing the wheel (we already have reinvented it :)). Harvest is the most engaging way to start with Orchard Core.

**Early Bird Offer**
You can get tickets at an early bird discount until the 15th of August.

**Event Details**
Location: Las Vegas, The Orleans Hotel & Casino
Dates: 12th and 13th of September, 2024

For more details and to register, please visit our [Orchard Harvest 2024](https://orchardcore.net/harvest) page
We would love to meet fellow .NET teams in person at Orchard Harvest 2024.

**Target date**
As soon as possible.

**Channel requested**
Blog, Website, Social Platforms

**Additional context**
![Flyer](https://github.com/user-attachments/assets/f79cbf7c-0284-4196-8171-3b2a5a81806d)

**Comment by ddskier** [comment]
Scheduled for Aug 20 on all social channels
