### ISSUE TITLE
[AMPLIFICATION] - JetBrains .NET Days Online

### ISSUE THREAD

**Issue by maartenba** [dotnet-foundation/content#29]
**Please describe the content.**
For the third time, JetBrains are organizing [JetBrains .NET Days Online](https://pages.jetbrains.com/dotnet-days-2021/dnf) - a free virtual event that will take place on May 11–12, 2021. Community speakers present topics they are passionate about. You can expect a variety of levels of technical content, and speakers may also share their personal experiences and development.

The topics on this year’s agenda include C#, F#, GraphQL, Blazor, gRPC, Hedy, working with databases, and debugging. On top of that, we’ll discuss stereotypes around legacy code and demonstrate how to build a React app backed with Azure features.

We have .NET Foundation listed as a community partner, and will mention you folks back in our tweets etc. 

More info: https://pages.jetbrains.com/dotnet-days-2021/dnf

**URL of the content**
https://twitter.com/resharper/status/1382309745583882242 (or https://pages.jetbrains.com/dotnet-days-2021/dnf if not retweeting)

**Copy for the content**
Feel free to retweet https://twitter.com/resharper/status/1382309745583882242

or use the following:

```
Join a free virtual event, JetBrains .NET Days Online, on May 11 and 12

🎙️Topics: #csharp, #fsharp, GraphQL, Blazor, gRPC, Hedy, and more! 
👉Save your seat: https://pages.jetbrains.com/dotnet-days-2021/dnf

 #dotnet #JBDotNetDays
```

**Date requested**
Before end of April, 2021

**Channel requested**
Facebook, Twitter

**Comment by ddskier** [comment]
I retweeted your Tweet. I'm repeating on all foundation social channels (Twitter, FB, LinkedIn) on April 16 and 21.
