### ISSUE TITLE
[AMPLIFICATION] - Unhandled Exception Podcast episode 70 - Naming things is hard! With Nick Cosentino

### ISSUE THREAD

**Issue by dracan** [dotnet-foundation/content#291]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**

This is for the next Unhandled Exception podcast episode, which is a podcast mostly about .NET and .NET projects/technologies.”

**URL of the content**
https://unhandledexceptionpodcast.com/posts/0070-namingthingsishard/

**Copy for the content**

Twitter:

The next #UnhandledException podcast is now out! In it, @dracan was joined by @DevLeaderCa to chat about code refactoring. They also chatted about testing, and how AI might affect us as developers.
https://unhandledexceptionpodcast.com/posts/0070-namingthingsishard/
#dotnet #refactoring #tdd

Others:

The next #UnhandledException podcast is now out! In it, Dan was joined by Nick Cosentino to chat about code refactoring. They also chatted about testing, and how AI might affect us as developers.
https://unhandledexceptionpodcast.com/posts/0070-namingthingsishard/
#dotnet #refactoring #tdd

**Date requested**
Whenever best suits you :)

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**

For the LinkedIn post, could you add a link at the bottom to my LinkedIn profile? (https://www.linkedin.com/in/danclarkeuk)

Also, here's the promo image...

![0070-NamingThingsIsHard](https://github.com/user-attachments/assets/94c26384-6748-4e93-982d-5b94bd50d391)

Thank you 🙂🙏
Dan

**Comment by ddskier** [comment]
Scheduled for Sept 4 on all social channels

**Comment by dracan** [comment]
Thanks @ddskier 😊🙏
