### ISSUE TITLE
[AMPLIFICATION] - League of Legends Client on Uno

### ISSUE THREAD

**Issue by mtmattei** [dotnet-foundation/content#296]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
 it showcases a significant project by @jamesnet3588: a League of Legends client built with the Uno Platform. It demonstrates how WPF skills can be extended to cross-platform development, providing valuable insights into modular design, CustomControls, and scalable architecture. It’s a key resource for developers looking to bridge desktop and cross-platform applications.

**URL of the content**
https://x.com/jamesnet214/status/1835833844144222338

**Copy for the content**
We are thrilled to spotlight @jamesnet214 latest project—a League of Legends client developed with Uno Platform. This project is a perfect example of how to transition from WPF to cross-platform development.

- Helps WPF developers leverage their existing skills in cross-platform development.
- Showcases modular structures, CustomControls, and scalable architecture.
- Demonstrates Uno’s powerful features and provides insights into XAML-based framework design.
- Open-source repo

![image](https://github.com/user-attachments/assets/f56a013d-dd67-4770-9aa2-51eaf2c3db21)

Check out the League of Legends Uno-Platform project[LINK}

**Date requested**
9/19/24

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Scheduled for 9/19 on all social channels
