### ISSUE TITLE
Veritas API Gateway release

### ISSUE THREAD

**Issue by VeritasSoftware** [dotnet-foundation/content#298]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
Yes. Seed category project.

**Please describe the content.**
A clear and concise description of what the content is and why it's important to the .NET open source community. Ex. The .NET Foundation should amplify this content because it provides news about a .NET Foundation new project release [...]

The content is a new release of the Veritas API Gateway project supporting .NET 8.

**URL of the content**
Link to the article, blog, video, social post, presentation, etc. 

https://github.com/VeritasSoftware/AspNetCore.ApiGateway

**Copy for the content**
Suggested copy you want to use for the social post. Please keep in mind the channel limitations (i.e. x/Twitter 280 characters)

Veritas API Gateway has released a new version (4.4.0) which supports .NET 8. So now, .NET 6/7/8 are supported. Also, features to create new default HttpClient to hit back-end routes, replacement of Newtonsoft.json with System.Text.Json etc. are now available.

**Date requested**
The date you are requesting us to amplify. We will try to hit that if approved. 

1st Oct 2024

**Channel requested**
X/Twitter
LinkedIn
Facebook

All channels.

**Additional context**
Add any other context or screenshots about the request here.
![image](https://github.com/user-attachments/assets/94c07e1f-a645-46f8-8009-dc541582aa81)

**Comment by ddskier** [comment]
Scheduled for Oct 2 on all social channels. I would have done Oct 1 but someone else already requested that date.

**Comment by VeritasSoftware** [comment]
@ddskier 

another feature added is the ability to vary response caching duration for each route (apiKey/routeKey).
the released version is 4.5.0
