### ISSUE TITLE
[AMPLIFICATION] - Stop building CRUD API's, use Data API Builder instead!

### ISSUE THREAD

**Issue by sander1095** [dotnet-foundation/content#299]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
This posts teaches the user about a new Microsoft project called Data API Builder. This allows a developer to generate an API with REST and GraphQL endpoints based on their database schema, **in seconds**! This speeds up the development process and leaves a developer with more time to work on more fun and engaging challenges!

Data API Builder is a useful tool for any developer's toolbox and contains tons of features that developers would normally spend lots of time creating themselves.

**URL of the content**
https://stenbrinke.nl/blog/data-api-builder-introduction/

**Copy for the content**
Tired of building CRUD API's? We often spend lots of time building them, which can be repetitive and sometimes even boring!

**Twitter**
Fortunately, this is no longer necessary thanks to Microsoft's Data API Builder, which generates the API for you! Read this post to learn all about it!

**LinkedIn**
Fortunately, this is no longer necessary thanks to Microsoft's Data API Builder, which generates the API for you! @sandertenbrinke teaches you all about it in his latest post!

**Date requested**
As soon as possible!

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
On LinkedIn, please tag me in the description, so users can navigate to my profile. If not possible, please replace `@sandertenbrinke` with "Sander ten Brinke"

**Comment by ddskier** [comment]
Scheduled for Oct 3 on all social channels
