### ISSUE TITLE
[AMPLIFICATION] - Containerizing Blazor Apps

### ISSUE THREAD

**Issue by JeremyMorgan** [dotnet-foundation/content#3]
**Please describe the content.**
The .NET Foundation should amplify this content because it's a quick tutorial to show how to put Blazor apps in containers, that helps productivity and helps people understand the difference between Blazor WebAssembly and Blazor Server applications. 

**URL of the content**
https://www.pluralsight.com/tech-blog/containerizing-blazor-apps/

**Copy for the content**
If you want to publish your Blazor applications in containers there are some things to know, and this tutorial takes you step by step through the process. 

**Date requested**
2/14/2020 

**Channel requested**
Facebook, Twitter

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
This is approved and is scheduled for 2/14/2020 at 6:15AM PST
