### ISSUE TITLE
[AMPLIFICATION] - JetBrains 2021.1 Release Party for ReSharper and Rider

### ISSUE THREAD

**Issue by matkoch** [dotnet-foundation/content#30]
**Please describe the content.**
We're hosting another release party for ReSharper / Rider 2021.1

**URL of the content**
https://www.youtube.com/watch?v=-Sj1l1fHeI0

**Copy for the content**
```
Our friends at @jetbrains are having their 2021.1 release party for ReSharper and Rider. Take a seat and enjoy! 🥳

⏰ April 26, 5pm CEST / 8am PDT
🗣 All the advocates 🥑
🤔 Bring all your questions!

https://www.youtube.com/watch?v=-Sj1l1fHeI0
```

**Date requested**
Preferably until 20 April, and maybe another time on the exact date.

**Channel requested**
Facebook, Twitter

**Comment by ddskier** [comment]
I retweeted your tweet already and I scheduled for Apr 19 and repeating on Apr 26 prior to the event.
