### ISSUE TITLE
[AMPLIFICATION] - Net Solution Analyzer

### ISSUE THREAD

**Issue by ignatandrei** [dotnet-foundation/content#300]
**Are you a .NET Foundation Member**
Yes		

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
PackageAnalyzer is a .NET Tool that make a (relative ) short summary for any   C#  solution .

If you are new to the solution you can see the relation between projects, the root projects, the projects with least classes.

If you want to improve the porjects, you can see cyclomatic complexity, class coupling, maintainability score,packages with major version different and more.

Here is PackageAnalyzer analyzing himself
https://ignatandrei.github.io/PackageAnalyzer/NetPackageAnalyzer_summary.html

**URL of the content**
https://github.com/ignatandrei/packageAnalyzer/

**Copy for the content**
Analyze any C# solution with packageAnalyzer .

**Date requested**
Does not matter

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
![image](https://github.com/user-attachments/assets/1c7029ea-7374-4b99-bb3e-29ed5662cd55)

**Comment by ddskier** [comment]
Scheduled for Oct 8 on all social channels
