### ISSUE TITLE
[AMPLIFICATION] - Announce JetBrains as our new sponsor

### ISSUE THREAD

**Issue by nicoleabuhakmeh** [dotnet-foundation/content#302]
**Is this for promoting a .NET Foundation Sponsor**
Yes

**Date Requested**
October 24, October 28

**Please describe the content.**

Announcement for X/Twitter, Including Logo:
📢 Exciting News! 🎉 Thrilled to announce that @JetBrains has joined forces with the .NET Foundation as our newest sponsor! 🤝 Together, we're empowering developers and advancing the world of #dotNET. 🚀 Thank you,  JetBrains, for your invaluable support! #techcommunity #sponsorship

Announcement for Facebook, Including Logo: 
📢 Exciting News! 🎉 We are thrilled to announce that [JetBrains](https://www.jetbrains.com/) has joined the .NET Foundation as a sponsor! Their commitment to supporting the development of open source technology is truly inspiring, and we look forward to working together to continue advancing the .NET ecosystem. Welcome to the team,  JetBrains! #dotNETFoundation #opensource #technology

Announcement for LinkedIn, Including Logo:
🎉 Exciting News! 🎉
We are thrilled to announce that [JetBrains](https://www.jetbrains.com/) has joined forces with the .NET Foundation as our newest sponsor! 🚀

“We strongly believe in the importance and power of the .NET ecosystem. For over 20 years, JetBrains has been dedicated to developing best-in-class products for .NET and game developers, beginning with ReSharper,” says Matt Ellis, .NET Developer Advocacy Team Lead at JetBrains.

“We also recognize the significance of a thriving community – not only in open source, but also through meetups, conferences, and content. The .NET Foundation has the scope and influence to help nurture this community, and we are proud to support the volunteers who drive this mission.

In addition to providing complimentary JetBrains licenses to active open-source projects, we launched the [OSS Power-Ups](https://lp.jetbrains.com/oss-powerups/) initiative to spotlight .NET open-source projects and give their maintainers a platform to raise awareness about their work.”

We extend a warm welcome to JetBrains and express our gratitude for their support and commitment. We're excited about the opportunities that lie ahead and the remarkable projects that will emerge from this collaboration.

If you haven't already, make sure to follow [JetBrains](https://www.jetbrains.com/) and the .NET Foundation on LinkedIn to stay up to date with the latest news, events, and initiatives. Let's celebrate this new partnership and continue building an extraordinary future for the .NET community!
#DotNETFoundation #Partnership #Collaboration #Innovation #OpenSource #SoftwareDevelopment

**Comment by ddskier** [comment]
Hey Nicole, you said "including logo". Am I supposed to include the .NET Foundation logo?

**Comment by nicoleabuhakmeh** [comment]
Thanks DeeDee, sorry!  We can download the JetBrains logo from https://www.jetbrains.com/company/brand/

**Comment by ddskier** [comment]
Set for Oct 24 and Oct 28 on all social channels
