### ISSUE TITLE
[AMPLIFICATION] - Unhandled Exception Podcast episode 72 - Unhandled Exceptions - With Callum Linington

### ISSUE THREAD

**Issue by dracan** [dotnet-foundation/content#303]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
This is for the next Unhandled Exception podcast episode, which is a podcast mostly about .NET and .NET projects/technologies.

**URL of the content**
https://unhandledexceptionpodcast.com/posts/0072-exceptions/

**Copy for the content**
Twitter:
In the latest episode of the #UnhandledException podcast, @dracan was joined by @No1Melman to chat about all the things wrong with exceptions! And more importantly, what you can use instead. And yeah, they used the term "monad"! 🙈
https://unhandledexceptionpodcast.com/posts/0072-exceptions/ #dotnet

Others:
In the latest episode of the #UnhandledException podcast, Dan was joined by Callum Linington to chat about all the things wrong with exceptions! And more importantly, what you can use instead. And yeah, they used the term "monad"! 🙈
https://unhandledexceptionpodcast.com/posts/0072-exceptions/ #dotnet

**Date requested**
Up to you :)

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**

For the LinkedIn post, could you add a link at the bottom to my LinkedIn profile? (https://www.linkedin.com/in/danclarkeuk)

Thank you 🙂🙏
Dan

Also, here's a graphic for social media posts...

![image](https://github.com/user-attachments/assets/e293381b-6f6d-4393-a9b9-1c770b8e4efa)

**Comment by ddskier** [comment]
Scheduled for Oct 21 on all social channels
