### ISSUE TITLE
[AMPLIFICATION] - Advent Of Craft 2024 "Growing together"

### ISSUE THREAD

**Issue by ythirion** [dotnet-foundation/content#305]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
The Advent Of Craft 2024 Edition is Here to Save Santa! 🚨 🚀🎄

Adventers, Developers, Crafters, Tech Leads, and all technical enthusiasts – are you ready for the ultimate holiday coding adventure? 
This year, the Advent Of Craft team invites you on a mission to save Santa!

Immerse yourself in the spirit of Christmas through an engaging, byte-sized software craftsmanship experience!

🔍 What to Expect:
- 25 Exclusive Daily Challenges: Tackle unique exercises never seen before – no existing katas, ensuring fresh and innovative coding experiences every day.
- Immersive Storyline: Dive into a captivating narrative where your skills are the key to saving Christmas.
- ⁠Community Collaboration: Connect with fellow tech professionals, share your implementations and insights, and celebrate your progress together.
- ⁠External Tech Contributors: Enjoy specially crafted exercises from renowned external tech experts, bringing diverse perspectives and expertise to your coding journey.
- ⁠Support for 7 Technology Stacks: Whether you code in Java, C#, Kotlin, TypeScript, PHP, Scala, or Python, we've got you covered with tailored challenges to suit your preferred language and framework.

🎯 Why Join?
- ⁠Enhance Your Skills: Improve your software craftsmanship with hands-on, practical tasks designed to push your boundaries.
- ⁠Festive Fun: Engage in a fun and festive coding journey that fits seamlessly into your daily routine.
- ⁠Expand Your Network: Help us grow our community from 300 to over 1,000 passionate individuals, fostering connections with like-minded professionals across various tech stacks.

**URL of the content**
- [Our repository](https://github.com/advent-of-craft/2024)
- [Video explaining the event](https://www.youtube.com/shorts/5ZSryorYO8s)

**Copy for the content**
Adventers, Developers, Crafters, Tech Leads, and all technical enthusiasts – are you ready for the ultimate holiday coding adventure? 
This year, the Advent Of Craft team invites you on a mission to save Santa!

Immerse yourself in the spirit of Christmas through an engaging, byte-sized software craftsmanship experience!

**Date requested**
24/10

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
It is totally free and Open Source.

![image](https://github.com/user-attachments/assets/32b06ce0-a75e-4898-936f-0a87522842a8)

**Comment by ddskier** [comment]
This is scheduled for Oct 23 on all social channels
