### ISSUE TITLE
[AMPLIFICATION] - Free eBook: ASP.NET-FullStack-BackEnd-FrontEnd

### ISSUE THREAD

**Issue by go2ismail** [dotnet-foundation/content#306]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
Exciting news! 🎉 My book ASP.NET Core Full-Stack Web Development is now available, covering essential topics like REST API, Clean Architecture, and Vue.js for modern web development.
Feel free to check it out and share with your network to help others who might find it useful!

**URL of the content**
[Link to the article, blog, video, social post, presentation, etc. ](https://github.com/go2ismail/ASP.NET-FullStack-BackEnd-FrontEnd)

**Copy for the content**
Exciting news! 🎉 My book ASP.NET Core Full-Stack Web Development is now available, covering essential topics like REST API, Clean Architecture, and Vue.js for modern web development.
Feel free to check it out and share with your network to help others who might find it useful!

**Date requested**
Friday, 25 Oct 2024

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
![image](https://github.com/user-attachments/assets/9cb4be2e-b750-4173-9202-21fc53e659b1)

**Comment by ddskier** [comment]
Scheduled for Oct 25 on all social channels
