### ISSUE TITLE
[AMPLIFICATION] - Capture The Flag Release

### ISSUE THREAD

**Issue by DevD4v3** [dotnet-foundation/content#307]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
Capture The Flag is a game mode for [SA-MP](https://www.sa-mp.mp/) (San Andreas Multiplayer, a multiplayer mod for GTA San Andreas) created with [SampSharp](https://github.com/ikkentim/SampSharp). There are 2 flags on the map, one for each team. Players need to capture the enemy's flag and bring it back to their own one.

**URL of the content**
- GitHub: https://github.com/MrDave1999/Capture-The-Flag
- Demo: https://youtu.be/rsWCZaT4aBE

**Copy for the content**
Capture The Flag is a game mode for [SA-MP](https://www.sa-mp.mp/) (San Andreas Multiplayer, a multiplayer mod for GTA San Andreas). There are 2 flags on the map, one for each team. Players need to capture the enemy's flag and bring it back to their own one. 

**Applied concepts:**
- Hexagonal architecture
- Entity–component–system (ECS)
- Object-oriented programming

![sa-mp-000](https://github.com/user-attachments/assets/fb7642aa-2b84-430c-aa14-6f4397ed9994)
Source code: https://github.com/MrDave1999/Capture-The-Flag
Demo: https://youtu.be/rsWCZaT4aBE

**Date requested**
It's up to you

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Comment by ddskier** [comment]
Set for Oct 18 on all social channels

**Comment by DevD4v3** [comment]
@ddskier Is it November 18th?

**Comment by ddskier** [comment]
Sorry yes. Nov 18.
