### ISSUE TITLE
[AMPLIFICATION] - Retweet about test execution on CI

### ISSUE THREAD

**Issue by matkoch** [dotnet-foundation/content#31]
**Please describe the content.**
Duration of test execution is important, particularly in CI/CD environments. This tweet shows solutions to decrease test execution time on Azure DevOps and TeamCity.

**URL of the content**
https://twitter.com/nukebuildnet/status/1387807684670509056

**Copy for the content**
<Just a retweet would be nice 😃>

**Date requested**
Any time

**Channel requested**
Twitter

**Comment by matkoch** [comment]
@ddskier is there anything missing here ?

**Comment by ddskier** [comment]
Oh crap, I never saw this request for some reason. :( I just retweeted it. Sorry for the delay!

**Comment by matkoch** [comment]
Alright, no worries :D thanks!
