### ISSUE TITLE
[AMPLIFICATION] - Don't use MediatR by default on all .NET projects

### ISSUE THREAD

**Issue by pierrebelin** [dotnet-foundation/content#312]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
It's a blog post which proposes a reflection around MediatR installed by default on the projects. The article is informative and concise!

**URL of the content**
[Link to the article, blog, video, social post, presentation, etc. ](https://goatreview.com/dont-use-mediatr-by-default-net-projects/)

**Copy for the content**
🐐 Don't use MediatR by default on all .NET projects 💡

This article questions the automatic use of MediatR on .NET projects. The library is seen in its entirety in “clean code” tutorials, without presenting the complexities that this brings. This is not a criticism of MediatR, but of its systematic use.

🔗 Article: https://goatreview.com/dont-use-mediatr-by-default-net-projects/

Connect with Pierre Belin 👉 https://www.linkedin.com/in/pierre-belin/

**Date requested**
As you prefer

**Channel requested**
LinkedIn

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Scheduled for Dec 9
