### ISSUE TITLE
[AMPLIFICATION] - .NET Conf Cameroon

### ISSUE THREAD

**Issue by djoufson** [dotnet-foundation/content#313]
**Are you a .NET Foundation Member**
Yes

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
.NET Cameroon is becoming the main actor of the .NET community in Cameroon, and as the .NET Conf is launched all around the world, we also host a local .NET Conf here in Cameroon. This event follows the same philosophy of Microsoft official .NET Conf, providing developers with latest .NET content and features, according to Microsoft guidelines. Resharing this event will help us reach a larger audience and get more and more people involved.

**URL of the content**
 https://dotnetcameroon.azurewebsites.net/dotnet-conf-2024

**Copy for the content**

📢 .NET Conf Cameroon is here!

We're thrilled to announce that .NET Conf Cameroon is happening this 11th of January 2025, and we’d love for YOU to be a part of it!! Join us to explore the latest in .NET, connect with the community, and celebrate tech innovation.

Attend: <https://dotnetcameroon.azurewebsites.net/dotnet-conf-2024>
Speak: <https://forms.office.com/r/debtL0TDmA>
Sponsor: <https://forms.office.com/r/YnKLW60s73>
Let’s make this event unforgettable!

#DotNetConf #Cameroon #TechCommunity

**Date requested**
- Monday 9th December 2024
- Monday 16th December 2024
- Monday 23rd December 2024

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
<img width="1391" alt="Screenshot 2024-12-05 at 21 45 40" src="https://github.com/user-attachments/assets/43624e3f-3aa2-4120-b325-79247fea1f1a">

**Comment by ddskier** [comment]
Scheduled for the dates you requested
