### ISSUE TITLE
[AMPLIFICATION] - Meet TUnit: The New, Fast, and Extensible .NET Testing Framework

### ISSUE THREAD

**Issue by sander1095** [dotnet-foundation/content#314]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
This post introduces TUnit, a new testing framework for .NET 8 and later, and shows off its incredible speed and amazing features!

**URL of the content**
https://stenbrinke.nl/blog/tunit-introduction/

**Copy for the content**
You've probably used xUnit, NUnit or MSTest in the past for .NET tests! But have you heard of TUnit, a new testing framework .NET 8 and up? It uses source generators and supports AOT, and can be up to 2000x times faster than existing testing frameworks!

Learn about it now!

**Date requested**
ASAP, but whatever works best for the team!

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**

**Comment by ddskier** [comment]
Scheduled for Dec 17 on all social channels

**Comment by sander1095** [comment]
@ddskier could you tag me in the post on linkedin? My name is Sander ten Brinke :)

**Comment by ddskier** [comment]
I use a scheduling tool for social. I can tag you on Twitter but can't on LinkedIn. However, I added a link to your LinkedIn profile in the post.
