### ISSUE TITLE
[AMPLIFICATION] - IntelliLogo

### ISSUE THREAD

**Issue by granicz** [dotnet-foundation/content#316]
**Are you a .NET Foundation Member**
No

**Is this for promoting a .NET Foundation Project**
No

**Please describe the content.**
I would like to amplify this content because it showcases the beauty of developing web applications in F#, and can inspire more developers to use ASP.NET Core.

**URL of the content**
https://intellifactory.com/user/granicz/20241228-intellilogo

**Copy for the content**
It would be great to simply RT my original tweet - https://x.com/granicz/status/1872812685592805537 with a message to #csharp #fsharp #aspnetcore #websharper developers.

**Date requested**
As soon as you can.

**Channel requested**
X/Twitter
LinkedIn
Facebook

**Additional context**
Feel free to use this image with the amplification: https://intellifactory.com/assets/intellilogo-plant.png

**Comment by ddskier** [comment]
Retweeted and resharing on all social platforms on Jan 7

**Comment by granicz** [comment]
@ddskier Thank you!
