### ISSUE TITLE
[AMPLIFICATION] - The Virtual ML .NET Community Conference 2021

### ISSUE THREAD

**Issue by aslotte** [dotnet-foundation/content#32]
**Please describe the content.**
The Virtual ML.NET Community Conference is a 2-day free community driven conference on all things ML.NET (Machine Learning in .NET). I believe the .NET Foundation would benefit from promoting this conference as ML.NET is still very new and many developers in the .NET community has expressed interest in learning more about ML and how they can apply that in their day-to-day jobs.

**URL of the content**
https://virtualml.net

**Copy for the content**
The Virtual ML.NET Community Conference is a 2-day community driven conference on all things ML.NET. Join us this Friday and Saturday, May 7th-8th to learn more about Machine Learning in .NET!

**Date requested**
ASAP

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
Add any other context or screenshots about the request here.

**Comment by DFMERA** [comment]
Thank you for sharing, looks great! I have registered myself allready.

**Comment by ddskier** [comment]
Posting 5/4 and 5/6 on Twitter, FB, LinkedIn
