### ISSUE TITLE
Content Amplification for talk at Codegarden 2021

### ISSUE THREAD

**Issue by poornimanayar** [dotnet-foundation/content#33]
**Please describe the content.**
Codegarden is a one-of-a-kind tech conference experience organized by Umbraco - the company behind Umbraco CMS. For the first time, Codegarden goes virtual on June 9 - 12, 2021. The Umbraco CMS is currently migrating from the ASP.NET framework to the newer, faster, and better ASP.NET Core/.NET 5, with exclusive news and updates live from the virtual Codegarden stage.

**URL of the content**
https://codegarden.umbraco.com/

**Copy for the content**
Don’t miss @poornimanayar 's introduction to Blazor, GraphQL and Umbraco Heartcore
at Codegarden 2021 next Friday at 17.15 CEST. 

**Date requested**
10th June 2021, 11th June 2021

**Channel requested**
Facebook, Twitter

**Additional context**
Poornima is a .NET developer with 10+ years of experience and is both a Microsoft and Umbraco MVP. In her talk, Poornima will demonstrate how to create a SPA using Blazor and integrate it with a CMS using the GraphQL API from Umbraco Heartcore.
Codegarden is free to attend, all you need to do is sign up @ codegarden.umbraco.com!

![image](https://user-images.githubusercontent.com/3941753/120475445-43d33c00-c3a1-11eb-9b51-2527296fbcd6.png)

**Comment by ddskier** [comment]
This has been scheduled for June 10 on Twitter, LinkedIn, FB and repeats on June 11.
