### ISSUE TITLE
Umbraco CMS on .NET Core - Talk

### ISSUE THREAD

**Issue by poornimanayar** [dotnet-foundation/content#34]
**Please describe the content.**
Codegarden is a one-of-a-kind tech conference experience organized by Umbraco - the company behind Umbraco CMS. For the first time, Codegarden goes virtual on June 9 - 12, 2021. The Umbraco CMS is currently migrating from the ASP.NET framework to the newer, faster, and better ASP.NET Core/.NET 5, with exclusive news and updates live from the virtual Codegarden stage.

**URL of the content**
https://codegarden.umbraco.com/

**Copy for the content**
Join Bjarke Berg and Elitsa Marinovska from the Umbraco development team at Codegarden to hear more about the Umbraco CMS migration to .NET Core, new features in ASP.NET 5/Core and how the new Umbraco will look. 

**Date requested**
9th June, 10th June 

**Channel requested**
Facebook, Twitter

**Additional context**
The Umbraco CMS is close to its next major version, and the first on ASP.NET 5/Core. 
The migration project has been long and meticulous, bolstered by testing and contributions from the dedicated Umbraco community.

**Comment by isaacrlevin** [comment]
hey @poornimanayar sorry this was not picked up. Are there additional talks upcoming that you would like to amplify?
