### ISSUE TITLE
Content Amplification for DotVVM Virtual Conference

### ISSUE THREAD

**Issue by tomasherceg** [dotnet-foundation/content#36]
**Please describe the content.**
A two-days virtual conference focused on recent news in the DotVVM project and our future roadmap. We'll be showing Hot reload in .NET 6 and how it works with DotVVM, we have a demo of Fluent UI web components, and some other cool things.

**URL of the content**
https://www.dotvvm.com/blog/84/Join-us-on-June-21-22-at-DotVVM-Virtual-Conference-

**Copy for the content**
Have you heard about #DotVVM? It's a #MVVM framework for web, and it's really easy to use. Join the #DotVVM team - they'll be showing what's new and what they are working on. 

**Date requested**
Ideally Wednesday 6/16 or Thursday 6/17
(The conference starts on Monday 6/21 and ends on Tuesday 6/22 - if it's possible to "retweet" once again during the conference, it would be awesome)

**Channel requested**
Facebook, Twitter

**Additional context**
Official banner:
![Virtual conference_novy design-1200x670px](https://user-images.githubusercontent.com/5599524/122044739-2492d080-cddd-11eb-8782-a2f71bcdf91c.jpg)

**Comment by BethMassi** [comment]
I retweeted dotvvm. Sorry I just saw this one!

**Comment by ddskier** [comment]
Oh wow, I'm really sorry I missed this. Sometimes I get so many notifications I miss them. :(

**Comment by tomasherceg** [comment]
No worries, next time I'll post it earlier before the event. 

I'll be post-processing the live stream recordings and publishing recordings of the individual sessions, so I can create another amplification request for a post with the recordings.
