### ISSUE TITLE
[AMPLIFICATION] - OSS Power-Ups: Verify

### ISSUE THREAD

**Issue by matkoch** [dotnet-foundation/content#37]
**Please describe the content.**
This is a follow-up for our OSS Power-Ups series.

**URL of the content**
https://www.youtube.com/watch?v=ZD5-51iCmU0

**Copy for the content**
```
Our friends at @jetbrains will be hosting another OSS Power-Ups event!

📺 Verify by @SimonCropp
📆 When: July 14 2021, 12:00 CEST (6:00 AM EDT)
🤗 Open to all, welcome!
🎟 https://www.youtube.com/watch?v=ZD5-51iCmU0

#dotnet
```

**Date requested**
Preferably twice. One time as soon as possible, and maybe 1 hour before the event (14 July 11pm CEST).

**Channel requested**
Facebook, Twitter

**Additional context**

**Comment by ddskier** [comment]
Posted a few mins ago and repeated at 1:00PM Pacific on the 14th (which I think is the right time...) I'm on vacation on Nantucket right now so my timezones are super confusing to me. :) 

And I posted on Twitter, FB and LinkedIn
