### ISSUE TITLE
[AMPLIFICATION] - Retweet thanks to sponsors

### ISSUE THREAD

**Issue by matkoch** [dotnet-foundation/content#38]
**Please describe the content.**
I'd like to give some hands to our sponsors this time. Hope you could just retweet it!

**URL of the content**
https://twitter.com/nukebuildnet/status/1417134612824956936

**Channel requested**
Twitter

Thanks in advance!

**Comment by ddskier** [comment]
Retweeted!

**Comment by matkoch** [comment]
Thanks @ddskier !
