### ISSUE TITLE
Carl Franklin's Free Blazor Webinars

### ISSUE THREAD

**Issue by carlfranklin** [dotnet-foundation/content#4]
Carl Franklin has announced dates all through April at various times for his "Blazor Desk Show", a 2-hour event where he shares everything he knows about Blazor. Carl thinks this is the right time to learn Blazor, as the component model is set and stone. Your markup and code will be compatible with the release version in November.

http://www.appvnext.com/blog/2020/4/6/new-blazor-desk-show-free-dates

New dates/times announced for the #BlazorDeskShow https://blazordeskshow.com sponsored by 
@DevExpress starting this Tues 4/7. Other April dates: 9th, 15th, 23rd, and 29th. #Blazor component model is baked. Now is a good time to get started!

**Date requested**
ASAP or Tuesday, 4/7

**Channel requested**
Facebook, Twitter

![DeskShow](https://user-images.githubusercontent.com/1486348/78602931-454cb700-7825-11ea-9633-9dabe1118775.png)

**Comment by BethMassi** [comment]
@carlfranklin for Facebook do you have an event you want us to share? Or do you have expanded copy you want us to use? Or just use the same as Twitter? 

Tweet is scheduled for 2:57PM PT.

**Comment by carlfranklin** [comment]
Just use the Tweet.

**Comment by BethMassi** [comment]
https://www.facebook.com/dotnetfoundation/photos/a.294760944512326/544544112867340/?type=3&theater

https://twitter.com/dotnetfdn/status/1247282181858361344

**Comment by carlfranklin** [comment]
Thank you very much!
