### ISSUE TITLE
[AMPLIFICATION] - .NET developer ecosystem survey 2021 result

### ISSUE THREAD

**Issue by maartenba** [dotnet-foundation/content#40]
JetBrains runs an annual developer ecosystem survey, much like StackOverflow and GitHub.

The results are in, and we blogged about the results relevant for .NET developers.

A quick retweet should do the trick: https://twitter.com/resharper/status/1425830563743633408
Ideally in the next week or two.

Many thanks!

**Comment by ddskier** [comment]
done

**Comment by maartenba** [comment]
Your rock! Thank you!
