### ISSUE TITLE
[AMPLIFICATION] - OSS Power-Ups: Statiq

### ISSUE THREAD

**Issue by matkoch** [dotnet-foundation/content#41]
Hi @ddskier!

Another request for our OSS series.

**Please describe the content.**
This is a follow-up for our OSS Power-Ups series.

**URL of the content**
https://www.youtube.com/watch?v=Vc2gqiYzg9o

**Copy for the content**
```
Our friends at @jetbrains will be hosting another OSS Power-Ups event! This time about static site generation 💎

📺 OSS Power-Ups: @statiqdev
🗣 Speaker: @daveaglick
📅 This Wednesday, August 25, 5 PM CEST / 11 AM EDT
🤗 Open to all, welcome!

https://www.youtube.com/watch?v=Vc2gqiYzg9o
```

**Date requested**
Today (23) or tomorrow (24) at around 2pm CEST.

**Channel requested**
Twitter + others that are convenient

Many thanks in advance!

**Comment by ddskier** [comment]
Set for tomorrow at 2pm CEST on Twitter, FB, LinkedIn

**Comment by matkoch** [comment]
Thank you so much!
