### ISSUE TITLE
[AMPLIFICATION] - Retweet @wixtoolset

### ISSUE THREAD

**Issue by robmen** [dotnet-foundation/content#43]
**Please describe the content.**

The WiX Toolset is a member project of the .NET Foundation. We have a very low traffic Twitter handle [@wixtoolset](https://twitter.com/wixtoolset) that essentially Tweets out our fortnightly Online Meetings and the occasional (pre)Releases of our software. It would be helpful if @dotnetfdn retweeted both of those to grow awareness about the WiX Toolset

**URL of the content**

https://twitter.com/wixtoolset

**Copy for the content**

A simple retweet of our online meeting and releases would be great. Here are examples:

1. Online meeting: https://twitter.com/firegiantco/status/1456297840074915843
2. Release: https://twitter.com/wixtoolset/status/1440721436272783374

**Date requested**
Every other Thursday at 9:30AM for online meetings. Releases are much more varied (and very infrequent).

**Channel requested**
Twitter

**Additional context**
Thank you. Had no idea this issue list existed.

**Comment by ddskier** [comment]
Hey Rob, thanks for the request. I'm worried that I won't remember these dates and times for retweets (note that none of the tweet scheduling tools support retweets). The best way to do this is to @dotnetfdn on your posts and then I will see them and I can retweet. Let me know if that works for you.

**Comment by CalvinAllen** [comment]
Sounds like a great use case for hooking up Power Automate 😄

**Comment by robmen** [comment]
We can do that. We'll add a standard callout to the @dotnetfdn Twitter handle to our announcement tweets. Thanks.
