### ISSUE TITLE
[AMPLIFICATION] - Announcement of Cake v2.0.0 RC 1 release

### ISSUE THREAD

**Issue by augustoproiete** [dotnet-foundation/content#44]
**Please describe the content.**
Cake, a .NET Foundation Project, just released version 2.0.0 RC 1

**URL of the content**
https://cakebuild.net/blog/2021/11/cake-v2.0.0-rc0001-released

**Copy for the content**

---

Cake v2.0.0 RC 1 released: New DotNet aliases, improved integration with GitHub Actions and Azure Pipelines, updated .NET TFMs, and and lots of improvements and bug fixes

![image](https://user-images.githubusercontent.com/177608/140671665-5b3c1c1f-2797-4bd3-b1f3-37c0fae7faee.png)
 
https://cakebuild.net/blog/2021/11/cake-v2.0.0-rc0001-released

#csharp #dotnet #devops #cakebuild

---

**Date requested**

November 8th 1pm EST, if possible, or later in the day.

**Channel requested**
Twitter, Facebook, and any others available

**Additional context**
Amplification request suggested by @isaacrlevin - https://twitter.com/isaacrlevin/status/1457467729384927233

**Comment by ddskier** [comment]
I have scheduled this for 1:15PM EST, Nov 8th on Twitter, FB & LinkedIn.
