### ISSUE TITLE
[AMPLIFICATION] - Migrating our trusty ol’ .NET Framework applications to AWS, hold on! One foot at a time!

### ISSUE THREAD

**Issue by fbouteruche** [dotnet-foundation/content#45]
**Please describe the content.**
The content is a Medium post on the I Love My Local Farmer engineering blog on Medium. This is a fictional company built for sharing purpose. They share their lessons learnt from their journey to AWS. This is the second post of a series focusing on .NET on AWS and how they can migrate and modernize their .NET Framework applications. In this post, they discuss how they broke their monolith app to migrate only a small part first to put their hands on AWS.

It can be useful for the .NET community to know that their preferred development stack is well supported on AWS and what are the available tools and hosting options.

**URL of the content**
https://medium.com/i-love-my-local-farmer-engineering-blog/migrating-our-trusty-ol-net-framework-applications-to-aws-hold-on-one-foot-at-a-time-12721e1f55af

**Copy for the content**
Default to the blog post title + the handle of the dedicated twitter account: @ILMLFarmerEng

**Date requested**
When approved

**Channel requested**
Facebook, Twitter, LinkedIn
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
I'm a Senior Developer Advocate at AWS focusing on .NET developers. This is the second post of a series focusing on .NET on AWS.

**Comment by fbouteruche** [comment]
Hello. I realize that opening this during the .NET Conf week was definitely not a good idea 😊

**Comment by ddskier** [comment]
Ugh, sorry I missed this! I'm posting this a little later today. I'll repeat later in the week. Apologies.

**Comment by ddskier** [comment]
I have this scheduled for 8AM Pacific today on Twitter, FB, LinkedIn. Then repeating on Friday. Sorry again!

**Comment by fbouteruche** [comment]
Hi @ddskier. No need to apologize. I'm the one to blame. Scheduling a post release the week of the .NET Conf is just not a good idea :D I thank you for taking the time to amplify my content.
