### ISSUE TITLE
[AMPLIFICATION] - Long running workflows with ability to suspend and replay the workflow in future.

### ISSUE THREAD

**Issue by ackava** [dotnet-foundation/content#46]
**Eternity Framework for DotNet to execute long running stateful workflows**
Strongly typed, unit testable long running workflows with dependency injection and an abstract storage, lets you create various workflows in simple syntax inspired from Durable Tasks with added features with support for mobile devices. You can use it on ASP.NET, ASP.NET Core, Xamarin Forms, almost everywhere.

**URL of the content**
[Eternity Framework ](https://github.com/neurospeech/eternity)

**Copy for the content**
Strongly typed, unit testable long running eternal workflows with dependency injection and an abstract storage, lets you create various workflows in simple syntax inspired from Durable Tasks with added features with support for mobile devices.

**Date requested**
Any date

**Channel requested**
Facebook, Twitter

**Comment by ddskier** [comment]
This is scheduled for tomorrow 11/17 at 6:30AM Pacific Timezone.
