### ISSUE TITLE
OSS + C#/.NET EVENT AMPLIFICATION - Building OSS Projects with C# and .NET, December 2/2021

### ISSUE THREAD

**Issue by andhowMSFT** [dotnet-foundation/content#48]
**Please describe the content.**
The Microsoft Reactor is hosting a virtual event on Thursday December 2 at 9am PT with contributors to two OSS projects being built and maintained in C# and .NET.

Led by Claire Novotny, our event host and Senior Program Manager on the .NET team at Microsoft, this conversation-style event will feature contributors from two OSS projects: Andres Pineda from Uno Platform and David Paquette from Humanitarian Toolbox.

https://github.com/unoplatform 
https://github.com/htbox 

Attendees will learn about the goals and status of these OSS projects, dive into the technology used to build and maintain them while relying on a distributed team of developers, and discover some lessons learned from experiences contributing to the creation of open-source software.

**URL of the content**
https://aka.ms/OSSProjectsWithNETandC 

**Copy for the content**
On Thursday December 2nd the Microsoft Reactor is hosting an engaging discussion with contributors to open-source software (OSS) projects being built and maintained in C# and .NET.

@clairernovotny is hosting a conversation with @ajpinedam and @Dave_Paquette, contributors to @UnoPlatform & @HTbox

**Date Requested:**
Between November 24 and December 1, 2021

**Channel requested**
Please help promote this event via any social channels that you feel are appropriate

Here is a creative asset to help promote this event 
![Social Creative - Reactor Dec 2 OSS C# dotnet](https://user-images.githubusercontent.com/93114898/143089192-a1bb9e66-450b-45c8-838a-db1eb1061b35.jpg)

See here for the creative asset and supporting info: https://twitter.com/and_how/status/1461839754375274503?s=20

FYI - Host and Speakers: @clairernovotny @ajpinedam @dpaquette

**Comment by ddskier** [comment]
I teed this up for the 26th and 28th on Twitter, FB, LinkedIn. I'm not closing this yet because I will try to also setup for next week too.

**Comment by nicoleabuhakmeh** [comment]
Closing this request.
