### ISSUE TITLE
 Cake v2.0.0 released

### ISSUE THREAD

**Issue by devlead** [dotnet-foundation/content#49]
The .NET Foundation project Cake has released 2.0

**URL of the content**

https://cakebuild.net/blog/2021/11/cake-v2.0.0-released

**Copy for the content**

> Cake v2.0.0 released! 🎉
> 
> * C# 10 & .NET 6 support
> * Improved dotnet CLI support
> * Improved GitHub Actions integration
> * Improved Azure Pipelines integration
> * Refactored docker images
> 
> .. and more! The full list of changes at
> https://cakebuild.net/blog/2021/11/cake-v2.0.0-released
> #dotnet #devops #csharp

**Date requested**
As soon as possible.

**Channel requested**
Facebook, Twitter

**Comment by ddskier** [comment]
Scheduled for Dec 1 and repeating on Dec 3. Will be on Twitter, FB, LinkedIn.
