### ISSUE TITLE
[AMPLIFICATION] - DotVVM Virtual Conference

### ISSUE THREAD

**Issue by tomasherceg** [dotnet-foundation/content#5]
**Please describe the content.**
We have decided to organize a two-day virtual event (3 sessions every day) focused on the DotVVM framework. The content will be mixed to satisfy beginners and newbies as well as current DotVVM users who use advanced features. There will be also a special session dedicated to ASP.NET Web Forms developers who are looking for some ways how to modernize their legacy applications. We plan to stream the event using Twitch.

**URL of the content**
https://www.dotvvm.com/blog/71/Save-the-date-of-DotVVM-Virtual-Conference-April-29-30

**Copy for the content**
Join the @DotVVM team on a two-day virtual conference on April 29-30. You'll learn how to build web apps using MVVM with just HTML and C#, how to modernize old Web Forms projects using DotVVM, and much more! https://www.dotvvm.com/blog/71/Save-the-date-of-DotVVM-Virtual-Conference-April-29-30 #DotVVM #LiveStream #Conference

![Virtual conference_TWITTER_1024x512px-01](https://user-images.githubusercontent.com/5599524/79213723-f10b8d80-7e49-11ea-86b3-35ba34cc2328.jpg)
![Virtual conference_FACEBOOK_1200x630px](https://user-images.githubusercontent.com/5599524/79213731-f49f1480-7e49-11ea-8b34-62156f55ae11.jpg)

**Date requested**
It would be great to promote in the week of April 19 and maybe repost it on April 27 or 28 if possible.

**Channel requested**
Facebook, Twitter

**Additional context**

**Comment by BethMassi** [comment]
This is scheduled on Twitter for Monday 4/19 & 4/27 at 9AM PT.
