### ISSUE TITLE
[AMPLIFICATION] - Retweet JetBrains Release Party

### ISSUE THREAD

**Issue by matkoch** [dotnet-foundation/content#50]
Hi @ddskier

this is just a request for a retweet. Maybe one today, and another on Monday?

https://twitter.com/JetBrainsRider/status/1468933328300560390
https://twitter.com/resharper/status/1468933067012247556

Thanks in advance!

**Comment by ddskier** [comment]
I retweeted today and have this scheduled for Monday on Twitter, FB, LinkedIn and repeating on Tuesday.
