### ISSUE TITLE
[AMPLIFICATION] - Minimal Api with ABP

### ISSUE THREAD

**Issue by antosubash** [dotnet-foundation/content#51]
**Please describe the content.**
Hello world sample using the Minimal Api with ABP Web application framework. This is created to  explain simplicity and the modularity of the abp framework.

**URL of the content**
https://blog.antosubash.com/posts/abp-with-minimal-api-p1

**Copy for the content**
Hello world api using the Minimal Api with ABP Web application framework.  (i.e. Twitter 280 characters)

**Date requested**
Any date

**Channel requested**
Facebook, Twitter

**Comment by ddskier** [comment]
This is scheduled on Twitter, LinkedIn, FB on Jan 5 at 6:45AM Pacific Timezone
