### ISSUE TITLE
[AMPLIFICATION] - Many to Many Relationship with ABP Framework and EF Core

### ISSUE THREAD

**Issue by EngincanV** [dotnet-foundation/content#52]
**Please describe the content.**
Shows how to many-to-many relationship can be established with the ABP framework and EF Core by following DDD rules.
The main reason for creating such an article is to demonstrate how to many-to-many relationship should be established with DDD-based applications. I think this kind of content can be helpful for .NET Community.

**URL of the content**
https://community.abp.io/articles/many-to-many-relationship-with-abp-and-ef-core-g7rm2qut

**Copy for the content**
In this article, we'll see how we can create a many-to-many relationship by following DDD rules on ABP-based applications (or any kind of .net core application).

**Date requested**
Any date

**Channel requested**
Facebook, Twitter

**Comment by ddskier** [comment]
This is scheduled for Jan 10 at 6:40AM Pacific Timezone (P.S. let me know if I should post to another timezone). Happy to repeat this post (or any post) at another time.
