### ISSUE TITLE
[AMPLIFICATION] - Apizr

### ISSUE THREAD

**Issue by Jerome-Liger** [dotnet-foundation/content#53]
**Please describe the content.**
At Respawnsive, we are borred to create complete resilient client-API each time from scratch on new mobile projects...
That's why we have created "Apizr" that let us quickly configure resilient-client-API !
We use it on production, we maintain and evolve it, and we share it whith OSS community :-)

We are currently evolving Apizr to V3, with the minimum of dependancies and refactored to be prepared for .NET6/MAUI.

**URL of the content**
OSS project :
https://github.com/Respawnsive/Apizr
Blog post :
https://www.respawnsive.com/category/blog-en/apizr/

**Copy for the content**
Apizr is a Refit based api client, but resilient (retry, connectivity, cache, auth, log, priority, etc...)

**Date requested**
Anytime

**Channel requested**
Any channel

Ideas, needs, PR, contributors, amplification... everybody is welcome to help us improve Apizr :-)

**Comment by ddskier** [comment]
This is scheduled for Jan 11 at 6:40AM Pacific Timezone
