### ISSUE TITLE
[AMPLIFICATION] - Global AI Bootcamp Latinoamerica 2022 

### ISSUE THREAD

**Issue by icebeam7** [dotnet-foundation/content#54]
**Please describe the content.**
Hello!

Could you please help with a retweet of the information of our next event? It's about Artificial Intelligence and Machine Learning and there are several sessions where .NET technology will be integrated (Xamarin, MLNET, NET Core, C#...). We have sessions in English and in Spanish.

**URL of the content**
https://twitter.com/darkicebeam/status/1479094705455611906 

(it's in Spanish, if the message must be in English, let me know and I can prepare it)

**Date requested**
We'd appreciate if it can be retweeted today and on Wednesday

**Channel requested**
Twitter

Thank you!

**Comment by ddskier** [comment]
I retweeted today and will retweet on Wed, Jan 12.
