### ISSUE TITLE
[AMPLIFICATION] - .NET OSS Maintainer Support Survey

### ISSUE THREAD

**Issue by SeanKilleen** [dotnet-foundation/content#56]
**Please describe the content.**

In an effort to put some data behind .NET OSS Maintainer / contributor needs, I've created a survey. This survey aims to identify the different types of support maintainers could receive and how well supported they currently feel in each regard. I will be sharing the aggregated data and insights with the larger community and hope to use it to help prioritize efforts to support those who are supporting us all.

**URL of the content**

* Blog post: https://seankilleen.com/2022/01/announcing-the-net-oss-maintainer-support-survey/
* Direct link to survey: https://docs.google.com/forms/d/e/1FAIpQLSdMvnARfsQ6vgrgaRK-fzR80zXDKfAL2eJUhA_aD7EFjAX8ew/viewform?usp=sf_link

**Copy for the content**

(Feel free to modify in whatever way you feel is best, and feel free to use the direct link if you feel it's more prudent; I trust you.)

Twitter: 

> Calling #dotnet Maintainers / #oss Contributors: @sjkilleen has published a survey on how we can best support you. Lend your voice and spread the word to your favorite maintainers / contributors!  https://seankilleen.com/2022/01/announcing-the-net-oss-maintainer-support-survey/

Facebook: 

> Calling .NET Maintainers / #oss Contributors: Sean Killeen has published a survey on how we can best support you. Lend your voice and spread the word to your favorite maintainers / contributors!  https://seankilleen.com/2022/01/announcing-the-net-oss-maintainer-support-survey/

**Date requested**

At your convenience; no deadline.

**Channel requested**

Facebook, Twitter

**Comment by ddskier** [comment]
Scheduled this for Jan 24 at 6:45AM Pacific timezone. Will be posted to Twitter, FB, LinkedIn

**Comment by SeanKilleen** [comment]
Thank you! ♥️

**Comment by ddskier** [comment]
Btw, I will repeat this post - most likely on the 27th.
