### ISSUE TITLE
[AMPLIFICATION] - Cricket Analysis and Prediction using ML.Net(C#)

### ISSUE THREAD

**Issue by praveenraghuvanshi** [dotnet-foundation/content#57]
**Please describe the content.**
An article/tutorial on applying Machine Learning to the game of Cricket using ML.Net. ML.Net is machine learning offering from Microsoft for .Net developers. The article does exploratory data analysis and prediction on the Cricket dataset and unlock insights from the dataset.

**URL of the content**
https://dev.to/praveenraghuvanshi/cricket-analysis-and-prediction-using-mlnetc-56od

**Copy for the content**
Applying Data Science and Machine Learning to the game of cricket by leveraging ML.Net framework from Microsoft.

**Date requested**
Anytime soon

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**

![image](https://user-images.githubusercontent.com/66641548/153102287-25d9007d-1665-46e4-9a25-4a8289cdf908.png)

**Comment by ddskier** [comment]
This is scheduled to run on Feb 10 on Twitter, FB, LinkedIn at 6:45AM Pacific Timezone
