### ISSUE TITLE
[AMPLIFICATION] - Silk.NET Community Meeting & API Review

### ISSUE THREAD

**Issue by Perksey** [dotnet-foundation/content#58]
**Please describe the content.**
This is promoting the first public Silk.NET Community Meeting & API Review, where we will be discussing and reviewing ideas and designs for a complete rewrite of the library. For more information see dotnet-foundation/wg-marketing#8.

**URL of the content**
https://youtu.be/YGRW-zDmSBw

**Copy for the content**

ASAP:

---

Join the @silkdotnet team on 25 Feb 19:00 UTC for a community meeting as they discuss & review designs for a complete rewrite! Have you used Silk .NET or a similar library, or interested in .NET graphics/compute? Pop by and give the team your thoughts! https://youtu.be/YGRW-zDmSBw

---

Day before the event (24th Feb):

---

Don't forget about the @silkdotnet community meeting tomorrow at 19:00 UTC, discussing & reviewing designs for a complete rewrite! Have you used Silk .NET or a similar library, or interested in .NET graphics/compute? Pop by and give the team your thoughts! https://youtu.be/YGRW-zDmSBw

---

Replace @silkdotnet with just Silk.NET or Silk .NET (if the platform converts the former to a URL automatically) on anywhere other than Twitter.

Of course, feel free to tweak the above to how you see fit! And the follow-up doesn't necessarily have to be the day before, you're better than this than I am so use whatever interval you think will bring the most people to the stream.

**Date requested**
As above.

**Channel requested**
- Facebook: Both
- Twitter: Both
- LinkedIn: First post only (I feel people don't check LinkedIn frequently enough for the second to do anything)

Unless you feel other channels are more appropriate.

**Additional context**
dotnet-foundation/wg-marketing#8

**Comment by ddskier** [comment]
I scheduled for Feb 15 at 6:45AM Pacific Timezone - I wanted to avoid Feb 14 because .NET is having a big 20th anniversary event so I didn't want to compete with that. I'm repeating the first post on Feb 21 at the same time. I've scheduled the 2nd post for Feb 24 at 6:40AM Pacific.

I've scheduled for FB, Twitter, LinkedIn.

**Comment by Perksey** [comment]
Thank you!
