### ISSUE TITLE
[AMPLIFICATION] - JetBrains .NET Day Online call for speakers

### ISSUE THREAD

**Issue by maartenba** [dotnet-foundation/content#59]
**Please describe the content.**
Promotion of the JetBrains .NET Day Online call for speakers. We're hosting an event for the wider .NET comunity, and would like to attract some speakers.

**URL of the content**
https://twitter.com/resharper/status/1494211057212088321

**Copy for the content**
A retweet is enough. Otherwise, Tweet text:

```
JetBrains have opened the Call for Speakers for the 2022 JetBrains .NET Day Online 🎉

✔️ Available on June 1, 2022?
✔️ Have a great session to share with fellow #dotnet folks?
👉 Submit your talk! https://jb.gg/8paixi
```

**Date requested**
Before March 10, 2022.

**Channel requested**
Facebook, Twitter

Thank you! 🙏

**Comment by maartenba** [comment]
Could you update the scheduled tweet with June 1 (instead of June 2?) Many thanks!

**Comment by ddskier** [comment]
Updated. Also I'm repeating on Mar 2 as well if that's ok.

**Comment by maartenba** [comment]
Yup, thanks! And I'm really sorry for this, could you change the date to May 17? (we just learned the UK has moved a public holiday so had to reschedule). May 17 is now final :)

**Comment by ddskier** [comment]
Updated to May 17
