### ISSUE TITLE
[AMPLIFICATION] - JetBrains .NET Day Online

### ISSUE THREAD

**Issue by maartenba** [dotnet-foundation/content#6]
**Please describe the content.**
As a Technical Steering Group member, JetBrains organizes the .NET Days Online, on May 13 and 14., a two-day virtual event relevant to folks in the .NET space. Since .NET Foundation is a supporter, amplification seems relevant.

**URL of the content**
The event itself is at: https://pages.jetbrains.com/dotnet-days-2020/dnf

**Copy for the content**
```
Join us for JetBrains .NET Days Online! 📣
A free, virtual event, supported by .NET Foundation, on May 13 and 14.

Topics: #csharp, #fsharp, coding practices, web, cloud, #Xamarin, and more!
🎫 Save your seat: https://pages.jetbrains.com/dotnet-days-2020/dnf #dotnet
```

**Date requested**
Any time before May 13 and 14 that fits your content schedule.

**Channel requested**
Facebook, Twitter

**Comment by ddskier** [comment]
I'm scheduling these tweets/posts for weekly amplification until the event. Plus will schedule for both days of the event.
