### ISSUE TITLE
[AMPLIFICATION] - Xliff support for ResXResourceManager

### ISSUE THREAD

**Issue by tom-englert** [dotnet-foundation/content#61]
**Please describe the content.**
Version 1.63 now supports Xliff files. 

**URL of the content**
https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Xliff.md

**Copy for the content**
ResXResourceManager Version 1.63 now supports sync to Xliff files.
Complement or replace MAT with the unique user experience of RXRM:
https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Xliff.md

**Date requested**
ASAP

**Channel requested**
Facebook, Twitter

**Comment by ddskier** [comment]
Just now posted to FB, Twitter, LinkedIn and repeating on Feb 25 at 6:45AM Pacific timezone
