### ISSUE TITLE
[AMPLIFICATION] - .NET Beyond

### ISSUE THREAD

**Issue by Layla-P** [dotnet-foundation/content#62]
**Please describe the content.**
A clear and concise description of what the content is and why it's important to the .NET open source community. Ex. The .NET Foundation should amplify this content because it provides news about a .NET Foundation new project release [...]

**URL of the content**
[dotnetbeyond.io](http://dotnetbeyond.io/)

**Copy for the content**
Are there any boundaries to what you can build with .NET? Not really! :rocket:Join @VMwareTanzu for two full days on Twitch as they look at how some of the smartest voices in the .NET community are using it to develop for the enterprise—and at scale. [dotnetbeyond.io](http://dotnetbeyond.io/)

**Date requested**
3/17

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
We are raising money for GirlsWhoCode and all sponsorship is going directly to our fundraiser.
Nicole has some graphics that can be used

**Comment by ddskier** [comment]
Scheduled two consecutive posts on 3/17 at 6:40AM Pacific. One is about the event and the other is about girls who code. Will go out on Twitter, FB, LinkedIn accounts
