### ISSUE TITLE
[AMPLIFICATION] - Throw

### ISSUE THREAD

**Issue by mantinband** [dotnet-foundation/content#63]
Not sure this is the right place to share this, so feel free to reject the issue 😁

**Please describe the content.**
A simple, fluent, extensible, and fully customizable library for throwing exceptions for projects using .NET 6+

**URL of the content**

https://twitter.com/amichaiman/status/1499357927509012492?s=21

https://www.linkedin.com/posts/amichaim_throw-exception-throwing-library-activity-6905119461947625472-xFjZ

[GitHub repo](https://github.com/mantinband/throw)

**Copy for the content**
A simple, fluent, extensible, and fully customizable library for throwing exceptions for projects using .NET 6+

**Date requested**
Whenever 🙂

**Channel requested**
Twitter, LinkedIn, Facebook

**Additional context**
A quick getting started infographic👇🏼
![Getting started png](https://github.com/mantinband/throw/blob/main/assets/getting-started.png?raw=true)

**Comment by ddskier** [comment]
Scheduled for Mar 16 at 6:45AM Pacific timezone on Twitter, FB, LinkedIn. Happy to repost again if you want me to do at a different timezone. Let me know.

**Comment by mantinband** [comment]
Yay, thanks 🔥🤙🏽🙌🏽
