### ISSUE TITLE
[AMPLIFICATION] - How to get started with .NET on AWS

### ISSUE THREAD

**Issue by fbouteruche** [dotnet-foundation/content#66]
**Please describe the content.**
In response to a question on Twitter regarding how to learn and be proficient in .NET on AWS, I've written a LinkedIn article to share my tips and some useful links.

I think it will help .NET developers who work for companies that use AWS as their Cloud provider.

**URL of the content**
https://www.linkedin.com/pulse/how-get-started-net-aws-fran%C3%A7ois-bouteruche/

**Copy for the content**
If you want to learn using .NET on AWS, here are some good tips to start.

**Date requested**
When approved

**Channel requested**
LinkedIn, Twitter
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
I'm a Senior Developer Advocate at AWS.

**Comment by ddskier** [comment]
Scheduled for tomorrow, 3/24 and repeating Monday 3/28. Will post to FB, LinkedIn, Twitter

**Comment by fbouteruche** [comment]
Thanks you 🙏
