### ISSUE TITLE
[AMPLIFICATION] - Education Committee Meetings

### ISSUE THREAD

**Issue by katiesavage** [dotnet-foundation/content#67]
**Please describe the content.**
The Education Committee meets every 2nd and 4th Friday at 9:00am PST. I hope to promote this meeting to boost membership.

**URL of the content**
Link to the article, blog, video, social post, presentation, etc. 

**Copy for the content**
The .NET Foundation Education Committee is meeting this Friday! Join us in welcoming students and teachers into the [#dotnet](https://twitter.com/hashtag/dotnet?src=hashtag_click) ecosystem. 
Meeting are every 2nd and 4th Friday at 9AM PST | 4PM GMT

**Date requested**
Wednesday, March 30th 

**Channel requested**
Twitter

**Additional context**
![education-committee-meeting](https://user-images.githubusercontent.com/20649242/160176264-5172464a-7f93-4357-8c35-07aedc023680.jpg)

**Comment by ddskier** [comment]
Can you tell me how they join the mtg? What's the URL? Thanks!

**Comment by katiesavage** [comment]
Here's the meeting [link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NmZjNTkyMTAtMjc3Yi00MjJkLTgwMjYtYWI2ZTljMWU1YmI2%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%22e196d8e6-f7d3-4a7d-b526-c2af9dfd5cff%22%7d)! Thank you.

**Comment by ddskier** [comment]
This is scheduled for Mar 30 and repeating on Apr 1. Will be posted to Twitter, FB, LinkedIn

**Comment by katiesavage** [comment]
Thank you!
