### ISSUE TITLE
[AMPLIFICATION] - Podcast episode - Geeking out on .NET with Nick Chapsas

### ISSUE THREAD

**Issue by dracan** [dotnet-foundation/content#68]
**Please describe the content.**
This was a really great and fun discussion about a wide range of .NET topics.

**URL of the content**
https://unhandledexceptionpodcast.com/posts/0034-nickchapsas/

**Copy for the content**
In this podcast episode, @dracan and @nickchapsas geek out on a range of #dotnet topics - from Minimal Api, to Github Copilot, to Mediatr and open-source, and more!

**Date requested**
Whenever best suits the Foundation.

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Scheduled for Apr 5 at 6:45AM Pacific Timezone. Will post on Twitter, FB, LinkedIn
