### ISSUE TITLE
[AMPLIFICATION] - Cake 2.2.0 released

### ISSUE THREAD

**Issue by devlead** [dotnet-foundation/content#69]
**Please describe the content.**

Cake v2.2.0 released 🎉
⭐Opt-in script caching for significant performance gains
⭐New aliases for using dotnet workload search
⭐Fixes in UNC and relative path collapsing
⭐Improved handling of .NET runtime reference assemblies
More at release blog post: https://cakebuild.net/blog/2022/04/cake-v2.2.0-released

**URL of the content**
https://cakebuild.net/blog/2022/04/cake-v2.2.0-released

**Copy for the content**
Above should work

**Date requested**
As soon as possible 

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
This is scheduled for tomorrow, 4/18 at 6:45AM PDT and repeating on 4/20 at 4:45PM PDT. It will post to Twitter, FB, LinkedIn.
