### ISSUE TITLE
[AMPLIFICATION] - The Virtual ML.NET Community Conference

### ISSUE THREAD

**Issue by aslotte** [dotnet-foundation/content#7]
**Please describe the content.**
The Virtual ML.NET Community Conference is a 2-day free community driven conference on all things ML.NET (Machine Learning in .NET). I believe the .NET Foundation would benefit from promoting this conference as ML.NET is still very new and many developers in the .NET community has expressed interest in learning more about ML and how they can apply that in their day-to-day jobs. 

**URL of the content**
http://virtualml.net/
https://sessionize.com/virtual-ml-net/

**Copy for the content**
The Virtual ML.NET Community Conference is a 2-day community driven conference on all things ML.NET. Join us on May 29th to learn more about Machine Learning in .NET!

**Date requested**
ASAP

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please see the [Newsletter repo](https://github.com/dotnet-foundation/newsletter)
To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Will schedule these now
