### ISSUE TITLE
[AMPLIFICATION] - A lightweight file logger provider implementation for Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by xiaomi7732** [dotnet-foundation/content#70]
**Please describe the content.**

I recently created a Logging Provider for File since there is not an official implementation by Microsoft. I tried some others, not as easy to use or lack of guide/doc.
This one targeting
* Easy to use 
* A level of performance.

How to build videos also available.

**URL of the content**
* [Readme](https://github.com/xiaomi7732/CodeWithSaar.Extensions.Logging/blob/main/CodeWithSaar.Extensions.Logging.File/Readme.MD)
* [NuGet package](https://www.nuget.org/packages/CodeWithSaar.Extensions.Logging.File)
* Videos for how are they built
  * [How to implement a custom logging provider for files (1/2)](https://youtu.be/3RUpYR4dZM4)
  * [How to implement a custom logging provider for files (2/2)](https://youtu.be/3Z3yemyikNc)

Appreciated!

**Comment by ddskier** [comment]
I scheduled this for 4/21 at 6:45AM PDT. Will post to Twitter, FB, LinkedIn. I'm not closing this because not sure if this is also requesting newsletter amplification.
