### ISSUE TITLE
[AMPLIFICATION] - .NET Enterprise Developer Day EMEA 2022

### ISSUE THREAD

**Issue by nicoleabuhakmeh** [dotnet-foundation/content#71]
**Please describe the content.**
#dotNET developers, #AWS has a free, all-day virtual event, .NET Enterprise Developer Day EMEA, on April 26. Learn best practices for migrating and modernizing .NET applications in the cloud. You can also join DeveloperWeek Europe, April 27-28, for free! https://bit.ly/3NIAdcK

**URL of the content**
[Link to the article, blog, video, social post, presentation, etc](https://bit.ly/3NIAdcK)

**Copy for the content**
#dotNET developers, #AWS has a free, all-day virtual event, .NET Enterprise Developer Day EMEA, on April 26. Learn best practices for migrating and modernizing .NET applications in the cloud. You can also join DeveloperWeek Europe, April 27-28, for free!

**Date requested**
Week of event

**Channel requested**
Facebook, Twitter

**Comment by ddskier** [comment]
Scheduled for Apr 25, repeating Apr 26 at 6:45AM PDT. Will post to Twitter, LinkedIn, FB
