### ISSUE TITLE
[AMPLIFICATION] - Authenticate Flutter Web Application in ABP IdentityServer

### ISSUE THREAD

**Issue by bigebesikci** [dotnet-foundation/content#74]
Hi there,

We have another beneficial article for the .NET Foundation Community. We would appreciate if you agree that your community would benefit from the content and share it with your followers.

**Description of the content.**
In this article, users will see, how to use ABP authentication in Flutter Web. Before further progress,ABP project and flutter application are assumed running on a web version in a specific port. In this article's example, 4200 is used as port.

**URL of the content**
[Link to the article](https://community.abp.io/posts/flutter-web-authentication-from-abp-mp6l2ehx)

**Copy for the content**
Learn how to authenticate flutter web application in ABP IdentityServer in detail with examples.

**Date requested**
Anytime that suits your schedule is fine.

**Channel requested**
Facebook, Twitter

Please let me know if there is anything that you need further. I'd love to provide if I could.

Thank you in advance. I appreciate it.

**Comment by ddskier** [comment]
Scheduled for May 10 and repeating on May 13 - both at 6:45AM Pacific. Will post to Twitter, FB, LinkedIn
