### ISSUE TITLE
[AMPLIFICATION] - Handle Concurrency with EF Core in an ABP Framework Project with ASP.NET Core MVC

### ISSUE THREAD

**Issue by bigebesikci** [dotnet-foundation/content#75]
Hi there,
We have another content which might be useful for .NET Foundation's audience. If you agree it would be beneficial and share it with .NET Foundation community, we would appreciate it.

**Description of the content.**
In this article, a basic application is created to demonstrate how "Concurrency Check/Control" can be implemented in an ABP project.

**URL of the content**
[Link to the article](https://community.abp.io/posts/handle-concurrency-with-ef-core-in-an-abp-framework-project-with-asp.net-core-mvc-jlkc3w8f)

**Copy for the content**
Read the demonstration of how concurrenct check/control can be implemented with EF Core in an ABP Framework Project with ASP.NET Core MVC from the article.

**Date requested**
Anytime that suits your schedule is all right for us, thank you.

**Channel requested**
Facebook, Twitter

Please let me know if there is anything we need to/can do for you. Thank you in advance.

**Comment by ddskier** [comment]
Scheduled for Monday, May 16 at 6:45AM Pacific. Will post to Twitter, FB, LinkedIn
