### ISSUE TITLE
[AMPLIFICATION] - The Unhandled Exception Podcast - Andrew Lock

### ISSUE THREAD

**Issue by dracan** [dotnet-foundation/content#76]
**Please describe the content.**
The episode is very .NET specific, covering a lot of hot .NET topics. The guest is highly regarded in this space, and I think the .NET community would really enjoy this conversation.

**URL of the content**
https://unhandledexceptionpodcast.com/posts/0036-andrewlock/

**Copy for the content**
In this #UnhandledException podcast episode, @dracan was joined by @andrewlocknet to chat about #aspnetcore. Covering plenty of other topics like #Kubernetes #Blazor #gRPC #mediatr #MinimalApi #Docker and #testing too! 🔥🎙 https://unhandledexceptionpodcast.com/posts/0036-andrewlock/

**Date requested**
Whenever suits you :)

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Scheduled for tomorrow, May 12 at 6:45AM Pacific Timezone. Will post to Twitter, FB, LinkedIn
