### ISSUE TITLE
[AMPLIFICATION] - 50 shades of .NET on AWS, how to host our .NET applications on AWS.

### ISSUE THREAD

**Issue by fbouteruche** [dotnet-foundation/content#77]
**Please describe the content.**
The content is a Medium post on the I Love My Local Farmer engineering blog on Medium. This is a fictional company built for sharing purpose. They share their lessons learnt from their journey to AWS. 

This post details how their .NET development team decides which are the best AWS hosting options for their .NET applications depending on their use cases.

It can be useful for the .NET community to know that their preferred development stack is well supported on AWS and what are the available tools and hosting options.

**URL of the content**
https://medium.com/i-love-my-local-farmer-engineering-blog/50-shades-of-net-on-aws-39f38205919c

**Copy for the content**
Default to the blog post title + the handle of the dedicated twitter account: @ILMLFarmerEng or LinkedIn page: https://www.linkedin.com/company/i-love-my-local-farmer

**Date requested**
When approved

**Channel requested**
Twitter, LinkedIn
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
I'm a Senior Developer Advocate at AWS focusing on .NET developers.

**Comment by ddskier** [comment]
This is scheduled for May 23 at 6:45AM Pacific & repeats on May 26. Will post to Twitter, FB, LinkedIn
