### ISSUE TITLE
[AMPLIFICATION] - Unhandled Exception Podcast - Microsoft Build

### ISSUE THREAD

**Issue by dracan** [dotnet-foundation/content#79]
**Please describe the content.**
A lot of the Build announcements discussed in this episode are .NET related.

**URL of the content**
https://unhandledexceptionpodcast.com/posts/0037-build/

**Copy for the content**
The next #UnhandledException podcast episode is an #MSBuild special! @dracan was joined by both @coolcsh and @gauravseth to chat about some of the announcements! 🔥🎙️ https://unhandledexceptionpodcast.com/posts/0037-build/ #dotnet #blazor #dotnetmaui @AzContainerApp #aspnetcore #azure

**Date requested**
Whenever suits you best. Although, sooner is probably better than later - as Build has now finished.

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
Here's an image that I created for when I tweeted about it. Feel free to use it too...

![FToGV6nWYAAPAbK](https://user-images.githubusercontent.com/567988/170640089-b9621361-0f0f-4c60-ac52-9119b3bb6bf4.jpg)

**Comment by ddskier** [comment]
Posted just now at 6:36AM Pacific Timezone and will repeat next week. Posted to Twitter, FB, LinkedIn

**Comment by dracan** [comment]
Amazing - thank you! 🙂
