### ISSUE TITLE
[AMPLIFICATION] - .NET Virtual User Groups

### ISSUE THREAD

**Issue by SaraJo** [dotnet-foundation/content#8]
**Please describe the content.**
.Net Virtual Meetup Groups announcement. 

**URL of the content**
Link to the article, blog, video, social post, presentation, etc. 
 https://www.meetup.com/dotnet-virtual-user-group/

**Copy for the content**
.NET Foundation – .NET Virtual User Group

The .NET Foundation has been working on a new initiative to help .NET user groups go virtual with the new [.NET Virtual User Group]( https://www.meetup.com/dotnet-virtual-user-group/
) program! Let the .NET Foundation take care of all of the streaming so you can focus in on making your meetup awesome and enable developers around the world join in. [Submit your user group session](https://github.com/dotnet-foundation/wg-outreach/issues/new/choose), get scheduled, get promoted, and have your user group. It is a great way to engage with the broader .NET community and keep your user group going during while we are all inside.

If you are looking for awesome upcoming user group sessions from around the world? Then join the .NET Virtual User Group today!

**Date requested**
ASAP next week

**Channel requested**
Facebook, Twitter

**Comment by BethMassi** [comment]
@SaraJo we're holding all social until Wednesday earliest out of respect for George Floyd's funeral services and amplification of important voices on the issues on social.

**Comment by ddskier** [comment]
This is scheduled on Twitter and FB for Monday, Jun 15.
