### ISSUE TITLE
[AMPLIFICATION] - JetBrains developer ecosystem survey

### ISSUE THREAD

**Issue by maartenba** [dotnet-foundation/content#80]
**Please describe the content.**
Much like StackOverflow does, JetBrains has an annual developer ecosystem survey of which data is made publicly available later. The survey can be taken by any developer, and serves to provide insight into different programming languages, developer habits, and more.

**URL of the content**
https://surveys.jetbrains.com/s3/dnet-developer-ecosystem-survey

**Copy for the content**
```
Our friends at @JetBrains opened their annual Developer Ecosystem survey!

🧐 Studying the developer industry
📤 Results and finding will be public
🏆 Chance to win a prize

Take the survey 
https://surveys.jetbrains.com/s3/dnet-developer-ecosystem-survey #dotnet
```

**Date requested**
As soon as possible

**Channel requested**
Facebook, Twitter

**Comment by ddskier** [comment]
Posted just now and will repost. Posted to Twitter, FB, LinkedIn
