### ISSUE TITLE
[AMPLIFICATION] - MAUI & ABP Online Meetup Event

### ISSUE THREAD

**Issue by bigebesikci** [dotnet-foundation/content#81]
Hi there,

We are organizing monthly events with for ABP Community, in this month's episode we will talk about MAUI and ABP Framework. MAUI is a very popular topic nowadays in .Net world, so we think this event would be beneficial for the .Net Foundation's audience.

It would be awesome if you could help us reach more people by sharing it on your socials.

Thank you in advance.

* Organized by ABP Framework team (see the open source ABP Framework: https://github.com/abpframework/abp - A web application framework for ASP.NET Core)
* Event Title: MAUI & ABP Framework
* Event Date: June 9, 2022
* Event Time: 17:00 UTC
* Duration: 1 hour
* Speakers: Alper Ebicoglu (https://github.com/ebicoglu | https://twitter.com/alperebicoglu), Enis Necipoglu (https://github.com/enisn | https://twitter.com/EnisNecipoglu)
* Kommunity Event Registration: https://kommunity.com/volosoft/events/abp-community-talks-20225-maui-abp-framework-ba889f91
* YouTube Link: https://youtu.be/qBOzRqzq7xA

Here are the visuals:
For LinkedIn/Twitter 
![LinkedIn-Twitter](https://user-images.githubusercontent.com/78538870/171902236-ea2ccc1f-fdcd-419d-a039-30f8bb972e7c.png)

1920x1080 Resolution:
![1920x1080](https://user-images.githubusercontent.com/78538870/171902454-e466740d-314b-4675-84cd-043f8eea976e.png)

**Comment by ddskier** [comment]
I posted this just now and will repeat on June 9 at 6:45AM pacific timezone. Posted to Twitter, FB, Linkedin
