### ISSUE TITLE
[AMPLIFICATION] - Unhandled Exception Podcast (E38): .NET MAUI, IoT, and Handy the bionic Arm - with Clifford Agius

### ISSUE THREAD

**Issue by dracan** [dotnet-foundation/content#82]
**Please describe the content.**
Podcast episode about .NET MAUI and IoT.

**URL of the content**
https://unhandledexceptionpodcast.com/posts/0038-cliffordagius/

**Copy for the content**
In this #UnhandledException podcast episode, @dracan was joined by @CliffordAgius to chat all about .NET MAUI, IoT, and Handy the Bionic Arm! 🔥🎙 https://unhandledexceptionpodcast.com/posts/0038-cliffordagius/ Available in all major podcast apps #dotnet #iot #maui

**Date requested**
Whenever suits you best.

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
This is scheduled for Monday, June 13 at 6:45AM Pacific timezone. Will post to Twitter, FB, LinkedIn. Repeating on Thurs, June 16.
