### ISSUE TITLE
[AMPLIFICATION] - REST API following Clean Architecture and Domain-Driven Design principles from scratch

### ISSUE THREAD

**Issue by amantinband** [dotnet-foundation/content#83]
Hi, first of all, thanks for all your work!

I'm creating a series in which we'll be building a REST API following Clean Architecture & Domain-Driven Design principles completely from scratch.
We will use .NET 6, EF Core, and common patterns such as CQRS, unit of work, repository, mediator, and more 💪🏽
We'll also use some awesome open-source libraries such as MediatR, FluentValidation, ErrorOr, Throw, Mapster, and more.
The developing environment will be visual studio code & dotnet CLI only. We will use awesome vscode plugins for everything from sending HTTP requests to connecting to our SQL database, debugging, and peaking at JWT tokens.
We will code and refactor multiple times to tackle the many concepts. When the series will be over, viewers should have a good understanding and intuition on how to use these patterns & libraries in their industry-level applications.

**Please describe the content.**
A concise, digestible, and practical guide to building a REST API following Clean Architecture & Domain-Driven Design principles.

**URL of the content**
![Frame 113 (7)](https://user-images.githubusercontent.com/39407673/173182781-ce013a4b-11fe-4290-9890-d7f8cc3cdab1.png)

Part 1: [REST API Following CLEAN ARCHITECTURE & DDD Tutorial Using .NET 6 | Part 1 - Project Setup](https://www.youtube.com/watch?v=fhM0V2N1GpY&t=10s)

![Frame 113 (8)](https://user-images.githubusercontent.com/39407673/173182797-f02a1d02-6553-46e5-95e7-b6a01ac53c6f.png)
Part 2: [Generating JWT Tokens | REST API Following CLEAN ARCHITECTURE & DDD Tutorial Using .NET 6 | Part 2
](https://www.youtube.com/watch?v=38bQNWKh0dk&t=152s)
Channel: [Link](https://www.youtube.com/channel/UClz49zOCnzsclUJY-t62lIw)

**Copy for the content**
A concise, digestible, and practical guide to building a REST API following Clean Architecture & Domain-Driven Design principles.

**Date requested**
Whenever you think is best 🙂

**Channel requested**
Facebook, Twitter, LinkedIn

The architecture of the project by the end of the series, visualized:

![Group 122 (2)](https://user-images.githubusercontent.com/39407673/173182718-f7370851-09f1-429b-b8ad-f793aa628af4.png)

**Comment by ddskier** [comment]
Part 1 scheduled for June 14 and Part 2 scheduled for June 15. Both will post at 6:45AM pacific timezone on Twitter, LinkedIn & FB.

**Comment by amantinband** [comment]
Awesome, thanks @ddskier! 🤙🏼
