### ISSUE TITLE
[AMPLIFICATION] - All About .NET MAUI

### ISSUE THREAD

**Issue by bigebesikci** [dotnet-foundation/content#84]
Hi there,

We have another article that would be highly beneficial for .NET Foundation's audience. You can find the details below. Thank you in advance.

**Please describe the content.**
In this article, @ebicoglu tells about .NET MAUI, the new generation of Xamarin, based on his talk at https://www.youtube.com/watch?v=qBOzRqzq7xA

**URL of the content**
[Link to the blog article](https://medium.com/volosoft/all-about-net-maui-5a1e774803ac)

**Copy for the content**
In this article, you will learn about .NET MAUI, the new generation of Xamarin. This article is based on the talk at https://www.youtube.com/watch?v=qBOzRqzq7xA.

**Date requested**
Anytime that suits your agenda is fine.

**Channel requested**
Facebook, Twitter, LinkedIn

**Comment by ddskier** [comment]
This is scheduled for monday, June 20th at 6:45AM Pacific timezone. It will post to FB, Twitter & LinkedIn

**Comment by ddskier** [comment]
I can't edit it but I can delete it. Let me know if you want me to delete it.
