### ISSUE TITLE
DNF Summit - October

### ISSUE THREAD

**Issue by nicoleabuhakmeh** [dotnet-foundation/content#85]
**Please describe the content.**
Announcing our next DNF Summit. 

**URL of the content**
dnfsummit.org

**Copy for the content**
Upcoming Event - Our next DNF Summit has been scheduled for Tuesday, October 18, 2022!

**Date requested**
A few times over the next few weeks and the day before. 

**Channel requested**
Facebook, Twitter

**Additional context**
https://www.dnfsummit.org/

**Comment by ddskier** [comment]
I've scheduled for Sat, June 25 at 8AM Pacific Timezone and will continue to repeat. Not closing this for now.
