### ISSUE TITLE
[AMPLIFICATION] - .NET OSS Maintainer Support Survey - The Results!

### ISSUE THREAD

**Issue by SeanKilleen** [dotnet-foundation/content#86]
**Please describe the content.**

This is a follow-up blog post to the original survey (original post that was amplified: https://seankilleen.com/2022/01/announcing-the-net-oss-maintainer-support-survey/)

**URL of the content**

https://seankilleen.com/2022/06/announcing-net-oss-survey-results/

**Copy for the content**

`The results are in for @sjkilleen's .NET OSS Maintainer Support Survey. Check it out here, and see where you might be able to contribute!  https://seankilleen.com/2022/06/announcing-net-oss-survey-results/`

**Date requested**

At your earliest convenience. No hard date. Would appreciate a few scheduled posts for consistency if you're able.

**Channel requested**

Twitter

**Comment by ddskier** [comment]
Scheduled for Wed, June 29 and repeating on Fri, July 1. Will also repeat more.
