### ISSUE TITLE
[AMPLIFICATION] - Flow Control in ASP.NET

### ISSUE THREAD

**Issue by amantinband** [dotnet-foundation/content#87]
**Please describe the content.**
Hi! I think this is an important topic that doesn't get enough attention and can dramatically improve the health and stability of almost any application using ASP.NET

**URL of the content**
https://www.youtube.com/watch?v=tZ8gGqiq_IU

**Copy for the content**
Perhaps it's time we rethink throwing exceptions for flow control.

**Date requested**
Whenever you think is best 🙂

**Channel requested**
Facebook, Twitter, LinkedIn

**Additional context**

![Frame 118 (3)](https://user-images.githubusercontent.com/39407673/177109172-a427b565-ce21-459f-bd2b-fa061ac93a71.jpg)

**Comment by ddskier** [comment]
Scheduled July 6 and repeating July 11. Will post to Twitter, FB, LinkedIn

**Comment by amantinband** [comment]
Hi @ddskier! I've updated the thumbnail, I think this one looks better 🙂 Is it possible to update it?

![Frame 139 (1)](https://user-images.githubusercontent.com/39407673/177308009-42676657-6dce-4024-a244-2707340976a2.jpg)

**Comment by ddskier** [comment]
done
