### ISSUE TITLE
[AMPLIFICATION] - Library for DI and IoC in .NET nanoFramework released

### ISSUE THREAD

**Issue by josesimoes** [dotnet-foundation/content#88]
**Please describe the content.**
We've just released a library to use Dependency Injection and Inversion of Control in .NET nanoFramework projects.
This is another milestone for the project as it allows advanced coding in C# for resource constrained microcontrollers.

**URL of the content**
[Tweet](https://twitter.com/nanoFramework/status/1544333170509639682)
[LinkedIn post](https://www.linkedin.com/posts/dotnet-nanoframework_dotnet-dependencyinjection-ioc-activity-6950098786979352576-lY4H)

**Copy for the content**
If Dependency Injection and Inversion of Control is your thing, you’ll be happy to know that we’ve just released a
[.NET nanoFramework](https://twitter.com/nanoFramework) library for this! 😎
Check the sample and download the NuGet package:
https://github.com/nanoframework/nanoFramework.DependencyInjection

**Date requested**
When possible

**Channel requested**
Facebook, Twitter, LinkedIn

**Additional context**
Thanks! 😄

**Comment by ddskier** [comment]
Set for July 7 and repeating July 12. Will post to FB, Twitter, LinkedIn
