### ISSUE TITLE
[AMPLIFICATION] - Unhandled Exception Podcast - Episode 41: OpenTelemetry in .NET - with Martin Thwaites

### ISSUE THREAD

**Issue by dracan** [dotnet-foundation/content#92]
**Please describe the content.**
OpenTelemetry is rapidly gaining traction as a standard for telemetry (logging, metrics, tracing) across various languages and platforms. .NET is no exception, so it's important that .NET developers understand the OTel concepts.

**URL of the content**
[Link to the article, blog, video, social post, presentation, etc. ](https://unhandledexceptionpodcast.com/posts/0041-opentelemetry/)

**Copy for the content**
In the latest #UnhandledException podcast episode, @dracan was joined by @MartinDotNet to chat all about #OpenTelemetry in @dotnet! 🔭🔥🎙 https://unhandledexceptionpodcast.com/posts/0041-opentelemetry/ #dotnet @opentelemetry

**Date requested**
When suits you best.

**Channel requested**
Facebook, Twitter
Note:
To request content for the Newsletter please submit a PR to [this markdown page](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md). To request technical content and presentations see the [dotnet-presentations repo](https://github.com/dotnet-presentations)

**Additional context**
Add any other context or screenshots about the request here.

**Comment by ddskier** [comment]
Scheduled Aug 3 and repeating on Aug 8. Posting to Twitter, FB, LinkedIn
