### ISSUE TITLE
[AMPLIFICATION] - Clean Architecture Project Setup With .NET 6 and CQRS

### ISSUE THREAD

**Issue by m-jovanovic** [dotnet-foundation/content#93]
**Please describe the content.**
Hello! I think this topic is important because Clean Architecture is a great solution for .NET applications and .NET engineers can benefit from seeing this video.

**URL of the content**
https://youtu.be/tLk4pZZtiDY

**Copy for the content**
A practical guide to setting up a Clean Architecture project using .NET 6 with CQRS and MediatR.

**Date requested**
Ideally, this Friday (12.08.2022.) or, if not possible, Saturday (13.08.2022.)

**Channel requested**
Facebook, Twitter, LinkedIn

**Additional context**
![#4 - Clean Architecture Project Setup](https://user-images.githubusercontent.com/34191235/183897963-1649fb4e-47c7-4f36-bd33-9e4f4b9ee7d3.png)

**Comment by ddskier** [comment]
Scheduled for Friday, Aug 12, repeating on Thurs, Aug 18. Will post to Twitter, FB, LinkedIn

**Comment by m-jovanovic** [comment]
Thank you so much!!!

**Comment by gclaasen** [comment]
Do you have a "code with - step-by-step" series for junior developers or those interested in moving to DDD can follow?

**Comment by m-jovanovic** [comment]
Hey @gclaasen, I don't since most of my content is intended for someone on medior or senior levels.

**Comment by gclaasen** [comment]
> Hey @gclaasen, I don't since most of my content is intended for someone on medior or senior levels.

Hi, is it possible to share the code for this?
