### ISSUE TITLE
[AMPLIFICATION] - ABP & OpenIddict Event

### ISSUE THREAD

**Issue by bigebesikci** [dotnet-foundation/content#94]
Hi there,

We are organizing a new episode of our regular meetings for [Open Source ABP Framework](https://github.com/abpframework/abp) community. I am sending the details below:

* **Event title:** ABP Community Talks 2022.6: ABP Framework v6.0 and OpenIdDict
* **Event date:** August 25, 2022
* **Event time:** 17:00 UTC
* **Speakers:** Halil İbrahim Kalkan (https://twitter.com/hibrahimkalkan), Engincan Veske (https://twitter.com/engincanveske), Galip Tolga Erdem(he doesn’t have a Twitter account)
* **Sponsors:** .NET Foundation, JetBrains
* **Registration:** https://kommunity.com/volosoft/events/abp-community-talks-20226-abp-framework-v60-openiddict-15007e21
* **YouTube link:** https://www.youtube.com/watch?v=th3IugJGQDA

**Copy for the content**
For Facebook Post:
![Facebook](https://user-images.githubusercontent.com/78538870/185153639-dea577b4-340b-4040-912b-1d3723bab475.png)

For Instagram Post:
![Instagram Post](https://user-images.githubusercontent.com/78538870/185153731-ec3432be-e943-4627-9445-a84f761370b4.png)

For Instagram Story:
![Instagram Story](https://user-images.githubusercontent.com/78538870/185153799-94b7e5d0-271f-4243-b5e8-3eeb3b06166d.png)

For LinkedIn & Twitter:
![LinkedIn   Twitter](https://user-images.githubusercontent.com/78538870/185153866-db4fbe15-16b9-4110-977b-73973238ceaf.png)

**Date requested**
Sometime this week and 25th of August, 2022. (the day of the event)

**Channel requested**
Facebook, Twitter, LinkedIn, Instagram

Thank you 🙏

**Comment by ddskier** [comment]
This is scheduled for 8/19 and repeats on 8/25. Will post to Twitter, LinkedIn, FB. We don't have an Instagram account (but we probably should!)
