### ISSUE TITLE
[AMPLIFICATION] - JetBrains .NET Days Online + GameDev Day Online

### ISSUE THREAD

**Issue by maartenba** [dotnet-foundation/content#97]
**Please describe the content.**
On October 25 and 26, JetBrains is again hosting the .NET Days Online. 2 days of sessions with community speakers!
And on October 27, we're adding a GameDev day as well, with sessions about Unreal Engine and Unity.

**URL of the content**
* Direct link: https://pages.jetbrains.com/dotnet-days-2022/dnf
* In case you want to retweet: https://twitter.com/resharper/status/1571821011405864962

**Copy for the content**
```
Our friends at JetBrains are again hosting .NET Days Online!

🗓️ Dates: October 25 and 26
🎙️ Topics: #csharp, #fsharp, Blazor, GraphQL, REST, gRPC, Unity, and more!

More info and registration here: https://pages.jetbrains.com/dotnet-days-2022/dnf
#dotnet #JBDotNetDays
```

**Date requested**
ASAP, and if possible once more in the time between now and October 25.

**Channel requested**
Twitter

Thank you very much 🙏

**Comment by ddskier** [comment]
Scheduled for Sept 20, Oct 3, Oct 18 & Oct 25. Will post to twitter.
