### ISSUE TITLE
[AMPLIFICATION] - ABP & Playwright Testing Event

### ISSUE THREAD

**Issue by bigebesikci** [dotnet-foundation/content#98]
Hi there,

We are organizing a new episode of our regular meetings for [Open Source ABP Framework](https://github.com/abpframework/abp) community. I am sending the details below:

**Title:** UI testing with Playwright / What’s coming with ABP 7.0
**Event date:** September 29, 2022
**Event time:** 17:00 UTC
**Speakers:** @demirmusa(He doesn't have a twitter account), @hikalkan(https://twitter.com/hibrahimkalkan), @ebicoglu(https://twitter.com/alperebicoglu), @gizemmutukurt (https://twitter.com/mutuuu_)
**Sponsors:** JetBrains(3 free annual personal subscription to [dotUltimate](https://www.jetbrains.com/dotnet/) giveaway)
**YouTube link:** https://www.youtube.com/watch?v=q4jIO9f4xg8
**Kommunity event:** https://kommunity.com/volosoft/events/abp-community-talks-20227-ui-testing-with-playwright-upcoming-abp-70-eb0b8701

**Copy for the content**
Facebook: 
![Facebook](https://user-images.githubusercontent.com/78538870/191680759-59eb6a7f-b169-4912-be96-f840929a7588.png)
Instagram Post:
![Instagram Post](https://user-images.githubusercontent.com/78538870/191680807-43ee2321-a7f6-4b35-a251-8406546e9549.png)
Instagram Story:
![Instagram Story](https://user-images.githubusercontent.com/78538870/191680853-30c993c5-fec1-4fba-ada9-8ee78ffe710f.png)
Twitter and LinkedIn:
![LinkedIn   Twitter](https://user-images.githubusercontent.com/78538870/191680925-fdb59241-068a-4ae1-adf2-3b34a1daa0fc.png)

**Date requested**
Today or tomorrow(if possible) and the day before the evet(28th of September)

**Channel requested**
Facebook, Twitter, LinkedIn, Instagram

Thank you 🙏

**Comment by ddskier** [comment]
Scheduled for today, 9/22 and repeating on 9/28. Posting to Twitter, FB, LinkedIn
