### ISSUE TITLE
[AMPLIFICATION] - Event Storming Free Online Tool

### ISSUE THREAD

**Issue by amantinband** [dotnet-foundation/content#99]
**Please describe the content.**
Hi! Domain-Driven Design is very common within the .NET community, yet Event Storming, a great tool for modeling the domain is rarely practiced, especially remotely.
This video includes everything individuals need to get started, and also a free online tool they can start using today 🙂

**URL of the content**
https://www.youtube.com/watch?v=7LFxWgfJEeI

**Copy for the content**
All you need to know to get started with Event Storming, including a free collaborative online tool

**Date requested**
23/9?

**Channel requested**
Facebook, Twitter, LinkedIn

**Additional context**

![Frame 179 (4)](https://user-images.githubusercontent.com/39407673/191785813-486a518c-16b7-47f2-b5ce-3495feed9d84.jpg)

Thanks again for amplifying content from the community! ❤️

**Comment by ddskier** [comment]
Scheduled for Sept 26 & Oct 5. Will post to Twitter, LinkedIn, FB.

**Comment by amantinband** [comment]
Awesome, thanks!! 🫶🏼
